<style>
    input[type=file]{
        padding-top: 0px;
        padding-left: 0px;
    }
    #productos_table .fa-trash{
        color:red;
    }
    #productos_table input{
        width: 80px;
    }
</style>
<link rel="stylesheet" type="text/css" href="/application/custom/css/validaciones.css">
<div class="page-bar">
        <ul class="page-breadcrumb">
            <li>
                <a href="javascript:;">Procesos</a>
                 <i class="fa fa-angle-right"></i>
            </li>
            <li>
                <a href="/procesos/credito">Notas de crédito</a>
                 <i class="fa fa-angle-right"></i>
            </li>
            <li>
                <a href="javascript:;"><?php echo '#'.$form->get('idnotacredito')->getValue()?></a>
            </li>
        </ul>
</div>
<div id="form_container">
    <form class="form-horizontal" id="frm-nota" action="/procesos/credito/editar/<?php echo $form->get('idnotacredito')->getValue()?>" method="post" enctype="multipart/form-data">
    <div class="portlet box green" style="border-left-width: 0px; border-bottom-width: 0px; border-right-width: 0px;">
        <div class="portlet-body form">
            <div class="form-body">
                
                 <div class="row">
                    <div class="col-md-6">
                         <div class="form-group">
                             <label class="control-label col-md-3">Creado por: </label>
                             <div class="col-md-9">
                                 <p class="form-control-static"><?php echo $entity->getUsuarioRelatedByIdusuario()->getUsuarioNombre()?></p>
                             </div>
                         </div>
                    </div>
                     <div class="col-md-6">
                         <div class="form-group">
                             <label class="control-label col-md-3">Auditor:</label>
                             <div class="col-md-9">
                                 <?php 
                                   
                                    if($entity->getNotacreditoRevisada()){
                                        $auditor = $entity->getUsuarioRelatedByIdauditor()->getUsuarioNombre();
                                    }else{
                                        $auditor = 'N/D';
                                    } 
                                ?>
                                 <p class="form-control-static"><?php echo $auditor?></p>
                             </div>
                         </div>
                    </div>
                 </div>
            </div>
        </div>
    </div>
    <div class="portlet box green" style="border-left-width: 0px; border-bottom-width: 0px; border-right-width: 0px;">
        <div class="portlet-body form">
            <div class="form-body">
                 <h3 class="page-title">Notacredito - <?php echo '#'.$form->get('idnotacredito')->getValue()?></h3>
                <div class="row">
                    <div class="form-group">
                        <div class="col-md-6">
                            <?php echo $this->formLabel($form->get('notacredito_fechanotacredito')) ?>  
                            <?php echo $this->formText($form->get('notacredito_fechanotacredito')) ?> 
                        </div>
                        <div class="col-md-6">
                            <?php echo $this->formHidden($form->get('idproveedor')); ?>  
                            <?php echo $this->formLabel($form->get('idproveedor_autocomplete')); ?>  
                            <div class="input-group">
                                <span class="input-group-addon">
                                    <i class="fa fa-search"></i>
                                </span>
                                 <?php echo $this->formText($form->get('idproveedor_autocomplete')); ?>  

                            </div>

                        </div>
                        
                    </div>
                    <div class="form-group">
                        
                        <div class="col-md-6">
                            <?php echo $this->formLabel($form->get('notacredito_folio')) ?>  
                            <?php echo $this->formText($form->get('notacredito_folio')) ?> 
                        </div>
                        <div class="col-md-6">
                            <?php echo $this->formLabel($form->get('notacredito_factura')) ?>  
                            <?php echo $this->formFile($form->get('notacredito_factura')) ?> 
                        </div>
                    </div>
                    
                    <div class="form-group">
                        <div class="col-md-6">

                            <?php echo $this->formLabel($form->get('idalmacen')) ?>  
                            <?php echo $this->formSelect($form->get('idalmacen')) ?> 
                        </div>
                        <div class="col-md-6">
                            <?php echo $this->formLabel($form->get('notacredito_revisada')) ?>  
                            <?php echo $this->formSelect($form->get('notacredito_revisada')) ?> 
                        </div>
                    </div>
                </div>
                 <div class="row">
                    <div class="form-group">
                        <div class="col-md-6">
                            <label>Creado por</label>
                            <input class="form-control" type="text" value="<?php echo $entity->getUsuarioRelatedByIdusuario()->getUsuarioNombre();?>" readonly="readonly"> 
                        </div>
                        <div class="col-md-6">
                            <label>Auditor</label>
                            <?php  
                                if($entity->getNotacreditoRevisada()){
                                    $auditor = $entity->getUsuarioRelatedByIdauditor()->getUsuarioNombre();
                                }else{
                                    $auditor = 'N/D';
                                } 
                            ?>
                            <input class="form-control" type="text" value="<?php echo $auditor;?>" readonly="readonly"> 
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="portlet box green" style="border-left-width: 0px; border-bottom-width: 0px; border-right-width: 0px;">
        <div class="portlet-body form">
            <div class="portlet-body form">
                <div class="form-body">
                    <h3 class="page-title">Productos</h3><br><br>
                    <div class="row">
                        <div class="form-group">
                            <div class="col-md-5 col-md-offset-6">
                                <div class="input-group">
                                    <span class="input-group-addon">
                                        <i class="fa fa-search"></i>
                                    </span>
                                    <input id="idproducto" type="hidden">
                                    <input id="producto_iva" type="hidden">
                                    <input id="producto_autocomplete" class="form-control" type="text">
                                </div>
                            </div>
                            <div class="col-md-1">
                                <button disabled id="producto_add" class="btn grey-mint" type="button">Agregar</button>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="table-responsive">
                        <table class="table" id="productos_table">
                            <thead>
                                <th>Producto</th>
                                <th>Cantidad</th>
                                <th>Precio</th>
                                <th>C.U. Neto</th>
                                <th>Desc. (%)</th>
                                <th>IEPS (%)</th>
                                <th>Subtotal</th>
                                <th>Revisada</th>
                                <th>Almacen</th>
                                <th>Opciones</th>
                            </thead>
                            <tbody>
                                <?php $detalle = new Notacreditodetalle()?>
                                <?php foreach ($notacredito_detalle as $detalle) :?>
                                <tr id="<?php echo $detalle->getIdnotacreditodetalle()?>">
                                    <td>
                                        <input type="hidden" name="productos[<?php echo $detalle->getIdnotacreditodetalle()?>][subtotal]" value="<?php echo $detalle->getNotacreditodetalleSubtotal()?>">
                                        <input type="hidden" name="productos[<?php echo $detalle->getIdnotacreditodetalle()?>][costo_unitario]" value="<?php echo $detalle->getNotacreditodetalleCostounitario()?>">
                                        <input type="hidden" name="productos[<?php echo $detalle->getIdnotacreditodetalle()?>][producto_iva]" value="true">
                                        <input type="hidden" name="productos[<?php echo $detalle->getIdnotacreditodetalle()?>][idproducto]" value="<?php echo $detalle->getIdproducto()?>">
                                        <?php echo $detalle->getProducto()->getProductoNombre()?>
                                    </td>
                                    <td>
                                        <input type="text" name="productos[<?php echo $detalle->getIdnotacreditodetalle()?>][cantidad]" value="<?php echo $detalle->getNotacreditodetalleCantidad()?>"> 
                                    </td>
                                    <td>
                                        <input type="text" name="productos[<?php echo $detalle->getIdnotacreditodetalle()?>][precio]" value="<?php echo $detalle->getNotacreditodetalleCostounitario()?>"> 
                                    </td>
                                    
                                    <td class="costo_unitario">
                                        <?php echo money_format('%(#10n',$detalle->getNotacreditodetalleCostounitarioneto())?>
                                    </td>
                                    
                                    <td>
                                        <input type="text" name="productos[<?php echo $detalle->getIdnotacreditodetalle()?>][descuento]" value="<?php echo $detalle->getNotacreditodetalleDescuento()?>"> 
                                    </td>
                                    <td>
                                        <input type="text" name="productos[<?php echo $detalle->getIdnotacreditodetalle()?>][ieps]" value="<?php echo $detalle->getNotacreditodetalleIeps()?>"> 
                                    </td>
                                    <td class="subtotal" >
                                        <?php echo money_format('%(#10n',$detalle->getNotacreditodetalleSubtotal())?>
                                    </td>
                                    <td>
                                        <?php if($detalle->getNotacreditodetalleRevisada()) :?>
                                            <input checked type="checkbox" name=productos[<?php echo $detalle->getIdnotacreditodetalle()?>][revisada]>
                                        <?php else :?>
                                            <input type="checkbox" name=productos[<?php echo $detalle->getIdnotacreditodetalle()?>][revisada]>
                                        <?php endif?>
                                    </td>
                                    <td>
   
                                        <select class="form-control" name="productos[<?php echo $detalle->getIdnotacreditodetalle()?>][almacen]">
                                            <?php foreach ($almacenes as $key => $value) :?>
                                                <?php if($key == $detalle->getIdalmacen()) :?>
                                                    <option selected value="<?php echo $key?>"><?php echo $value?></option>
                                                <?php else :?>
                                                     <option value="<?php echo $key?>"><?php echo $value?></option>
                                                <?php endif;?>
                                            <?php endforeach; ?>
                                        </select> 
                                    </td>
                                    <td><a href="javascript:;"><i class="fa fa-trash"></i></a></td>
                                </tr>
                                <?php endforeach?>

                            </tbody>
                            <tfoot>
                                <tr>
                                    <td colspan="8"></td>
                                    <td>SUBTOTAL</td>
                                    <?php echo $this->formHidden($form->get('notacredito_subtotal')) ?> 
                                    <td id="subtotal"><?php echo money_format('%(#10n',$entity->getNotacreditoSubtotal())?></td>
                                </tr>
                                <tr>
                                    <td colspan="8"></td>
                                    <td>IEPS</td>
                                    <?php echo $this->formHidden($form->get('notacredito_ieps')) ?> 
                                    <td id="ieps"><?php echo money_format('%(#10n',$entity->getNotacreditoIeps())?></td>
                                </tr>
                                <tr>
                                    <td colspan="8"></td>
                                    <td>IVA</td>
                                    <?php echo $this->formHidden($form->get('notacredito_iva')) ?> 
                                    <td id="iva"><?php echo money_format('%(#10n',$entity->getNotacreditoIva())?></td>
                                </tr>
                                <tr>
                                    <td colspan="8"></td>
                                    <td>TOTAL</td>
                                    <?php echo $this->formHidden($form->get('notacredito_total')) ?> 
                                    <td id="total"><?php echo money_format('%(#10n',$entity->getNotacreditoTotal())?></td>
                                </tr>
                            </tfoot>
                        </table>
                        </div>
                    </div>
                </div>
                
                <input type="hidden" id="ivaValor" value="<?php echo $iva->getTasaivavalor()?>">
                
                <div class="form-actions right">
                    <button class="btn blue" type="submit">
                        <i class="fa fa-check"></i>
                        Guardar 
                    </button>
                </div>
            </div>
        </div>
    </div>
</form>
</div>
<script type="text/javascript" src="/application/custom/js/procesos/notacredito.js"></script>
<script>
    var $form = $('#form_container').compra();
    $form.edit(<?php echo $anio_activo?>,<?php echo $mes_activo?>,<?php echo $mes_notacredito ?>,<?php echo $anio_notacredito ?>,<?php echo json_encode($almacenes)?>,<?php echo $count?>);
</script>
