<link rel="stylesheet" type="text/css" href="/application/custom/css/validaciones.css">
<div id="form_container">
    <h3 class="page-title">Cuenta bancaria - <?php echo '#' . $form->get('idcuentabancaria')->getValue() ?></h3>
    <div class="page-bar">
        <ul class="page-breadcrumb">
            <li>
                <a href="javascript:;">Catalogo</a>
                <i class="fa fa-angle-right"></i>
            </li>
            <li>
                <a href="/flujoefectivo/cuentabancaria">Cuenta bancaria</a>
                <i class="fa fa-angle-right"></i>
            </li>
            <li>
                <a href="javascript:;"><?php echo '#' . $form->get('idcuentabancaria')->getValue() ?></a>
            </li>
        </ul>
    </div>
    <?php foreach ($messages->getSuccessMessages() as $message): ?>
        <div class="alert alert-success alert-dismissable">
            <button class="close" aria-hidden="true" data-dismiss="alert" type="button"></button>
            <strong>Exito!</strong>
            <?php echo $message ?>
        </div>
    <?php endforeach; ?>

    <?php foreach ($messages->getErrorMessages() as $message): ?>
        <div class="alert alert-danger alert-dismissable">
            <button class="close" aria-hidden="true" data-dismiss="alert" type="button"></button>
            <strong>Error!</strong>
            <?php echo $message ?>
        </div>
    <?php endforeach; ?>
    <?php
    $form->setAttribute('action', '/flujoefectivo/cuentabancaria/editar/' . $form->get('idcuentabancaria')->getValue());
    echo $this->form()->openTag($form);
    ?>
    <div class="portlet box green" style="border-left-width: 0px; border-bottom-width: 0px; border-right-width: 0px;">
        <div class="portlet-body form">
            <div class="form-body">
                <h3 class="form-section">Información general</h3>
                <div class="row">
                    <div class="col-md-6">
                        <?php echo $this->formHidden($form->get('idcuentabancaria')) ?>
                        <?php echo $this->formLabel($form->get('cuentabancaria_banco')); ?>  
                        <?php echo $this->formText($form->get('cuentabancaria_banco')); ?>
                    </div>
                    <div class="col-md-6">
                        <?php echo $this->formLabel($form->get('cuentabancaria_nocuenta')); ?>  
                        <?php echo $this->formText($form->get('cuentabancaria_nocuenta')); ?>
                    </div>
                    <div class="col-md-6">
                        <?php echo $this->formLabel($form->get('cuentabancaria_balance')); ?>  
                        <?php echo $this->formText($form->get('cuentabancaria_balance')); ?>
                    </div>
                </div>
                <br>
                <div class="row">
                    <div class="col-md-12">
                        <p>(*)Campos obligatorios</p>
                    </div>
                    <div class="btn-set pull-right">
                <button class="btn blue" id="plantilla_save" type="submit">
                    <i class="fa fa-check"></i>
                    Guardar
                </button>
            </div>
                </div>
            
            
            
            </div>
        </div>
    </div>
    <div class="portlet box green" style="border-left-width: 0px; border-bottom-width: 0px; border-right-width: 0px;">
        <div class="portlet-body form">
            <div class="form-body">
                 <h3 class="form-section">Movimientos</h3>
                 <div class="row">
                     <div class="col-md-12">
                     <table class="table table-striped table-bordered table-hover order-column" id="datatable"  style="border-bottom-width: 0px;">
                <thead>
                    <tr>
                        <th class="text"> Fecha </th>
                        <th class="text"> Tipo </th>
                        <th class="text"> Cantidad </th>
                        <th class="text"> Medio </th>
                        <th class="text"> Referencia </th>
                        <th class="text"> Comprobante </th>
                    </tr>
                </thead>
                <tbody class="text">
                    <?php
                    $entity = new Flujoefectivo();
                    foreach ($flujoefectivo as $entity) :
                        $cobrado = ($entity->getFlujoefectivoMediodepago() == 'cheque' && $entity->getFlujoefectivoChequecirculacion()) ? "Cobrado" : "No cobrado";
                        $class = ($entity->getFlujoefectivoMediodepago() == 'cheque' && $entity->getFlujoefectivoChequecirculacion()) ? "info" : "danger";
                        ?>
                        <tr id="<?php echo $entity->getIdflujoefectivo() ?>">
                            <td><?php echo $entity->getFlujoefectivoFecha('d/m/Y') ?></td>
                            <td><?php echo $entity->getFlujoefectivoTipo() ?></td>
                            <td><?php echo $entity->getFlujoefectivoCantidad() ?></td>
                            <td><?php echo $entity->getFlujoefectivoMediodepago() . " ";if ($entity->getFlujoefectivoMediodepago() == 'cheque') { ?><span class="label label-sm label-<?php echo $class ?>"> <?php echo $cobrado ?> </span><?php } ?></td>
                            <td><?php echo $entity->getFlujoefectivoReferencia() ?></td>
                            <td><?php echo ($entity->getFlujoefectivoComprobante() != null) ? '<a target="_blank" href="' . $entity->getFlujoefectivoComprobante() . '"><i class="fa fa-file"></i></a>' : " "; ?></td>
                        </tr>                            
                    <?php endforeach; ?>
                    <?php
                    $entity = new Abonoproveedordetalle();
                    foreach ($saldoproveedor as $entity) :
                        $cobrado = ($entity->getAbonoproveedordetalleMediodepago() == 'cheque' && $entity->getAbonoproveedordetalleChequecirculacion()) ? "Cobrado" : "No cobrado";
                        $class = ($entity->getAbonoproveedordetalleMediodepago() == 'cheque' && $entity->getAbonoproveedordetalleChequecirculacion()) ? "info" : "danger";
                        ?>
                        <tr id="<?php echo $entity->getIdabonoproveedordetalle() ?>">
                            <td><?php echo $entity->getAbonoproveedordetalleFechaabono('d/m/Y') ?></td>
                            <td><?php echo $entity->getAbonoproveedordetalleTipo() ?></td>
                            <td><?php echo $entity->getAbonoproveedordetalleCantidad() ?></td>
                            <td><?php echo $entity->getAbonoproveedordetalleMediodepago() . " ";if ($entity->getAbonoproveedordetalleMediodepago() == 'cheque') { ?><span class="label label-sm label-<?php echo $class ?>"> <?php echo $cobrado ?> </span><?php } ?></td>
                            <td><?php echo $entity->getAbonoproveedordetalleReferencia() ?></td>
                            <td><?php echo ($entity->getAbonoproveedordetalleComprobante() != null) ? '<a target="_blank" href="' . $entity->getAbonoproveedordetalleComprobante() . '"><i class="fa fa-file"></i></a>' : " "; ?></td>
                        </tr>                            
                    <?php endforeach; ?>
                </tbody>
            </table>
                     </div>
                 </div>
            </div>
        </div>
    </div>
    
    
    
    
    
</div>
<script src="/application/global/scripts/datatable.js" type="text/javascript"></script>
<script src="/application/global/plugins/datatables/datatables.min.js" type="text/javascript"></script>
<script src="/application/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.js" type="text/javascript"></script>
<script type="text/javascript" src="/application/custom/js/flujoefectivo/cuentabancaria.js"></script>
<script>
    var $form = $('#form_container').cuentabancaria();
    $form.edit();
</script>