<link href="/application/global/plugins/datatables/datatables.min.css" rel="stylesheet" type="text/css" />
<link href="/application/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.css" rel="stylesheet" type="text/css" />
<div id="my_container">
    <h3 class="page-title">Ajustes de inventarios</h3>
    <div class="page-bar">
        <ul class="page-breadcrumb">
            <li>
                <a href="/procesos/ajustesinventarios">Ajustes de inventarios</a>
            </li>
        </ul>
    </div>
    <?php foreach ($messages->getSuccessMessages() as $message):?>
        <div class="alert alert-success alert-dismissable">
            <button class="close" aria-hidden="true" data-dismiss="alert" type="button"></button>
            <strong>Éxito!</strong>
            <?php echo $message?>
        </div>
    <?php endforeach;?>
    <div class="portlet box " style="border-left-width: 0px; border-bottom-width: 0px; border-right-width: 0px;">
        <div class="portlet-body form">
            <div class="form-body">
                <div class="btn-set pull-right">
                    <a href="/procesos/ajustesinventarios/nuevo"><button class="btn default" type="button" style="margin-bottom: 15px;">Nuevo ajuste de inventario</button></a>
                </div>
                <table class="table table-striped table-bordered table-hover order-column" id="datatable"  style="border-bottom-width: 0px;">
                    <thead>
                        <tr>
                            <th class="text"> Fecha </th>
                            <th class="text"> Almacen </th>
                            <th class="text"> Producto </th>
                            <th class="text"> U. medida </th>
                            <th class="text"> Tipo </th>
                            <th class="text"> Cantidad </th>
                            <th class="text"> Opciones </th>
                        </tr>
                    </thead>
                    <tbody class="text">
                        <?php $entity = new Ajusteinventario();foreach ($collection as $entity) : ?>
                        <tr id="<?php echo $entity->getIdajusteinventario()?>">
                            <td><?php echo $entity->getAjusteinventarioFecha('Y/m/d') ?></td>
                            <td><?php echo $entity->getAlmacen()->getAlmacenNombre() ?></td>
                            <td><?php echo $entity->getProducto()->getProductoNombre() ?></td>
                            <td><?php echo $entity->getProducto()->getUnidadmedida()->getUnidadmedidaNombre() ?></td>
                            <td><?php echo $entity->getAjusteinventarioTipo() ?></td>
                            <td><?php echo $entity->getAjusteinventarioCantidad() ?></td>
                            <td>
                                <div class="btn-group">
                                    <button class="btn btn-xs green dropdown-toggle" type="button" data-toggle="dropdown" aria-expanded="false"> Acciones
                                        <i class="fa fa-angle-down"></i>
                                    </button>
                                    <ul class="dropdown-menu" role="menu">
                                        <li>
                                            <a href="/procesos/ajustesinventarios/editar/<?php echo $entity->getIdajusteinventario()?>">
                                            <i class="fa fa-pencil"></i> Editar </a>
                                        </li>
                                        <?php if(\Application\Dashboard\Controller\IndexController::validateprocessbyinventariomesfordelete(false,$entity->getAjusteinventarioFecha(), array($entity->getIdalmacen()))):?>
                                        <li>
                                            <a href="javascript:;" class="delete_modal">
                                                <i class="fa fa-trash"></i> Eliminar </a>
                                        </li>
                                        <?php endif;?>
                                    </ul>
                                </div>
                            </td>
                        </tr>                            
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
        
    </div>
</div>

<script src="/application/global/scripts/datatable.js" type="text/javascript"></script>
<script src="/application/global/plugins/datatables/datatables.min.js" type="text/javascript"></script>
<script src="/application/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.js" type="text/javascript"></script>
<script src="/application/custom/js/procesos/ajustesinventarios.js" type="text/javascript"></script>	
<script>
    var $plugin = $('#my_container').ajustesinventarios({'idrol':<?php echo $idrol?>});
    $plugin.list();
</script>