<?php //echo '<pre>';var_dump($messages->getErrorMessages());echo'</pre>'; ?>



<?php //foreach ($padres as $item): ?>
    <?php //echo $item->getCategoriaNombre() ?>
<?php //endforeach ?>

<h3 class="page-title">Registro categoría</h3>
<div class="page-bar">
    <ul class="page-breadcrumb">
        <li>
            <a href="/catalogo/categoria">Categorías</a>
            <i class="fa fa-angle-right"></i>
        </li>
        <li>
            <span>Registro</span>
        </li>
    </ul>
</div>
<?php foreach ($messages->getErrorMessages() as $message):?>
    <div class="alert alert-danger alert-dismissable">
        <button class="close" aria-hidden="true" data-dismiss="alert" type="button"></button>
        <strong>Error!</strong>
        <?php echo $message?>
        
    </div>
<?php endforeach;?>
<?php
    $form->setAttribute('action', '/catalogo/categoria/editar/'.$form->get('idcategoria')->getValue());
    echo $this->form()->openTag($form);
?>
<div class="portlet box green" style="border-left-width: 0px; border-bottom-width: 0px; border-right-width: 0px;">
    <div class="portlet-body form">
        <div class="form-body">
            <h3 class="form-section">Información general</h3>
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <?php echo $this->formLabel($form->get('categoria_nombre')) ?>  
                        <?php echo $this->formHidden($form->get('idcategoria')) ?>
                        <?php echo $this->formText($form->get('categoria_nombre')) ?>
                        <span for="categoria_nombre" style="color:red; display: none"><b>Ya existe una subcategoria con el mismo nombre</b></span>
                    </div>
                </div>
                <div class="col-md-6" style="padding-top: 30px;">
                    <div class="form-group">
                        <?php echo $this->formLabel($form->get('categoria_almacenable')) ?>  
                        <?php echo $this->formCheckbox($form->get('categoria_almacenable')) ?>
                    </div>
                </div>
                
                
            </div>
            <div class="row">
                <div class="col-md-12">
                    <p>(*)Campos obligatorios</p>
                </div>
            </div>
        </div>
        <div class="form-actions right" style="background-color: white;">
            <button class="btn blue" type="submit">
                <i class="fa fa-check"></i>
                Guardar
            </button>
        </div>
    </div>
    
</div>

<script>

    $('button[type=submit]').on('click',function(e){
        
        e.preventDefault();
        var subcategoria = $('input[name=categoria_nombre]').val();
        
        var idsubcategory = $('input[name=idcategoria]').val();
        $.ajax({
            url:'/catalogo/categoria/validatesubcategory',
            data:{subcategory_name:subcategoria,idsubcategory:idsubcategory},
            dataType: 'JSON',
            type: 'POST',
            success: function (data, textStatus, jqXHR) {
                if(data){
                    $('[for=categoria_nombre]').show();
                }else{
                    $('form').submit();
                }
            }
        });
        
    });

</script>