<link href="/application/global/plugins/datatables/datatables.min.css" rel="stylesheet" type="text/css" />
<link href="/application/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.css" rel="stylesheet" type="text/css" />

<?php foreach ($messages->getSuccessMessages() as $message):?>
    <div class="alert alert-success alert-dismissable">
        <button class="close" aria-hidden="true" data-dismiss="alert" type="button"></button>
        <strong>Éxito!</strong>
        <?php echo $message?>
    </div>
<?php endforeach;?>

<h3 class="page-title">Registro categoria</h3>
<div class="page-bar">
    <ul class="page-breadcrumb">
        <li>
            <a href="/catalogo/categoria">Categorias</a>
            <i class="fa fa-angle-right"></i>
        </li>
        <li>
            <span>Registro</span>
        </li>
    </ul>
</div>
<?php foreach ($messages->getErrorMessages() as $message):?>
    <div class="alert alert-danger alert-dismissable">
        <button class="close" aria-hidden="true" data-dismiss="alert" type="button"></button>
        <strong>Error!</strong>
        <?php echo $message?>
        
    </div>
<?php endforeach;?>
<?php
    $form->setAttribute('action', '/catalogo/categoria/editar/'.$form->get('idcategoria')->getValue());
    echo $this->form()->openTag($form);
?>
<div class="portlet box green" style="border-left-width: 0px; border-bottom-width: 0px; border-right-width: 0px;">
    <div class="portlet-body form">
        <div class="form-body">
            <h3 class="form-section">Información general</h3>
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <?php echo $this->formLabel($form->get('categoria_nombre')) ?>  
                        <?php echo $this->formText($form->get('categoria_nombre')) ?>
                    </div>
                </div>
                
                
            </div>
            <div class="row">
                <div class="col-md-12">
                    <p>(*)Campos obligatorios</p>
                </div>
            </div>
        </div>
        <div class="form-actions right" style="background-color: white;">
            <button class="btn blue" type="submit">
                <i class="fa fa-check"></i>
                Guardar
            </button>
        </div>
    </div>
    
    <div class="portlet box green" style="border-left-width: 0px; border-bottom-width: 0px; border-right-width: 0px;">
        
        <div class="portlet-body form">
            <div class="form-body">
                <div class="btn-set pull-right">
                    <a href="/catalogo/categoria/nuevasub/<?php echo $form->get('idcategoria')->getValue() ?> "><button class="btn default" type="button" style="margin-bottom: 15px;">Nueva sub categoria</button></a>
                </div>
                <h2>Sub Categorias</h2><br>
                <table class="table table-striped table-bordered table-hover order-column" id="datatable" style="border-bottom-width: 0px;">
                    <thead>
                        <tr>
                            <th class="text-center"> Categoria </th>
                            <th class="text-center"> Categoría almacenable </th>
                            <th class="text-center"> Categoria principal </th>
                            <th class="text-center"> Acciones </th>
                        </tr>
                    </thead>
                    <tbody class="text-center">
                        <?php foreach ($collection as $entity) : ?>
                            
                            <?php if ($entity->getIdcategoriapadre() != 0): ?>

                        
                                <tr id="<?php echo $entity->getIdcategoria() ?>">
                                <td><?php echo $entity->getCategoriaNombre() ?></td>
                                <td>
                                    <?php if ($entity->getCategoriaAlmacenable() == 1): ?>
                                        <span class="label label-sm label-primary ">Almacenable</span>
                                    <?php else: ?>
                                        <span class="label label-sm label-danger">No almacenable</span>
                                    <?php endif ?>
                                </td>
                                <td><?php echo $form->get('categoria_nombre')->getValue() ?></td>
                                
                                <td>
                                    <div class="btn-group">
                                        <button class="btn btn-xs green dropdown-toggle" type="button" data-toggle="dropdown" aria-expanded="false"> Acciones
                                            <i class="fa fa-angle-down"></i>
                                        </button>
                                        <ul class="dropdown-menu" role="menu">
                                            <li>
                                                <a href="/catalogo/categoria/editarsub/<?php echo $entity->getIdcategoria()?>">
                                                    <i class="fa fa-pencil"></i> Editar </a>
                                            </li>
                                            <li>
                                                <a href="javascript:;" class="delete_modal">
                                                    <i class="fa fa-trash"></i> Eliminar </a>
                                            </li>
                                        </ul>
                                    </div>
                                </td>
                            </tr>
                            
                            <?php endif ?>
                            
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
            
        </div>
            
        </div>
</div>

<script src="/application/global/scripts/datatable.js" type="text/javascript"></script>
<script src="/application/global/plugins/datatables/datatables.min.js" type="text/javascript"></script>
<script src="/application/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.js" type="text/javascript"></script>
<script src="/application/custom/js/catalogo/usuario.js" type="text/javascript"></script>	

<script>
    $(document).ready(function(){
        var table = $('#datatable');
                $.ajax({
                    url:'/application/json/datatable/lang_es.json',
                    dataType:'json',
                    success:function(data){
                       table.DataTable({
                           "language":data,
                           "order":[],
                       });
                    },
                });
        $('.delete_modal').click(function(){

          var id = $(this).closest('tr').attr('id');
          var tmpl = [
            // tabindex is required for focus
            ' <div class="modal fade draggable-modal" id="draggable" tabindex="-1" role="basic" aria-hidden="true">',
              '<div class="modal-header">',
                '<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>',
                '<h4 class="modal-title">ADVERTENCIA</h4>', 
              '</div>',
              '<form method="post" action="/catalogo/categoria/eliminar/'+id+'">',
                '<div class="modal-body">',
                  '<p>¿Estas seguro que deseas eliminar el registro seleccionado?</p>',
                '</div>',
                '<div class="modal-footer">',
                  '<a href="#" data-dismiss="modal" class="btn btn-default">Cancelar</a>',
                  '<button class="btn btn-danger" type="submit">Eliminar</button>',
                '</div>',
              '</form>',
            '</div>'
          ].join('');
          $(tmpl).modal();
        });
    }); 
</script>