<link href="/application/global/plugins/datatables/datatables.min.css" rel="stylesheet" type="text/css" />
<link href="/application/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.css" rel="stylesheet" type="text/css" />
<div id="my_container">
    <h3 class="page-title">Categorias</h3>
    <div class="page-bar">
        <ul class="page-breadcrumb">
            <li>
                <a href="/catalogo/categoria">Categorias</a>
            </li>
        </ul>
    </div>
    <?php foreach ($messages->getSuccessMessages() as $message):?>
        <div class="alert alert-success alert-dismissable">
            <button class="close" aria-hidden="true" data-dismiss="alert" type="button"></button>
            <strong>Éxito!</strong>
            <?php echo $message?>
        </div>
    <?php endforeach;?>
    <div class="portlet box green" style="border-left-width: 0px; border-bottom-width: 0px; border-right-width: 0px;">
        <div class="portlet-body form">
            <div class="form-body">
                <div class="btn-set pull-right">
                    <a href="/catalogo/categoria/nuevo"><button class="btn default" type="button" style="margin-bottom: 15px;">Nueva categoria</button></a>
                </div>
                <h2>Categorias principales</h2><br>
                <table class="table table-striped table-bordered table-hover order-column" id="datatable" style="border-bottom-width: 0px;">
                    <thead>
                        <tr>
                            <th class="text-center"> Categoria </th>
                            <th class="text-center"> Categoría almacenable </th>
                            <th class="text-center"> Acciones </th>
                        </tr>
                    </thead>
                    <tbody class="text-center">
                        <?php foreach ($collection as $entity) : ?>
                            
                            <tr id="<?php echo $entity->getIdcategoria() ?>">
                                <td><?php echo $entity->getCategoriaNombre() ?></td>
                                <td>
                                    <?php if ($entity->getCategoriaAlmacenable() == 1): ?>
                                        <span class="label label-sm label-primary ">Almacenable</span>
                                    <?php else: ?>
                                        <span class="label label-sm label-danger">No almacenable</span>
                                    <?php endif ?>
                                </td>
                                
                                <td>
                                    <div class="btn-group">
                                        <a href="/catalogo/categoria/editar/<?php echo $entity->getIdcategoria()?>">
                                            <button class="btn blue btn-xs">
                                                    <i class="fa fa-pencil"></i> Editar 
                                            </button>
                                        </a>
                                        <a href="javascript:;" class="delete_modal_iva">
                                            <button class="btn red btn-xs">
                                                    <i class="fa fa-trash"></i> Eliminar 
                                            </button>
                                        </a>
                                        
                                    </div>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<script src="/application/global/scripts/datatable.js" type="text/javascript"></script>
<script src="/application/global/plugins/datatables/datatables.min.js" type="text/javascript"></script>
<script src="/application/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.js" type="text/javascript"></script>
<script src="/application/custom/js/catalogo/categoria.js" type="text/javascript"></script>	
<script>
    
    //var plugin = $('#my_container').usuario();
    
    

</script>