<?php echo '<pre>';var_dump($messages->getErrorMessages());echo'</pre>'; ?>



<?php //foreach ($padres as $item): ?>
    <?php //echo $item->getCategoriaNombre() ?>
<?php //endforeach ?>

<h3 class="page-title">Registro categoria</h3>
<div class="page-bar">
    <ul class="page-breadcrumb">
        <li>
            <a href="/catalogo/categoria">Categorias</a>
            <i class="fa fa-angle-right"></i>
        </li>
        <li>
            <span>Registro</span>
        </li>
    </ul>
</div>
<?php foreach ($messages->getErrorMessages() as $message):?>
    <div class="alert alert-danger alert-dismissable">
        <button class="close" aria-hidden="true" data-dismiss="alert" type="button"></button>
        <strong>Error!</strong>
        <?php echo $message?>
        
    </div>
<?php endforeach;?>
<?php
    $form->setAttribute('action', '/catalogo/categoria/nuevo');
    echo $this->form()->openTag($form);
?>
<div class="portlet box green" style="border-left-width: 0px; border-bottom-width: 0px; border-right-width: 0px;">
    <div class="portlet-body form">
        <div class="form-body">
            <h3 class="form-section">Información general</h3>
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <?php echo $this->formLabel($form->get('categoria_nombre')) ?>  
                        <?php echo $this->formText($form->get('categoria_nombre')) ?>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <?php echo $this->formLabel($form->get('categoria_padre')) ?>  
                        <?php echo $this->formSelect($form->get('categoria_padre')) ?>
                    </div>
                </div>
                <div class="col-md-6 col-md-offset-6">
                    <div class="form-group pull-right">
                        <?php echo $this->formLabel($form->get('categoria_almacenable')) ?>  
                        <?php echo $this->formCheckbox($form->get('categoria_almacenable')) ?>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <p>(*)Campos obligatorios</p>
                </div>
            </div>
        </div>
        <div class="form-actions right">
            <button class="btn blue" type="submit">
                <i class="fa fa-check"></i>
                Guardar
            </button>
        </div>
    </div>
</div>