<div class="user-login-5">
            <div class="row bs-reset">
                <div class="col-md-6 bs-reset">
                    <div class="login-bg" style="background-image:url(/application/pages/img/login/bg1.jpg)">
                        <img class="login-logo" src="/application/login/login_logo.png" /> </div>
                </div>
              
                <div class="col-md-6 login-container bs-reset">
                    
                    
                    <div class="login-content">
                        <h1>AERSA CFCI Inicio de sesión</h1>
                        <p> Control de flujo de efectivo, costos e inventarios. </p>
                        <form action="/login" class="login-form" method="post">
                            <div class="alert alert-danger display-hide">
                                <button class="close" data-close="alert"></button>
                                <span>Por favor ingrese su nombre de usuario y contraseña. </span>
                            </div>
                            <div class="row">
                                <?php foreach ($messages->getErrorMessages() as $message): ?>
                                    <div class="alert alert-danger alert-dismissable">
                                        <button class="close" aria-hidden="true" data-dismiss="alert" type="button"></button>
                                        <strong>Error!</strong>
                                        <?php echo $message ?>
                                    </div>
                                <?php endforeach; ?>
                                <div class="col-xs-6">
                                    <input class="form-control form-control-solid placeholder-no-fix form-group" type="text" autocomplete="off" placeholder="Nombre de usuario" name="usuario_username" required/> </div>
                                <div class="col-xs-6">
                                    <input class="form-control form-control-solid placeholder-no-fix form-group" type="password" autocomplete="off" placeholder="Contraseña" name="usuario_password" required/> </div>
                            </div>
                            <div class="row">
                                <div class="col-sm-4">
                 
                                </div>
                                <div class="col-sm-8 text-right">
                                    <div class="forgot-password">
                                        <!--<a href="javascript:;" id="forget-password" class="forget-password">Olvidate tu contraseña?</a>-->
                                    </div>
                                    <button class="btn blue" type="submit">Iniciar sesión</button>
                                </div>
                            </div>
                        </form>
                        <!-- BEGIN FORGOT PASSWORD FORM -->
                        <form class="forget-form" action="javascript:;" method="post">
                            <h3 class="font-green">Forgot Password ?</h3>
                            <p> Enter your e-mail address below to reset your password. </p>
                            <div class="form-group">
                                <input class="form-control placeholder-no-fix form-group" type="text" autocomplete="off" placeholder="Email" name="email" /> </div>
                            <div class="form-actions">
                                <button type="button" id="back-btn" class="btn grey btn-default">Back</button>
                                <button type="submit" class="btn blue btn-success uppercase pull-right">Submit</button>
                            </div>
                        </form>
                        <!-- END FORGOT PASSWORD FORM -->
                    </div>
                    <div class="login-footer">
                        <div class="row bs-reset">
                            <div class="col-xs-5 bs-reset">
                                <ul class="login-social">
                                    <li>
                                        <a href="javascript:;">
                                            <i class="icon-social-facebook"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="javascript:;">
                                            <i class="icon-social-twitter"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="javascript:;">
                                            <i class="icon-social-dribbble"></i>
                                        </a>
                                    </li>
                                </ul>
                            </div>
                            <div class="col-xs-7 bs-reset">
                                <div class="login-copyright text-right">
                                    <p>Copyright &copy; AERSA 2016</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>