<link href="/application/global/plugins/datatables/datatables.min.css" rel="stylesheet" type="text/css" />
<link href="/application/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.css" rel="stylesheet" type="text/css" />
<div id="my_container">
    <h3 class="page-title">Ingresos</h3>
    <div class="page-bar">
        <ul class="page-breadcrumb">
            <li>
                <a href="/flujoefectivo/cuentasporpagar">Flujo de efectivo</a>
                 <i class="fa fa-angle-right"></i>
            </li>
            <li>
                <a href="/flujoefectivo/ingresos">Ingresos</a>
            </li>
        </ul>
    </div>
    <?php foreach ($messages->getSuccessMessages() as $message):?>
        <div class="alert alert-success alert-dismissable">
            <button class="close" aria-hidden="true" data-dismiss="alert" type="button"></button>
            <strong>Éxito!</strong>
            <?php echo $message?>
        </div>
    <?php endforeach;?>
    <div class="portlet box green" style="border-left-width: 0px; border-bottom-width: 0px; border-right-width: 0px;">
        <div class="portlet-body form">
            <div class="form-body">
                <table class="table table-striped table-bordered table-hover order-column" id="datatable" style="border-bottom-width: 0px;">
                    <thead>
                        <tr>
                            <th> Fecha </th>
                            <th> Total Alimentos </th>
                            <th> Total Bebidas </th>
                            <th> Total Miscelanea </th>
                            <th> Revisada </th>
                            <th> Acciones </th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php $entity = new Ingreso(); ?>
                        <?php foreach ($collection as $entity) : ?>
                            <?php
                            if($entity->getIngresoRevisada()) {
                                $class = 'info';
                                $revisada = 'Revisada';
                            } else {
                                $class = 'danger';
                                $revisada = 'No revisada';
                            }
                            ?>
                            <tr date="<?php echo $entity->getIngresoFecha('Y/m/d') ?>" id="<?php echo $entity->getIdingreso() ?>">
                                <td><?php echo $entity->getIngresoFecha('d/m/Y') ?></td>
                                <td><?php echo money_format('%+#1.6n',$entity->getingresoTotalalimento()) ?></td>
                                <td><?php echo money_format('%+#1.6n',$entity->getingresoTotalbebida()) ?></td>
                                <td><?php echo money_format('%+#1.6n',$entity->getingresoTotalmiscelanea()) ?></td>
                                <td><span class="label label-sm label-<?php echo $class?>"> <?php echo $revisada ?> </span></td>
                                <td>                                    
                                    <div class="btn-group">
                                        <button class="btn btn-xs green dropdown-toggle" type="button" data-toggle="dropdown" aria-expanded="false"> Acciones
                                            <i class="fa fa-angle-down"></i>
                                        </button>
                                        <ul class="dropdown-menu" role="menu">
                                            <li>
                                                <a href="/flujoefectivo/ingresos/editar/<?php echo $entity->getIdingreso()?>">
                                                    <i class="fa fa-list-ul"></i> Detalles </a>
                                            </li>
                                        </ul>
                                    </div>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<script src="/application/global/scripts/datatable.js" type="text/javascript"></script>
<script src="/application/global/plugins/datatables/datatables.min.js" type="text/javascript"></script>
<script src="/application/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.js" type="text/javascript"></script>
<script src="/application/custom/js/flujoefectivo/ingresos.js" type="text/javascript"></script>	
<script>
    
    var plugin = $('#my_container').ingresos();
    plugin.list();
</script>