<link href="/application/global/plugins/datatables/datatables.min.css" rel="stylesheet" type="text/css" />
<link href="/application/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.css" rel="stylesheet" type="text/css" />
<link rel="stylesheet" type="text/css" href="/application/custom/css/validaciones.css">
<h3 class="page-title"><?php echo $proveedor->getProveedorNombrecomercial(); ?></h3>
<div class="page-bar">
    <ul class="page-breadcrumb">
        <li>
            <a href="/flujoefectivo/saldoproveedores">Saldo proveedores</a>
            <i class="fa fa-angle-right"></i>
        </li>
        <li>
            <span><span><?php echo $abonoproveedor->getProveedor()->getProveedorNombrecomercial(); ?></span></span>
        </li>
    </ul>
</div>
<div id="my_container">
    <div class="page-bar">
        <ul class="page-breadcrumb">
            <li>
                <a href="/flujoefectivo/saldoproveedores">Saldo proveedores</a>
            </li>
        </ul>
    </div>
    <?php foreach ($messages->getSuccessMessages() as $message):?>
        <div class="alert alert-success alert-dismissable">
            <button class="close" aria-hidden="true" data-dismiss="alert" type="button"></button>
            <strong>Éxito!</strong>
            <?php echo $message?>
        </div>
    <?php endforeach;?>
    <div class="portlet box " style="border-left-width: 0px; border-bottom-width: 0px; border-right-width: 0px;">
        <div class="portlet-body form">
            <div class="form-body">
                <div class="row">
                    <div class="col-md-6">
                        <?php echo $this->formHidden($form->get('idabonoproveedor')); ?>
                        <?php echo $this->formHidden($form->get('idproveedor')); ?>
                        <?php echo $this->formLabel($form->get('proveedor_nombrecomercial')); ?>  
                        <?php echo $this->formText($form->get('proveedor_nombrecomercial')); ?>
                    </div>
                    <div class="col-md-6">
                        <?php echo $this->formLabel($form->get('abonoproveedor_balance')); ?>  
                        <?php echo $this->formText($form->get('abonoproveedor_balance')); ?>
                    </div>
                </div>
                <br><br>
                <div class="btn-set pull-right">
                    <a href="/flujoefectivo/saldoproveedores/movimientos/<?php echo $abonoproveedor->getIdproveedor();?>/abono"><button class="btn default" type="button" style="margin-bottom: 15px;">Nuevo abono</button></a>
                </div>
                <br><br>
                <table class="table table-striped table-bordered table-hover order-column" id="datatable"  style="border-bottom-width: 0px;">
                    <thead>
                        <tr>
                            <th class="text"> Fecha </th>
                            <th class="text"> Tipo </th>
                            <th class="text"> Cantidad </th>
                            <th class="text"> Cuenta </th>
                            <th class="text"> Medio </th>
                            <th class="text"> Referencia </th>
                            <th class="text"> Comprobante </th>
                            <th class="text"> Opciones </th>
                        </tr>
                    </thead>
                    <tbody class="text">
                        <?php $entity = new Abonoproveedordetalle();foreach ($abonoproveedordetalle as $entity) : 
                            $cobrado = ($entity->getAbonoproveedordetalleMediodepago() == 'cheque' && $entity->getAbonoproveedordetalleChequecirculacion()) ? "Cobrado":  "No cobrado";
                            $class = ($entity->getAbonoproveedordetalleMediodepago() == 'cheque' && $entity->getAbonoproveedordetalleChequecirculacion()) ? "info":  "danger";?>
                        <tr id="<?php echo $entity->getIdabonoproveedordetalle()?>">
                            <td><?php echo $entity->getAbonoproveedordetalleFechaabono('d/m/Y') ?></td>
                            <td><?php echo $entity->getAbonoproveedordetalleTipo() ?></td>
                            <td><?php echo $entity->getAbonoproveedordetalleCantidad() ?></td>
                            <td><?php if($entity->getIdcuentabancaria()!=null)echo $entity->getCuentabancaria()->getCuentabancariaBanco()." - ".$entity->getCuentabancaria()->getCuentabancariaNocuenta(); ?></td>
                            <td><?php echo $entity->getAbonoproveedordetalleMediodepago()." "; if($entity->getAbonoproveedordetalleMediodepago()=='cheque') {?><span class="label label-sm label-<?php echo $class?>"> <?php echo $cobrado ?> </span><?php  } ?></td>
                            <td><?php echo $entity->getAbonoproveedordetalleReferencia() ?></td>
                            <td><?php echo ($entity->getAbonoproveedordetalleComprobante()!=null) ? '<a target="_blank" href="'.$entity->getAbonoproveedordetalleComprobante().'"><i class="fa fa-file"></i></a>' : " ";?></td>
                                <td>
                                    <div class="btn-group">
                                        <button class="btn btn-xs green dropdown-toggle" type="button" data-toggle="dropdown" aria-expanded="false"> Acciones
                                            <i class="fa fa-angle-down"></i>
                                        </button>   
                                        <ul class="dropdown-menu" role="menu">
                                            <?php if ($entity->getAbonoproveedordetalleMediodepago() == 'cheque' && !$entity->getAbonoproveedordetalleChequecirculacion()) : ?>
                                            <li>
                                                <a class="editarmovimiento" href="javascript:;">
                                                    <i class="fa fa-pencil"></i> Editar </a>
                                            </li>
                                            <?php endif; ?>
                                            <li>
                                                <a href="javascript:;" class="delete_modal">
                                                    <i class="fa fa-trash"></i> Eliminar </a>
                                            </li>
                                        </ul>
                                    </div>
                                </td>
                            </tr>                            
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<script src="/application/global/scripts/datatable.js" type="text/javascript"></script>
<script src="/application/global/plugins/datatables/datatables.min.js" type="text/javascript"></script>
<script src="/application/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.js" type="text/javascript"></script>
<script src="http://cdn.datatables.net/plug-ins/1.10.13/sorting/date-eu.js" type="text/javascript"></script>
<script src="/application/custom/js/flujoefectivo/saldoproveedores.js" type="text/javascript"></script>	
<script>
    var $plugin = $('#my_container').saldoproveedores();
    $plugin.movimientos();
</script>