<link href="/application/global/plugins/datatables/datatables.min.css" rel="stylesheet" type="text/css" />
<link href="/application/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.css" rel="stylesheet" type="text/css" />
<div id="my_container">
    <h3 class="page-title">Reporte variación de los costos</h3>
    <div class="page-bar">
        <ul class="page-breadcrumb">
            <li>
                <a href="/reportes/variacioncostos">Reporte variación de los costos</a>
            </li>
        </ul>
    </div>

    <div class="portlet box green" style="border-left-width: 0px; border-bottom-width: 0px; border-right-width: 0px;">
        <div class="portlet-body form">
            <div class="form-body">
                <div class="row">
                    <div class="form-actions right">
                        <button class="btn blue" id="back" type="button" onClick="history.go(-1);return true;">
                            <i class="fa fa-refresh"></i>
                            Generar otro reporte
                        </button>
                    </div>
                    <div class="col-md-12">
                        <table class="table" id="reporte_table">
                            <?php
                            echo $reporte[0];
                            echo $reporte[1];
                            unset($reporte[0]);
                            unset($reporte[1]);
                            ?>
                            <thead>
                            <th>Productos</th>
                            <th>Unidad</th>
                            <th>Costo Old</th>
                            <th>Costo New</th>
                            <th>Var</th>
                            <th>PctVar</th>
                            </thead>
                            <tbody id="tbody">
                                <?php
                                foreach ($reporte as $tr):
                                    echo $tr;
                                endforeach;
                                ?>
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="form-actions right">
                    <button class="btn blue" id="back" type="button" onClick="history.go(-1);return true;">
                        <i class="fa fa-refresh"></i>
                        Generar otro reporte
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="/application/global/scripts/datatable.js" type="text/javascript"></script>
<script src="/application/global/plugins/datatables/datatables.min.js" type="text/javascript"></script>
<script src="/application/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.js" type="text/javascript"></script>
<script src="/application/custom/js/reportes/reportes.js" type="text/javascript"></script>	
<script>
                        var $plugin = $('#my_container').reportes();
                        $plugin.variacioncostos();
</script>