<link href="/application/global/plugins/datatables/datatables.min.css" rel="stylesheet" type="text/css" />
<link href="/application/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.css" rel="stylesheet" type="text/css" />

<div id="my_container">
    <h3 class="page-title">Semanas revisadas</h3>
    <div class="page-bar">
        <ul class="page-breadcrumb">
            <li>
                <a href="/catalogo/semanasrevisadas">Semanas revisadas</a>
            </li>
        </ul>
    </div>
    <?php foreach ($messages->getSuccessMessages() as $message):?>
        <div class="alert alert-success alert-dismissable">
            <button class="close" aria-hidden="true" data-dismiss="alert" type="button"></button>
            <strong>Éxito!</strong>
            <?php echo $message?>
        </div>
    <?php endforeach;?>
   <div class="portlet box green" style="border-left-width: 0px; border-bottom-width: 0px; border-right-width: 0px;">
        <div class="portlet-body form">
            <div class="form-body">
<!--                <div class="btn-set pull-right">
                   
                        <a class="btn default" href="/catalogo/semanasrevisadas/nuevo" style="margin-bottom: 15px;">
                           
                            Nueva semana revisada
                        </a>

                </div>-->
                <table class="table table-striped table-bordered table-hover order-column" id="datatable" style="border-bottom-width: 0px;">
                    <thead >
                        <tr>
                            <th> Sucursal </th>
                            <th> Año activo </th>
                            <th> Semana activo </th>
                            <th> Opciones </th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php $entity = new Sucursal();?>
                        <?php foreach ($collection as $entity) : ?>
                            <?php
                            


                            $week_array = \Shared\GeneralFunctions::getWeekArray($entity->getSucursalAnioactivo());


                            ?>
                            <tr>
                                <td><?php echo $entity->getSucursalNombre() ?></td>
                                <td><?php echo $entity->getSucursalAnioactivo() ?></td>
                                <td><?php echo $week_array[$entity->getSucursalMesactivo()] ?></td>
                                <td><a href="/catalogo/semanasrevisadas/ver/<?php echo $entity->getIdsucursal()?>"><span class="label label-sm label-info">Ver semanas revisadas</span></a></td>

                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<script src="/application/global/plugins/datatables/datatables.min.js" type="text/javascript"></script>
<script src="/application/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.js" type="text/javascript"></script>
<script src="/application/custom/js/catalogo/semanarevisada.js" type="text/javascript"></script>
<script>
    var myplugin = $('#my_container').semanarevisada();
    myplugin.list();
</script>

