<div id="my_container">
<h3 class="page-title">Semanas revisada</h3>
<div class="page-bar">
    <ul class="page-breadcrumb">
        <li>
            <a href="/catalogo/semanasrevisadas/">Semanas revisada</a>
            <i class="fa fa-angle-right"></i>
        </li>
        <li>
            <a href="/catalogo/semanasrevisadas/nuevo">Nuevo</a>
           
        </li>
    </ul>
</div>
<?php foreach ($messages->getErrorMessages() as $message):?>
    <div class="alert alert-danger alert-dismissable">
        <button class="close" aria-hidden="true" data-dismiss="alert" type="button"></button>
        <strong>Error!</strong>
        <?php echo $message?>
        
    </div>
<?php endforeach;?>
<?php
    $form->setAttribute('action', "/catalogo/semanasrevisadas/nuevo/".$idsucursal);
    echo $this->form()->openTag($form);
?>
<div class="portlet box green" style="border-left-width: 0px; border-bottom-width: 0px; border-right-width: 0px;">
    <div class="portlet-body form">
        <div class="form-body">
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <?php echo $this->formLabel($form->get('semanarevisada_anio')) ?>  
                        <?php echo $this->formText($form->get('semanarevisada_anio')) ?>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <?php echo $this->formLabel($form->get('semanarevisada_semana')) ?>  
                        <?php echo $this->formSelect($form->get('semanarevisada_semana')) ?>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <p>(*)Campos obligatorios</p>
                </div>
            </div>
        </div>
        <div class="form-actions right">
            <button class="btn blue" type="submit">
                <i class="fa fa-check"></i>
                Guardar
            </button>
        </div>
    </div>
</div>
<?php  echo $this->form()->closeTag(); ?>
</div>
<script src="/application/custom/js/catalogo/semanarevisada.js" type="text/javascript"></script>
<script>
    var myplugin = $('#my_container').semanarevisada();
    myplugin.new();
</script>