<link href="/application/global/plugins/datatables/datatables.min.css" rel="stylesheet" type="text/css" />
<link href="/application/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.css" rel="stylesheet" type="text/css" />

<div id="my_container">
    <h3 class="page-title"><?php echo $sucursal->getSucursalNombre()?> - Semanas revisadas</h3>
    <div class="page-bar">
        <ul class="page-breadcrumb">
            <li>
                <a href="/catalogo/semanasrevisadas">Semanas revisadas</a>
            </li>
        </ul>
    </div>
    <?php foreach ($messages->getSuccessMessages() as $message):?>
        <div class="alert alert-success alert-dismissable">
            <button class="close" aria-hidden="true" data-dismiss="alert" type="button"></button>
            <strong>Éxito!</strong>
            <?php echo $message?>
        </div>
    <?php endforeach;?>
   <div class="portlet box green" style="border-left-width: 0px; border-bottom-width: 0px; border-right-width: 0px;">
        <div class="portlet-body form">
            <div class="form-body">
                <div class="btn-set pull-right">
                   
                        <a class="btn default" href="/catalogo/semanasrevisadas/nuevo/<?php echo $sucursal->getIdsucursal()?>" style="margin-bottom: 15px;">
                           
                            Nueva semana revisada
                        </a>

                </div>
                <table class="table table-striped table-bordered table-hover order-column" id="datatable" style="border-bottom-width: 0px;">
                    <thead >
                        <tr  >
                            <th> Año revisada</th>
                            <th> Semana revisada</th>
                            <th> Estatus </th>
                            <th> Opciones </th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php $entity = new Semanarevisada()?>
                        <?php $collection_count = $collection->count(); $count = 0?>
                        <?php foreach ($collection as $entity) : ?>
                            <?php
                            $count ++;
                            $class = "danger";
                            $status = "No revisada";
                            if($entity->getSemanarevisadaEstatus()){
                                $class = "info";
                                $status = "Revisada";
                            }

                            
                            $week_array = \Shared\GeneralFunctions::getWeekArray($entity->getSemanarevisadaAnio());


                            ?>
                            <tr id="<?php echo $entity->getIdsemanarevisada() ?>">
                                <td><?php echo $entity->getSemanarevisadaAnio() ?></td>
                                <td><?php echo $week_array[$entity->getSemanarevisadaSemana()] ?></td>
                                <td><span class="label label-sm label-<?php echo $class?>"><?php echo $status?></span></a></td>
                                <td> 
                                     <?php if($collection_count == $count) :?>
                                    <div class="btn-group">
                                        <button class="btn btn-xs green dropdown-toggle" type="button" data-toggle="dropdown" aria-expanded="false"> Acciones
                                            <i class="fa fa-angle-down"></i>
                                        </button>
                                        <ul class="dropdown-menu" role="menu">
                                           
                                            <li>
                                                <a href="javascript:;" class="delete_modal">
                                                    <i class="fa fa-trash"></i> Eliminar </a>
                                            </li>
                                            
                                        </ul>
                                    </div>
                                    <?php else :?>
                                        N/D
                                    <?php endif; ?>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<script src="/application/global/plugins/datatables/datatables.min.js" type="text/javascript"></script>
<script src="/application/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.js" type="text/javascript"></script>
<script src="/application/custom/js/catalogo/semanarevisada.js" type="text/javascript"></script>
<script>
    var myplugin = $('#my_container').semanarevisada();
    myplugin.list();
</script>

