<style>
    input[type=file]{
        padding-top: 0px;
        padding-left: 0px;
    }
</style>
<link href="/application/global/plugins/datatables/datatables.min.css" rel="stylesheet" type="text/css" />
<link href="/application/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.css" rel="stylesheet" type="text/css" />
<link rel="stylesheet" type="text/css" href="/application/custom/css/validaciones.css">
<h3 class="page-title"><?php echo $cuentaporcobrar->getCuentaporcobrarCliente() ?></h3>

<div id="my_container">
    <div class="page-bar">
        <ul class="page-breadcrumb">
            <li>
                <a href="/flujoefectivo/cuentaporcobrar">Cuenta por cobrar </a>
                <i class="fa fa-angle-right"></i>
            </li>
            <li>
                <a href="/flujoefectivo/cuentaporcobrar/movimientos/<?php echo $cuentaporcobrar->getIdcuentaporcobrar(); ?>"><?php echo $cuentaporcobrar->getCuentaporcobrarCliente() ?> </a>
            </li>
        </ul>
    </div>
    <?php foreach ($messages->getSuccessMessages() as $message): ?>
        <div class="alert alert-success alert-dismissable">
            <button class="close" aria-hidden="true" data-dismiss="alert" type="button"></button>
            <strong>Éxito!</strong>
            <?php echo $message ?>
        </div>
    <?php endforeach; ?>
    <div class="portlet box " style="border-left-width: 0px; border-bottom-width: 0px; border-right-width: 0px;">
        <div class="portlet-body form">
            <div class="form-body">
                <div class="row">
                    <?php
                    $form->setAttribute('action', '/flujoefectivo/cuentaporcobrar/movimientos/'.$cuentaporcobrar->getIdcuentaporcobrar());
                    $form->setAttribute('method','post');
                    $form->setAttribute('enctype','multipart/form-data');
                    echo $this->form()->openTag($form);
                    ?>
                    <div class="col-md-6">
                        <?php echo $this->formHidden($form->get('idcuentaporcobrar'));?>
                        <?php echo $this->formLabel($form->get('cuentaporcobrar_fecha')); ?>  
                        <?php echo $this->formText($form->get('cuentaporcobrar_fecha')); ?>
                    </div>
                    <div class="col-md-6">
                        <?php echo $this->formLabel($form->get('cuentaporcobrar_cliente')); ?>  
                        <?php echo $this->formText($form->get('cuentaporcobrar_cliente')); ?>
                    </div>
                    <div class="col-md-6">
                        <?php echo $this->formLabel($form->get('cuentaporcobrar_cantidad')); ?>  
                        <?php echo $this->formText($form->get('cuentaporcobrar_cantidad')); ?>
                    </div>
                    <div class="col-md-6">
                        <?php echo $this->formLabel($form->get('cuentaporcobrar_abonado')); ?>  
                        <?php echo $this->formText($form->get('cuentaporcobrar_abonado')); ?>
                    </div>
                    <div class="col-md-6">
                        <?php echo $this->formLabel($form->get('cuentaporcobrar_referencia')); ?>  
                        <?php echo $this->formText($form->get('cuentaporcobrar_referencia')); ?>
                    </div>
                    <?php if($cuentaporcobrar->getCuentaporcobrarComprobante()!=null):?>
                    <div class="col-md-6">
                        <?php echo $this->formLabel($form->get('cuentaporcobrar_comprobante')); ?>
                        <br>
                        <div class="col-md-1">
                        <?php echo '<a target="_blank" href="'.$cuentaporcobrar->getCuentaporcobrarComprobante().'"><i class="fa fa-file"></i></a>'; ?>
                        </div>
                        <div class="col-md-11">
                        <?php echo $this->formFile($form->get('cuentaporcobrar_comprobante'));?>
                        </div>
                    </div>
                    <?php else: ?>
                    <div class="col-md-6">
                        <?php echo $this->formLabel($form->get('cuentaporcobrar_comprobante')); ?>
                        <?php echo $this->formFile($form->get('cuentaporcobrar_comprobante')); ?>
                    </div>
                    <?php endif; ?>
                    <br>
                    <div class="col-md-12">
                        <p>(*)Campos obligatorios</p>
                    </div>    
                    </div>
                    
                    <div class="row">
                    
                    
                    <div class="form-actions right">
                        <button class="btn blue" id="plantilla_save" type="submit">
                            <i class="fa fa-check"></i>
                            Guardar
                        </button>
                    </div>
                        </div>
                    <?php
                    echo $this->form()->closeTag($form);
                    ?>
                    
                
                <br><br>
                <?php if(!(bool)$cuentaporcobrar->getCuentaporcobrarEstatuspago()):?>
                <div class="btn-set pull-right">
                    <a href="/flujoefectivo/cuentaporcobrar/movimientos/<?php echo $cuentaporcobrar->getIdcuentaporcobrar(); ?>/pago"><button class="btn default" type="button" style="margin-bottom: 15px;">Nuevo pago</button></a>
                </div>
                <?php endif;?>
                <br><br>
                <table class="table table-striped table-bordered table-hover order-column" id="datatable"  style="border-bottom-width: 0px;">
                    <thead>
                        <tr>
                            <th class="text"> Fecha </th>
                            <th class="text"> Pago </th>
                            <th class="text"> Cuenta </th>
                            <th class="text"> Medio </th>
                            <th class="text"> Referencia </th>
                            <th class="text"> Comprobante </th>
                            <th class="text"> Opciones </th>
                        </tr>
                    </thead>
                    <tbody class="text">
                        <?php $entity = new Flujoefectivo();
                        foreach ($flujoefectivo as $entity) :
                            $cobrado = ($entity->getFlujoefectivoPago() == 'cuenta' && $entity->getFlujoefectivoMediodepago() == 'cheque' && $entity->getFlujoefectivoChequecirculacion()) ? "Cobrado":  "No cobrado";
                            $class = ($entity->getFlujoefectivoPago() == 'cuenta' && $entity->getFlujoefectivoMediodepago() == 'cheque' && $entity->getFlujoefectivoChequecirculacion()) ? "info":  "danger";
                            ?>
                            <tr id="<?php echo $entity->getIdflujoefectivo() ?>">
                                <td><?php echo $entity->getFlujoefectivoFecha('d/m/Y') ?></td>
                                <td><?php echo $entity->getFlujoefectivoCantidad() ?></td>
                                <td><?php echo $entity->getCuentabancaria()->getCuentabancariaBanco() . " - " . $entity->getCuentabancaria()->getCuentabancariaNocuenta() ?></td>
                                <td><?php echo $entity->getFlujoefectivoMediodepago()." "; if($entity->getFlujoefectivoMediodepago()=='cheque') {?><span class="label label-sm label-<?php echo $class?>"> <?php echo $cobrado ?> </span><?php  } ?></td>
                                <td><?php echo $entity->getFlujoefectivoReferencia() ?></td>
                                <td><?php echo ($entity->getFlujoefectivoComprobante()!=null) ? '<a target="_blank" href="'.$entity->getFlujoefectivoComprobante().'"><i class="fa fa-file"></i></a>' : " ";?></td>
                                <td>
                                    <div class="btn-group">
                                        <button class="btn btn-xs green dropdown-toggle" type="button" data-toggle="dropdown" aria-expanded="false"> Acciones
                                            <i class="fa fa-angle-down"></i>
                                        </button>   
                                        <ul class="dropdown-menu" role="menu">
    <?php if ($entity->getFlujoefectivoPago() == 'cuenta' && $entity->getFlujoefectivoMediodepago() == 'cheque' && !$entity->getFlujoefectivoChequecirculacion()) : ?>
                                            <li>
                                                <a class="editarmovimiento" href="javascript:;">
                                                <i class="fa fa-pencil"></i> Editar </a>
                                            </li>
    <?php endif; ?> 
                                            <li>
                                                <a href="javascript:;" class="delete_modal">
                                                <i class="fa fa-trash"></i> Eliminar </a>
                                            </li>
                                        </ul>
                                    </div>
                                </td>
                            </tr>                            
<?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<script src="/application/global/scripts/datatable.js" type="text/javascript"></script>
<script src="/application/global/plugins/datatables/datatables.min.js" type="text/javascript"></script>
<script src="/application/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.js" type="text/javascript"></script>
<script src="http://cdn.datatables.net/plug-ins/1.10.13/sorting/date-eu.js" type="text/javascript"></script>
<script src="/application/custom/js/flujoefectivo/cuentaporcobrar.js" type="text/javascript"></script>	
<script>
    var $plugin = $('#my_container').cuentaporcobrar();
    $plugin.movimientos();
</script>