<style>
    input[type=file]{
        padding-top: 0px;
        padding-left: 0px;
    }
</style>
<link rel="stylesheet" type="text/css" href="/application/custom/css/validaciones.css">
<div id="form_container">
    <h3 class="page-title">Registro cuenta por cobrar </h3>
    <div class="page-bar">
        <ul class="page-breadcrumb">
            <li>
                <a href="/flujoefectivo/cuentaporcobrar">Cuenta por cobrar</a>
                <i class="fa fa-angle-right"></i>
            </li>
            <li>
                <span>Registro</span>
            </li>
        </ul>
    </div>
    <?php foreach ($messages->getSuccessMessages() as $message): ?>
        <div class="alert alert-success alert-dismissable">
            <button class="close" aria-hidden="true" data-dismiss="alert" type="button"></button>
            <strong>Exito!</strong>
            <?php echo $message ?>
        </div>
    <?php endforeach; ?>

    <?php foreach ($messages->getErrorMessages() as $message): ?>
        <div class="alert alert-danger alert-dismissable">
            <button class="close" aria-hidden="true" data-dismiss="alert" type="button"></button>
            <strong>Error!</strong>
            <?php echo $message ?>
        </div>
    <?php endforeach; ?>
    <?php
    $form->setAttribute('action', '/flujoefectivo/cuentaporcobrar/nuevo');
    $form->setAttribute('enctype','multipart/form-data');
    echo $this->form()->openTag($form);
    ?>
    <div class="portlet box green" style="border-left-width: 0px; border-bottom-width: 0px; border-right-width: 0px;">
        <div class="portlet-body form">
            <div class="form-body">
                <h3 class="form-section">Información general</h3>
                <div class="row">
                    <div class="col-md-6">
                    <?php echo $this->formLabel($form->get('cuentaporcobrar_fecha')); ?>  
                    <?php echo  $this->formText($form->get('cuentaporcobrar_fecha'));?>
                    </div>
                    <div class="col-md-6">
                    <?php echo $this->formLabel($form->get('cuentaporcobrar_cliente')); ?>  
                    <?php echo  $this->formText($form->get('cuentaporcobrar_cliente'));?>
                    </div>
                    <div class="col-md-6">
                    <?php echo $this->formLabel($form->get('cuentaporcobrar_cantidad')); ?>  
                    <?php echo  $this->formText($form->get('cuentaporcobrar_cantidad'));?>
                    </div>
                    <div class="col-md-6">
                    <?php echo $this->formLabel($form->get('cuentaporcobrar_referencia')); ?>  
                    <?php echo  $this->formText($form->get('cuentaporcobrar_referencia'));?>
                    </div>
                    <div class="col-md-6">
                    <?php echo $this->formLabel($form->get('cuentaporcobrar_comprobante')); ?>  
                    <?php echo  $this->formFile($form->get('cuentaporcobrar_comprobante'));?>
                    </div>
                </div>
                <br>
                <div class="row">
                    <div class="col-md-12">
                        <p>(*)Campos obligatorios</p>
                    </div>
                </div>
            </div>
            <div class="form-actions right">
                <button class="btn blue" id="plantilla_save" type="submit">
                    <i class="fa fa-check"></i>
                    Guardar
                </button>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript" src="/application/custom/js/flujoefectivo/cuentaporcobrar.js"></script>
<script>
    var $form = $('#form_container').cuentaporcobrar();
    $form.new();
</script>