<h3 class="page-title"><?php echo $form->get('empresa_nombrecomercial')->getValue()?></h3>
<div class="page-bar">
    <ul class="page-breadcrumb">
        <li>
            <a href="/catalogo/empresa">Empresa </a>
            <i class="fa fa-angle-right"></i>
        </li>
        <li>
            <span><?php echo $form->get('empresa_nombrecomercial')->getValue()?></span>
        </li>
    </ul>
</div>
<?php foreach ($messages->getSuccessMessages() as $message):?>
    <div class="alert alert-success alert-dismissable">
        <button class="close" aria-hidden="true" data-dismiss="alert" type="button"></button>
        <strong>Éxito!</strong>
        <?php echo $message?>
    </div>
<?php endforeach;?>

<?php foreach ($messages->getErrorMessages() as $message):?>
    <div class="alert alert-danger alert-dismissable">
        <button class="close" aria-hidden="true" data-dismiss="alert" type="button"></button>
        <strong>Error!</strong>
        <?php echo $message?>
        
    </div>
<?php endforeach;?>
<?php
    $form->setAttribute('action', '/catalogo/empresa/editar/'.$form->get('idempresa')->getValue());
    echo $this->form()->openTag($form);
?>
<div class="portlet box green" style="border-left-width: 0px; border-bottom-width: 0px; border-right-width: 0px;">
    <div class="portlet-body form">
        <div class="form-body">
            <h3 class="form-section">Empresa <?php echo $form->get('empresa_nombrecomercial')->getValue()?></h3>
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <?php echo $this->formLabel($form->get('empresa_nombrecomercial')) ?>  
                        <?php echo $this->formText($form->get('empresa_nombrecomercial')) ?>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <?php echo $this->formLabel($form->get('empresa_razonsocial')) ?>  
                        <?php echo $this->formText($form->get('empresa_razonsocial')) ?>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <?php echo $this->formLabel($form->get('empresa_estatus')) ?>  
                        <?php echo $this->formSelect($form->get('empresa_estatus')) ?>
                    </div>
                </div>
                <div class="col-md-6" style=" padding-top: 30px;">
                    <div >
                        <?php echo $this->formLabel($form->get('empresa_administracion')) ?>  
                        <?php echo $this->formCheckbox($form->get('empresa_administracion')) ?>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <p>(*)Campos obligatorios</p>
                </div>
            </div> 
        </div>
        <div class="form-actions right" style="background-color: white">
            <button class="btn blue" type="submit">
                <i class="fa fa-check"></i>
                Guardar
            </button>
        </div>
        
    </div>
</div>
<div class="portlet box green" style="border-left-width: 0px; border-bottom-width: 0px; border-right-width: 0px;">
    <div class="portlet-body form">
        <div class="form-body">
            <div class="btn-set pull-right">
                <a href="/catalogo/usuario/administrador/<?php echo $form->get('idempresa')->getValue() ?>" ><button class="btn default" type="button" style="margin-bottom: 15px;">Nuevo administrador</button></a>
            </div>
            <h3 class="form-section ">Administradores de la empresa </h3>
            <table class="table table-striped table-bordered table-hover order-column" id="datatable" style="border-bottom-width: 0px;">
                <thead >
                    <tr>
                        <th class="text-center"> Nombre </th>
                        <th class="text-center"> Estatus </th>
                        <th class="text-center"> Usuario </th>
                        <th class="text-center"> Acciones </th>
                    </tr>
                </thead>
                <tbody class="text-center">
                    <?php foreach ($administradores as $entity) : ?>
                        <?php

                        if ($entity->getUsuarioEstatus() == 1) 
                        {
                            $estatus = 'Activo';
                            $class = 'info';
                        } 
                        else 
                        {
                            $estatus = 'Inactivo';
                            $class = 'danger';
                        }

                        ?>
                        <div id="divEmp" style="display: none"><?php echo $form->get('idempresa')->getValue() ?></div>
                    
                        <tr id="<?php echo $entity->getIdusuario() ?>">
                            <td><?php echo $entity->getUsuarionombre() ?></td>
                            <td><span class="label label-sm label-<?php echo $class?>"> <?php echo $estatus ?> </span></td>
                            <td><?php echo $entity->getUsuariousername() ?></td>
                            
                            <td>
                                <div class="btn-group">
                                    <button class="btn btn-xs green dropdown-toggle" type="button" data-toggle="dropdown" aria-expanded="false"> Acciones
                                        <i class="fa fa-angle-down"></i>
                                    </button>
                                    <ul class="dropdown-menu" role="menu">
                                        <li>
                                            <a href="/catalogo/usuario/editaradministrador/<?php echo $entity->getIdusuario()?>/<?php echo $form->get('idempresa')->getValue() ?>">
                                                <i class="fa fa-pencil"></i> Editar </a>
                                        </li>
                                        <?php if (count($administradores) > 1 ): ?>
                                            <li>
                                                <a href="javascript:;" class="delete_admin">
                                                    <i class="fa fa-trash"></i> Eliminar </a>
                                            </li>
                                        <?php endif ?>
                                    </ul>
                                </div>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                        
                        
                </tbody>
            </table>
        </div>        
    </div>
</div>

<div class="portlet box green" style="border-left-width: 0px; border-bottom-width: 0px; border-right-width: 0px;">
    <div class="portlet-body form">
        <div class="form-body">
            <div class="btn-set pull-right">
                <a href="/catalogo/empresa/sucursal/nuevo/<?php echo $form->get('idempresa')->getValue() ?>"><button class="btn default" type="button" style="margin-bottom: 15px;">Nueva sucursal</button></a>
            </div>
            <h3 class="form-section ">Sucursales </h3>
            <table class="table table-striped table-bordered table-hover order-column" id="datatable" style="border-bottom-width: 0px;">
                <thead >
                    <tr>
                        <th class="text-center"> Nombre </th>
                        <th class="text-center"> Estatus </th>
                        <th class="text-center"> Productos </th>
                        <th class="text-center"> Recetas </th>
                        <th class="text-center"> Acciones </th>
                    </tr>
                </thead>
                <tbody class="text-center">
                    <?php foreach ($sucursales as $entity) : ?>
                        <?php

                        if ($entity->getSucursalestatus() == 1) 
                        {
                            $estatus = 'Activo';
                            $class = 'info';
                        } 
                        else 
                        {
                            $estatus = 'Inactivo';
                            $class = 'danger';
                        }
                        if ($entity->getSucursalHabilitarproductos() == 1) 
                        {
                            $prod = 'Activo';
                            $classProd = 'info';
                        } 
                        else 
                        {
                            $prod = 'Inactivo';
                            $classProd = 'danger';
                        }
                        if ($entity->getSucursalHabilitarrecetas() == 1) 
                        {
                            $recetas = 'Activo';
                            $classRec = 'info';
                        } 
                        else 
                        {
                            $recetas = 'Inactivo';
                            $classRec = 'danger';
                        }

                        ?>
                        <tr id="<?php echo $entity->getIdsucursal() ?>">
                            <td><?php echo $entity->getSucursalnombre() ?></td>
                            <td><span class="label label-sm label-<?php echo $class?>"> <?php echo $estatus ?> </span></td>
                            <td><span class="label label-sm label-<?php echo $classProd?>"> <?php echo $prod ?></span></td>
                            <td><span class="label label-sm label-<?php echo $classRec?>"> <?php echo $recetas ?></span></td>

                            <td>
                                
                                <div class="btn-group">
                                    <button class="btn btn-xs green dropdown-toggle" type="button" data-toggle="dropdown" aria-expanded="false"> Acciones
                                        <i class="fa fa-angle-down"></i>
                                    </button>
                                    <ul class="dropdown-menu" role="menu">
                                        <li>
                                            <a href="/catalogo/empresa/sucursal/editar/<?php echo $entity->getIdSucursal()?>/<?php echo $form->get('idempresa')->getValue() ?>">
                                                <i class="fa fa-pencil"></i> Editar </a>
                                        </li>
                                        <!--
                                        <li>
                                            <a href="javascript:;" class="delete_suc">
                                                <i class="fa fa-trash"></i> Eliminar </a>
                                        </li>
                                        -->
                                    </ul>
                                </div>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                        
                        <?php if(count($sucursales) == 0) : ?>
                        <tr>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                                
                        </tr>
                        <?php endif ?>
                        
                </tbody>
            </table>
        </div>        
    </div>
</div>


<?php  echo $this->form()->closeTag(); ?>

<script>
    $(document).ready(function(){

        $('.delete_admin').click(function(){

          var id = $(this).closest('tr').attr('id');
          var emp = $("#divEmp").text();
          var tmpl = [
            // tabindex is required for focus
            ' <div class="modal fade draggable-modal" id="draggable" tabindex="-1" role="basic" aria-hidden="true">',
              '<div class="modal-header">',
                '<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>',
                '<h4 class="modal-title">ADVERTENCIA</h4>', 
              '</div>',
              '<form method="post" action="/catalogo/usuario/eliminaradministrador/'+id+'/'+emp+'">',
                '<div class="modal-body">',
                  '<p>¿Estas seguro que deseas eliminar el registro seleccionado?</p>',
                '</div>',
                '<div class="modal-footer">',
                  '<a href="#" data-dismiss="modal" class="btn btn-default">Cancelar</a>',
                  '<button class="btn btn-danger" type="submit">Eliminar</button>',
                '</div>',
              '</form>',
            '</div>'
          ].join('');
          $(tmpl).modal();
        });
        
        
    }); 
</script>