<link href="/application/global/plugins/datatables/datatables.min.css" rel="stylesheet" type="text/css" />
<link href="/application/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.css" rel="stylesheet" type="text/css" />
<div id="my_container">
    <h3 class="page-title">Empresas</h3>
    <div class="page-bar">
        <ul class="page-breadcrumb">
            <li>
                <a href="/catalogo/empresa">Empresas</a>
            </li>
        </ul>
    </div>
    <?php foreach ($messages->getSuccessMessages() as $message):?>
        <div class="alert alert-success alert-dismissable">
            <button class="close" aria-hidden="true" data-dismiss="alert" type="button"></button>
            <strong>Éxito!</strong>
            <?php echo $message?>
        </div>
    <?php endforeach;?>
    <div class="portlet box green" style="border-left-width: 0px; border-bottom-width: 0px; border-right-width: 0px;">
        <div class="portlet-body form">
            <div class="form-body">
                <div class="btn-set pull-right">
                    <a href="/catalogo/empresa/nuevo"><button class="btn default" type="button" style="margin-bottom: 15px;">Nueva empresa</button></a>
                </div>
                <table class="table table-striped table-bordered table-hover order-column" id="datatable" style="border-bottom-width: 0px;">
                    <thead >
                        <tr>
                            <th class="text-center"> Nombre comercial </th>
                            <th class="text-center"> Razón social </th>
                            <th class="text-center"> Estatus </th>
                            <th class="text-center"> Administrable </th>
                            <th class="text-center"> Acciones </th>
                        </tr>
                    </thead>
                    <tbody class="text-center">
                        <?php foreach ($collection as $entity) : ?>
                            <?php
                            
                            if ($entity->getEmpresaestatus() == 1) 
                            {
                                $estatus = 'Activo';
                                $class = 'info';
                            } 
                            else 
                            {
                                $estatus = 'Inactivo';
                                $class = 'danger';
                            }
                            if ($entity->getEmpresaadministracion() == 1) 
                            {
                                $administracion = 'Administrable';
                                $classAdm = 'info';
                            } 
                            else 
                            {
                                $administracion = 'No administrable';
                                $classAdm = 'danger';
                            }
                             
                            ?>
                            <tr id="<?php echo $entity->getIdempresa() ?>">
                                <td><?php echo $entity->getEmpresaNombrecomercial() ?></td>
                                <td><?php echo $entity->getEmpresarazonsocial() ?></td>
                                <td><span class="label label-sm label-<?php echo $class?>"> <?php echo $estatus ?> </span></td>
                                <td><span class="label label-sm label-<?php echo $classAdm ?>"> <?php echo $administracion ?> </span></td>
                                
                                <td class="text-left">                                    
                                    <div class="btn-group">
                                        <button class="btn btn-xs green dropdown-toggle" type="button" data-toggle="dropdown" aria-expanded="false"> Acciones
                                            <i class="fa fa-angle-down"></i>
                                        </button>
                                        <ul class="dropdown-menu" role="menu">
                                            <li>
                                                <a href="/catalogo/empresa/editar/<?php echo $entity->getIdempresa()?>">
                                                    <i class="fa fa-pencil"></i> Editar </a>
                                            </li>
                                            <!--
                                            <li>
                                                <a href="javascript:;" class="delete_modal">
                                                    <i class="fa fa-trash"></i> Eliminar </a>
                                            </li>
                                            -->
                                        </ul>
                                    </div>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<script src="/application/global/scripts/datatable.js" type="text/javascript"></script>
<script src="/application/global/plugins/datatables/datatables.min.js" type="text/javascript"></script>
<script src="/application/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.js" type="text/javascript"></script>
<script src="/application/custom/js/catalogo/usuario.js" type="text/javascript"></script>	
<script>
    
    var plugin = $('#my_container').usuario();
    
    

</script>