<link href="/application/global/plugins/datatables/datatables.min.css" rel="stylesheet" type="text/css" />
<link href="/application/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.css" rel="stylesheet" type="text/css" />
<div id="my_container">
    <h3 class="page-title">Recetas técnicas</h3>
    <div class="page-bar">
        <ul class="page-breadcrumb">
            <li>
                <a href="/reportes/recetas">Recetas técnicas</a>
            </li>
        </ul>
    </div>
    <div class="portlet box green" style="border-left-width: 0px; border-bottom-width: 0px; border-right-width: 0px;">
        <div class="portlet-body form">
            <div class="form-body">
                <br>
                <h5>Selecciona un tipo de reporte</h5>
                <br>
                <div class="row">
                    <div class="form-actions">
                    <div class="col-md-6">
                        <a href="recetas/detalle" class="btn btn-info" role="button"><i class="fa fa-th"></i>Detalle</a>
                    </div>
                    <div class="col-md-6">
                        <a href="recetas/resumen" class="btn blue" role="button"><i class="fa fa-th-large"></i>Resumen</a>
                    </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="/application/global/scripts/datatable.js" type="text/javascript"></script>
<script src="/application/global/plugins/datatables/datatables.min.js" type="text/javascript"></script>
<script src="/application/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.js" type="text/javascript"></script>