<link href="/application/global/plugins/datatables/datatables.min.css" rel="stylesheet" type="text/css" />
<link href="/application/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.css" rel="stylesheet" type="text/css" />
<div id="my_container">
    <h3 class="page-title">Receta técnica resumen</h3>
    <div class="page-bar">
        <ul class="page-breadcrumb">
            <li>
                <a href="/reportes/recetas/resumen">Receta técnica resumen</a>
            </li>
        </ul>
    </div>

    <div class="portlet box green" style="border-left-width: 0px; border-bottom-width: 0px; border-right-width: 0px;">
        <div class="portlet-body form">
            <div class="form-body">
                <br>
                <center><h3>Empresa: <?php echo $empresa?></h3></center>
                <center><h3>Sucursal: <?php echo $sucursal?></h3></center>
                <center><h3>Fecha: <?php echo $fecha?></h3></center>
                <br>
                <div class="row">
                </div>
                <br>
                <div class="form-actions">
                    <form action="/reportes/recetas/resumen" method="post">
                        <div class="left col-md-2">
                            <button class="btn blue" id="generar_pdf" name="generar_pdf" type="submit">
                                <i class="fa fa-file-pdf-o"></i>
                                PDF
                            </button>
                        </div>
                        <div class="left col-md-2">
                            <button class="btn blue" id="generar_excel" name="generar_excel" type="submit">
                                <i class="fa fa-file-excel-o"></i>
                                Excel
                            </button>
                        </div>
                    </form>
                    <div class="right col-md-8" align="right">
                        <a href="detalle" class="btn btn-info" role="button"><i class="fa fa-th"></i>Detalle</a>
                    </div>
                        
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <table class="table" id="reporte_table">
                            <thead>
                            </thead>
                            <tbody id="tbody">
                                <?php foreach ($reporte as $line) {
                                    echo $line;
                                }
?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="/application/global/scripts/datatable.js" type="text/javascript"></script>
<script src="/application/global/plugins/datatables/datatables.min.js" type="text/javascript"></script>
<script src="/application/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.js" type="text/javascript"></script>
<script src="/application/custom/js/reportes/receta.js" type="text/javascript"></script>	
<script>
    var $plugin = $('#my_container').receta();
    $plugin.resumen();
</script>