<link href="/application/global/plugins/datatables/datatables.min.css" rel="stylesheet" type="text/css" />
<link href="/application/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.css" rel="stylesheet" type="text/css" />

<link href="https://cdn.datatables.net/select/1.1.2/css/select.dataTables.min.css" rel="stylesheet" type="text/css" />
<style>
    .dt-buttons { float: left !important;}
</style>
<div id="my_container">
    <h3 class="page-title">Productos</h3>
    <div class="page-bar">
        <ul class="page-breadcrumb">
            <li>
                <a href="/catalogo/producto">Listado de productos</a>
            </li>
        </ul>
    </div>
    <?php foreach ($messages->getSuccessMessages() as $message):?>
        <div class="alert alert-success alert-dismissable">
            <button class="close" aria-hidden="true" data-dismiss="alert" type="button"></button>
            <strong>Éxito!</strong>
            <?php echo $message?>
        </div>
    <?php endforeach;?>
    <div class="portlet box green" style="border-left-width: 0px; border-bottom-width: 0px; border-right-width: 0px;">
        <div class="portlet-body form">
            <div class="form-body">
                
                
                <div style="margin-top: 50px"></div>
                
                
              
                <table class="table table-striped table-bordered table-hover order-column row" id="datatable" style="border-bottom-width: 0px;">
                    <thead >
                        <tr>
                            <th></th>
                            <th> Producto </th>
                            <th> Categoria </th>
                            <th> Estatus </th>
                        </tr>
                    </thead>
                    <tbody>
                        
                        
                        <?php foreach ($productos as $entity) : ?>

                        <?php $categoria    = \CategoriaQuery::create()->findPk($entity->getIdCategoria()) ?>
                        <?php $subcategoria = \CategoriaQuery::create()->findPk($entity->getIdsubcategoria()) ?>
                            
                           
                            <tr id="<?php echo $entity->getIdproducto() ?>">
                                <td></td>
                                
                                <td><?php echo $entity->getProductoNombre() ?></td>
                                <td><span class="label label-sm label-success"> <?php echo $entity->getCategoriaRelatedByIdcategoria()->getCategoriaNombre() ?> </span></td>
                                <?php if($subcategoria != NULL): ?>
                                <td><span class="label label-sm label-success"><?php echo $subcategoria->getCategoriaNombre() ?></span></td>
                                <?php else:?>
                                    <td><span class="label label-sm label-danger"> N/A </span></td>
                                <?php endif ?>
                                    
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<script src="/application/global/scripts/datatable.js" type="text/javascript"></script>
<script src="/application/global/plugins/datatables/datatables.min.js" type="text/javascript"></script>
<script src="/application/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.js" type="text/javascript"></script>
<script src="/application/custom/js/catalogo/usuario.js" type="text/javascript"></script>	

<script src="/application/global/plugins/datatables/dataTables.select.min.js" type="text/javascript"></script>
<script src="/application/global/plugins/datatables/dataTables.buttons.min.js" type="text/javascript"></script>

<script>    
    $.ajax({
        url:'/application/json/datatable/lang_es.json',
        dataType:'json',
        success:function(data){
           $('#datatable').dataTable({
               "language":data,
               "order":[],
               dom: 'Bfrtip',
                buttons: [
                    'selectAll',
                    'selectNone',
                ],
                columnDefs: [ {
                    orderable: false,
                    className: 'select-checkbox',
                    targets:   0
                } ],
                select: {
                    style: 'multi'
                }
           });
        },
    });
</script>