<link href="/application/global/plugins/datatables/datatables.min.css" rel="stylesheet" type="text/css" />
<link href="/application/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.css" rel="stylesheet" type="text/css" />


<div id="my_container">
    <h3 class="page-title">Productos</h3>
    <div class="page-bar">
        <ul class="page-breadcrumb">
            <li>
                <a href="/catalogo/producto">Listado de productos</a>
            </li>
        </ul>
    </div>
    <?php foreach ($messages->getSuccessMessages() as $message):?>
        <div class="alert alert-success alert-dismissable">
            <button class="close" aria-hidden="true" data-dismiss="alert" type="button"></button>
            <strong>Éxito!</strong>
            <?php echo $message?>
        </div>
    <?php endforeach;?>
    <div class="portlet box green" style="border-left-width: 0px; border-bottom-width: 0px; border-right-width: 0px;">
        <div class="portlet-body form">
            <div class="form-body">
                
                
                <form action="/catalogo/altaproductos" method="post">
                    
                    <div class="row  col-md-2">
                        <select class="form-control " required name="status">
                            <option selected value> Sin especificar </option>
                            <option value="1"> Activo </option>
                            <option value="0"> Inactivo </option>
                        </select>
                    </div>
                    <div class="col-md-2">
                        <button id="btnSave" class="btn blue col-md-6 col-md-offset-3 ">Guardar</button>
                    </div>
              
                    <table class="table table-striped table-bordered table-hover order-column row col-md-12" id="datatable" style="border-bottom-width: 0px; ">
                        <thead >
                            <tr>
                                <th><input type="checkbox" id="selectall" class="pull-left"> </th>
                                <th> Producto </th>
                                <th> Categoria </th>
                                <th> Estatus </th>
                            </tr>
                        </thead>
                    <tbody>
                        
                        <?php foreach ($productos as $entity) : ?>
                        
                        
                        <?php $categoria    = \CategoriaQuery::create()->findPk($entity->getIdCategoria()) ?>
                        <?php $subcategoria = \CategoriaQuery::create()->findPk($entity->getIdsubcategoria()) ?>
                            
                            <?php
                                 if ($entity->getProductobaja()) 
                                 {
                                     $estatus = "Activo";
                                     $class ="primary";
                                 }
                                 else
                                 {
                                     $estatus = "Inactivo";
                                     $class ="danger";
                                 }
                            ?>
                            <tr id="tabla">
                            <br>
                            <td><input type="checkbox" class="text-center" name="<?php echo $entity->getIdproducto() ?>" value="<?php echo $entity->getIdproducto() ?>" ></td>
                                <td><?php echo $entity->getProductoNombre() ?></td>
                                <td><span class="label label-sm label-success"> <?php echo $entity->getCategoriaRelatedByIdcategoria()->getCategoriaNombre() ?> </span></td>
                                <?php if($subcategoria != NULL): ?>
                                <td><span class="label label-sm label-<?php echo $class ?>  "><?php echo $estatus?></span></td>
                                <?php else:?>
                                    <td><span class="label label-sm label-danger"> N/A </span></td>
                                <?php endif ?>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
                    
                </form>
            </div>
        </div>
    </div>
</div>
<script src="/application/global/scripts/datatable.js" type="text/javascript"></script>
<script src="/application/global/plugins/datatables/datatables.min.js" type="text/javascript"></script>
<script src="/application/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.js" type="text/javascript"></script>
<script src="/application/custom/js/catalogo/usuario.js" type="text/javascript"></script>	

<script src="/application/custom/js/catalogo/altaproductos.js" type="text/javascript"></script>

<script>   
    $('#datatable').dataTable({});

   
   $("#selectall").click(function () {
                var checkAll = $("#selectall").prop('checked');
                    if (checkAll) {
                        $(".case").prop("checked", true);
                    } else {
                        $(".case").prop("checked", false);
                    }
                });
			
</script>