<link href="/application/global/plugins/datatables/datatables.min.css" rel="stylesheet" type="text/css" />
<link href="/application/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.css" rel="stylesheet" type="text/css" />
<div id="my_container">
    <h3 class="page-title">Productos</h3>
    <div class="page-bar">
        <ul class="page-breadcrumb">
            <li>
                <a href="/catalogo/producto">Listado de productos</a>
            </li>
        </ul>
    </div>
    <?php foreach ($messages->getSuccessMessages() as $message):?>
        <div class="alert alert-success alert-dismissable">
            <button class="close" aria-hidden="true" data-dismiss="alert" type="button"></button>
            <strong>Éxito!</strong>
            <?php echo $message?>
        </div>
    <?php endforeach;?>
    <div class="portlet box green" style="border-left-width: 0px; border-bottom-width: 0px; border-right-width: 0px;">
        <div class="portlet-body form">
            <div class="form-body">
                <div class="btn-set pull-right">
                    <form action="/catalogo/producto/export" method="post">
                    <button class="btn default" id="generar_excel" name="generar_pdf" type="submit" style="margin-bottom: 15px;">
                        <i class="fa fa-file-excel-o"></i>
                        Exportar Excel
                    </button>
                    <button class="btn default" id="generar_pdf" name="generar_pdf" type="submit" style="margin-bottom: 15px;">
                        <i class="fa fa-file-pdf-o"></i>
                        Exportar PDF
                    </button>
                    
                    <a id="subir_productos" href="javascript:;"><button class="btn default" type="button" style="margin-bottom: 15px;">Subir productos</button></a>
                   <input type="file" name="batch_productos" style="display: none" accept=".xls,.xlsx">
                    <a href="/catalogo/producto/nuevo"><button class="btn default" type="button" style="margin-bottom: 15px;">Nuevo producto</button></a>
                    </form>
                </div>
                <table class="table table-striped table-bordered table-hover order-column" id="datatable_product" style="border-bottom-width: 0px;">
                    <thead >
                        <tr>
                            <th> Nombre </th>
                            <th> Tipo </th>
                            <th> Categoria </th>
                            <th> Subcategoria </th>
                            <th> Unidad medida </th>
                            <th> Costo </th>
                            <th> Iva </th>
                            <th> Opciones </th>
                        </tr>
                    </thead>
                    <tbody>

                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.8.0/xlsx.full.min.js"></script>
<script src="/application/global/scripts/datatable.js" type="text/javascript"></script>
<script src="/application/global/plugins/datatables/datatables.min.js" type="text/javascript"></script>
<script type="text/javascript" src="https://cdn.datatables.net/plug-ins/1.10.12/api/fnSetFilteringDelay.js"></script>
<script src="/application/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.js" type="text/javascript"></script>
<script src="/application/custom/js/catalogo/usuario.js" type="text/javascript"></script>	
<script>
    
    var plugin = $('#my_container').usuario();
    var empresa_habilitarproductos = "<?php echo json_encode($empresa_habilitarproductos)?>";
    if(empresa_habilitarproductos == "false"){
        $('.btn.default').attr('disabled',true).attr('cursor','not-allowed');
    }

      //INICIALIZAMOS DATATABLES
            var table = $('#datatable_product');
            $.ajax({
                url:'/application/json/datatable/lang_es.json',
                dataType:'json',
                success:function(data){
                   table.dataTable({
                       "language":data,
                       "order":[[0,'asc']],
                       "serverSide": true,
                       processing: true,
                       iDisplayLength:10,
                       "ajax": {
                            "type": "POST"
                        },
                        "columns": [
                            {"data": "producto_nombre", "name": "producto_nombre", "orderable": true},
                            {"data": "producto_tipo", "name": "producto_tipo", "orderable": true},
                            {"data": "categoria_nombre", "name": "categoria_nombre", "orderable": true},
                            {"data": "subcategoria_nombre", "name": "subcategoria_nombre", "orderable": true},
                            {"data": "unidadmedida_nombre", "name": "unidadmedida_nombre", "orderable": true},
                            {"data": "producto_costo", "name": "producto_costo", "orderable": true},
                            {"data": "producto_iva", "name": "producto_iva", "orderable": true},
                            {"data": "options", "name": "options", "orderable": false}
                        ],
                        "columnDefs": [
                            { "orderable": false, "targets": 0 }
                        ]
                   }).fnSetFilteringDelay();
                },
            });

</script>