<link href="/application/global/plugins/datatables/datatables.min.css" rel="stylesheet" type="text/css" />
<link href="/application/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.css" rel="stylesheet" type="text/css" />
<div id="my_container">
    <h3 class="page-title">Productos</h3>
    <div class="page-bar">
        <ul class="page-breadcrumb">
            <li>
                <a href="/catalogo/producto">Listado de productos</a>
            </li>
        </ul>
    </div>
    <?php foreach ($messages->getSuccessMessages() as $message):?>
        <div class="alert alert-success alert-dismissable">
            <button class="close" aria-hidden="true" data-dismiss="alert" type="button"></button>
            <strong>Éxito!</strong>
            <?php echo $message?>
        </div>
    <?php endforeach;?>
    <div class="portlet box green" style="border-left-width: 0px; border-bottom-width: 0px; border-right-width: 0px;">
        <div class="portlet-body form">
            <div class="form-body">
                <div class="btn-set pull-right">
                    <a id="subir_productos" href="javascript:;"><button class="btn default" type="button" style="margin-bottom: 15px;">Subir productos</button></a>
                   <input type="file" name="batch_productos" style="display: none" accept=".xls,.xlsx">
                    <a href="/catalogo/producto/nuevo"><button class="btn default" type="button" style="margin-bottom: 15px;">Nuevo producto</button></a>
                </div>
                <table class="table table-striped table-bordered table-hover order-column" id="datatable" style="border-bottom-width: 0px;">
                    <thead >
                        <tr>
                            <th> Nombre </th>
                            <th> Tipo </th>
                            <th> Categoria </th>
                            <th> Subcategoria </th>
                            <th> Unidad medida </th>
                            <th> Costo </th>
                            <th> Opciones </th>
                        </tr>
                    </thead>
                    <tbody>

                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.8.0/xlsx.full.min.js"></script>
<script src="/application/global/scripts/datatable.js" type="text/javascript"></script>
<script src="/application/global/plugins/datatables/datatables.min.js" type="text/javascript"></script>
<script type="text/javascript" src="https://cdn.datatables.net/plug-ins/1.10.12/api/fnSetFilteringDelay.js"></script>
<script src="/application/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.js" type="text/javascript"></script>
<script src="/application/custom/js/catalogo/usuario.js" type="text/javascript"></script>	
<script>
    
    var plugin = $('#my_container').usuario();
    var empresa_habilitarproductos = "<?php echo json_encode($empresa_habilitarproductos)?>";
    if(empresa_habilitarproductos == "false"){
        $('.btn.default').attr('disabled',true).attr('cursor','not-allowed');
    }

    

</script>