<link href="/application/global/plugins/datatables/datatables.min.css" rel="stylesheet" type="text/css" />
<link href="/application/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.css" rel="stylesheet" type="text/css" />
<div id="my_container">
    <h3 class="page-title">Productos</h3>
    <div class="page-bar">
        <ul class="page-breadcrumb">
            <li>
                <a href="/catalogo/producto">Listado de productos</a>
            </li>
        </ul>
    </div>
    <?php foreach ($messages->getSuccessMessages() as $message):?>
        <div class="alert alert-success alert-dismissable">
            <button class="close" aria-hidden="true" data-dismiss="alert" type="button"></button>
            <strong>Éxito!</strong>
            <?php echo $message?>
        </div>
    <?php endforeach;?>
    <div class="portlet box green" style="border-left-width: 0px; border-bottom-width: 0px; border-right-width: 0px;">
        <div class="portlet-body form">
            <div class="form-body">
                <div class="btn-set pull-right">
                    <a href="#"><button class="btn default" type="button" style="margin-bottom: 15px;">Subir productos</button></a>
                    <a href="/catalogo/producto/nuevo"><button class="btn default" type="button" style="margin-bottom: 15px;">Nuevo producto</button></a>
                </div>
                <table class="table table-striped table-bordered table-hover order-column" id="datatable" style="border-bottom-width: 0px;">
                    <thead >
                        <tr>
                            <th class="text-center"> Nombre </th>
                            <th class="text-center"> Categoria </th>
                            <th class="text-center"> Subcategoria </th>
                            <th class="text-center"> Unidad medida </th>
                            <th class="text-center"> Costo </th>
                            <th class="text-center"> Opciones </th>
                        </tr>
                    </thead>
                    <tbody class="text-center">
                        
                        
                        <?php foreach ($productos as $entity) : ?>

                        <?php $categoria    = \CategoriaQuery::create()->findPk($entity->getIdCategoria()) ?>
                        <?php $subcategoria = \CategoriaQuery::create()->findPk($entity->getIdsubcategoria()) ?>
                        
                            <tr id="<?php echo $entity->getIdproducto() ?>">
                                <td><?php echo $entity->getProductoNombre() ?></td>
                                <td><span class="label label-sm label-success"> <?php echo $categoria->getCategoriaNombre() ?> </span></td>
                                <?php if($subcategoria != NULL): ?>
                                <td><span class="label label-sm label-success"><?php echo $subcategoria->getCategoriaNombre() ?></span></td>
                                <?php else:?>
                                    <td><span class="label label-sm label-danger"> N/A </span></td>
                                <?php endif ?>
                                <td><?php echo $entity->getIdunidadmedida() ?></td>
                                <td><?php echo $entity->getProductocosto() ?></td>
                                
                                <td class="text-left">                                    
                                    <div class="btn-group">
                                        <button class="btn btn-xs green dropdown-toggle" type="button" data-toggle="dropdown" aria-expanded="false"> Acciones
                                            <i class="fa fa-angle-down"></i>
                                        </button>
                                        <ul class="dropdown-menu" role="menu">
                                            <li>
                                                <a href="/catalogo/producto/editar/<?php echo $entity->getIdProducto() ?>">
                                                    <i class="fa fa-pencil"></i> Editar </a>
                                            </li>
                                            <!--
                                            <li>
                                                <a href="javascript:;" class="delete_modal">
                                                    <i class="fa fa-trash"></i> Eliminar </a>
                                            </li>
                                            -->
                                        </ul>
                                    </div>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<script src="/application/global/scripts/datatable.js" type="text/javascript"></script>
<script src="/application/global/plugins/datatables/datatables.min.js" type="text/javascript"></script>
<script src="/application/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.js" type="text/javascript"></script>
<script src="/application/custom/js/catalogo/usuario.js" type="text/javascript"></script>	
<script>
    
    var plugin = $('#my_container').usuario();
    
    

</script>