
<?php $product = new Producto(); ?>
<h3 class="page-title">Registro de subreceta</h3>
<div class="page-bar">
    <ul class="page-breadcrumb">
        <li>
            <a href="/catalogo/producto/editar/<?php echo $producto->getIdproducto() ?>"><?php echo $producto->getProductonombre()?></a>
            <i class="fa fa-angle-right"></i>
        </li>
        <li>
            <span>Registro de subreceta</span>
        </li>
    </ul>
</div>
<?php foreach ($messages->getSuccessMessages() as $message):?>
    <div class="alert alert-success alert-dismissable">
        <button class="close" aria-hidden="true" data-dismiss="alert" type="button"></button>
        <strong>Éxito!</strong>
        <?php echo $message?>
    </div>
<?php endforeach;?>
<?php foreach ($messages->getErrorMessages() as $message):?>
    <div class="alert alert-danger alert-dismissable">
        <button class="close" aria-hidden="true" data-dismiss="alert" type="button"></button>
        <strong>Error!</strong>
        <?php echo $message?>
        
    </div>
<?php endforeach;?>
<?php
    $form->setAttribute('action', '/catalogo/producto/nuevasubreceta/'.$producto->getIdProducto());
    echo $this->form()->openTag($form);
?>
<div class="portlet box green" style="border-left-width: 0px; border-bottom-width: 0px; border-right-width: 0px;">
    <div class="portlet-body form">
        <div class="form-body">
            <h3 class="form-section">Sub receta</h3>
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <?php echo $this->formLabel($form->get('idproductoreceta')) ?>  
                        <?php //echo $this->formSelect($form->get('idproductoreceta')) ?>
                        <div class="input-group">
                            <span class="input-group-addon">
                                <i class="fa fa-search"></i>
                            </span>
                            <input id="idproducto" name="idproductoreceta" type="hidden">
                            <input id="producto_iva" type="hidden">
                            <input id="producto_rendimientooriginal" type="hidden" value="<?php echo $producto->getProductoRendimientooriginal()?>">
                            <input id="producto_rendimiento" type="hidden" value="<?php echo $producto->getProductoRendimiento()?>">
                            <input id="producto_autocomplete" class="form-control" type="text">
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <?php echo $this->formLabel($form->get('receta_cantidadoriginal')) ?>  
                        <?php echo $this->formText($form->get('receta_cantidadoriginal')) ?>
                    </div>
                </div>
                <?php if($producto->getProductoTipo() == 'subreceta' && $producto->getIdcategoria() == 1) :?>
                    <div class="col-md-6">
                        <div class="form-group">
                            <?php echo $this->formLabel($form->get('receta_cantidad')) ?>  
                            <?php echo $this->formText($form->get('receta_cantidad')) ?>
                        </div>
                    </div>
                <?php endif;?>
            </div>
           
            
        </div>
        <div class="form-actions right">
            <button class="btn blue" type="submit">
                <i class="fa fa-check"></i>
                Registrar sub receta
            </button>
        </div>
    </div>
</div>

<script type="text/javascript" src="/application/custom/js/catalogo/subreceta.js"></script>

<script>     

    $("[name=receta_cantidad]").numeric();
    
    var producto_rendimientooriginal = $('#producto_rendimientooriginal').val();
    var producto_rendimiento = $('#producto_rendimiento').val();
    
    if(producto_rendimientooriginal != "" && producto_rendimiento != "")
    {   
        $("[name=receta_cantidadoriginal]").on('change',function(){
            
            
            var cantidad = $("[name=receta_cantidadoriginal]").val();
            var cantidad_normalizada = (cantidad*producto_rendimiento)/producto_rendimientooriginal;
            $('[name=receta_cantidad]').val(cantidad_normalizada.toFixed(2));
        });
    } 
    

</script>