
<?php $product = new Producto(); ?>
<h3 class="page-title">Registro de subreceta</h3>
<div class="page-bar">
    <ul class="page-breadcrumb">
        <li>
            <a href="/catalogo/producto/editar/<?php echo $producto->getIdproducto() ?>"><?php echo $producto->getProductonombre()?></a>
            <i class="fa fa-angle-right"></i>
        </li>
        <li>
            <span>Registro de subreceta</span>
        </li>
    </ul>
</div>
<?php foreach ($messages->getSuccessMessages() as $message):?>
    <div class="alert alert-success alert-dismissable">
        <button class="close" aria-hidden="true" data-dismiss="alert" type="button"></button>
        <strong>Éxito!</strong>
        <?php echo $message?>
    </div>
<?php endforeach;?>
<?php foreach ($messages->getErrorMessages() as $message):?>
    <div class="alert alert-danger alert-dismissable">
        <button class="close" aria-hidden="true" data-dismiss="alert" type="button"></button>
        <strong>Error!</strong>
        <?php echo $message?>
        
    </div>
<?php endforeach;?>
<?php
    $form->setAttribute('action', '/catalogo/producto/nuevasubreceta/'.$producto->getIdProducto());
    echo $this->form()->openTag($form);
?>
<div class="portlet box green" style="border-left-width: 0px; border-bottom-width: 0px; border-right-width: 0px;">
    <div class="portlet-body form">
        <div class="form-body">
            <h3 class="form-section">Sub receta</h3>
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <?php echo $this->formLabel($form->get('idproductoreceta')) ?>  
                        <?php //echo $this->formSelect($form->get('idproductoreceta')) ?>
                        <div class="input-group">
                            <span class="input-group-addon">
                                <i class="fa fa-search"></i>
                            </span>
                            <input name="idproducto" type="hidden" value="<?php echo $producto->getIdProducto()?>">
                            <input id="idproducto" name="idproductoreceta" type="hidden">
                            <input id="producto_iva" type="hidden">
                            <input id="producto_rendimientooriginal" type="hidden" value="<?php echo $producto->getProductoRendimientooriginal()?>">
                            <input id="producto_rendimiento" type="hidden" value="<?php echo $producto->getProductoRendimiento()?>">
                            <input id="productoreceta_rendimiento" type="hidden">
                            <input id="producto_autocomplete" class="form-control" type="text">
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <?php echo $this->formLabel($form->get('receta_cantidadoriginal')) ?>  
                        <?php echo $this->formText($form->get('receta_cantidadoriginal')) ?>
                    </div>
                </div>
                <?php if(($producto->getProductoTipo() == 'subreceta' || $producto->getProductoTipo() == 'plu')  && $producto->getIdcategoria() == 1) :?>
                    <div class="col-md-6">
                        <div class="form-group">
                            <?php echo $this->formLabel($form->get('receta_cantidad')) ?>  
                            <?php echo $this->formText($form->get('receta_cantidad')) ?>
                        </div>
                    </div>
                <?php endif;?>
                <?php if($habilitar_unidad) :?>
                    <div class="col-md-6">
                        <div class="form-group">
                            <?php echo $this->formLabel($form->get('receta_unidad')) ?>  
                            <?php echo $this->formSelect($form->get('receta_unidad')) ?>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <?php echo $this->formLabel($form->get('receta_cantidad')) ?>  
                            <?php echo $this->formText($form->get('receta_cantidad')) ?>
                        </div>
                    </div>
                <?php endif;?>
            </div>
           
            
        </div>
        <div class="form-actions right">
            <button class="btn blue" type="submit">
                <i class="fa fa-check"></i>
                Registrar sub receta
            </button>
        </div>
    </div>
</div>

<script type="text/javascript" src="/application/custom/js/catalogo/subreceta.js"></script>

<script>     

    $("[name=receta_cantidad]").numeric();
    
    var producto_rendimientooriginal = $('#producto_rendimientooriginal').val();
    var producto_rendimiento = $('#producto_rendimiento').val();
    var factor=1;


    if(producto_rendimientooriginal != "" && producto_rendimiento != "")
    {
        $("[name=receta_cantidadoriginal],select[name=receta_unidad]").on('change',function(){
            if(typeof  $('select[name=receta_unidad] option:selected').val() != 'undefined'){
                producto_rendimiento = $('#productoreceta_rendimiento').val();
                var unidad = $('select[name=receta_unidad] option:selected').val();
                if(unidad == "Onza"){
                    factor = 29.574;
                }else if(unidad == "Copa vino 187.5 ML"){
                     factor = 187.5;
                }else if(unidad == "Copa vino 150 ML"){
                    factor =150;
                }
                var cantidad = $("[name=receta_cantidadoriginal]").val();
                if(unidad == "Pieza" || unidad == "Botella"){
                    var cantidad_normalizada = (cantidad*factor);
                 }
                 else
                {
                    var cantidad_normalizada = (cantidad*factor)/producto_rendimiento;
                }
                                                                          
            }
            else
            {
                var cantidad = $("[name=receta_cantidadoriginal]").val();
                var cantidad_normalizada = (cantidad*producto_rendimiento)/producto_rendimientooriginal;
            }
            $('[name=receta_cantidad]').val(cantidad_normalizada.toFixed(6));
        });
    }
    

</script>
