<link rel="stylesheet" type="text/css" href="/application/custom/css/validaciones.css">
<link href="/application/custom/css/multiple-select.css" rel="stylesheet"/>
<h3 class="page-title"><?php echo $form->get('usuario_nombre')->getValue()?></h3>
<div class="page-bar">
    <ul class="page-breadcrumb">
        <li>
            <a href="/catalogo/usuario">Usuarios</a>
            <i class="fa fa-angle-right"></i>
        </li>
        <li>
            <span><?php echo $form->get('usuario_nombre')->getValue()?></span>
        </li>
    </ul>
</div>
<?php foreach ($messages->getSuccessMessages() as $message):?>
    <div class="alert alert-success alert-dismissable">
        <button class="close" aria-hidden="true" data-dismiss="alert" type="button"></button>
        <strong>Éxito!</strong>
        <?php echo $message?>
    </div>
<?php endforeach;?>
<?php foreach ($messages->getErrorMessages() as $message):?>
    <div class="alert alert-danger alert-dismissable">
        <button class="close" aria-hidden="true" data-dismiss="alert" type="button"></button>
        <strong>Error!</strong>
        <?php echo $message?>
        
    </div>
<?php endforeach;?>
<?php
    $form->setAttribute('action', '/catalogo/usuario/editar/'.$form->get('idusuario')->getValue());
    echo $this->form()->openTag($form);
?>
<div class="portlet box green" style="border-left-width: 0px; border-bottom-width: 0px; border-right-width: 0px;">
    <div class="portlet-body form">
        <div class="form-body">
            <h3 class="form-section">Información general</h3>
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <?php echo $this->formLabel($form->get('usuario_nombre')) ?>  
                        <?php echo $this->formText($form->get('usuario_nombre')) ?>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <?php echo $this->formLabel($form->get('idrol')) ?>  
                        <?php echo $this->formSelect($form->get('idrol')) ?>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <?php echo $this->formLabel($form->get('usuario_username')) ?>  
                        <?php echo $this->formText($form->get('usuario_username')) ?>
                    </div>
                </div>
                <div class="col-md-6">
                    <div >
                        <?php echo $this->formLabel($form->get('usuario_estatus')) ?>  
                        <?php echo $this->formSelect($form->get('usuario_estatus')) ?>
                    </div>
                </div>
                
            </div>
            <div class="row" style="display: none" id="usuario_empresa_container">
                    <div class="col-md-6">
                        <div class="form-group test">
                            <label for="idempresas">Empresas a cargo</label></br>

                            <select name="idempresas[]" id="empresas" formnovalidate="formnovalidate" class="row col-md-12" multiple="multiple">

                                <?php foreach( $empresas as $item): ?>
                                    <option value="<?php echo $item->getIdempresa() ?>"><?php echo $item->getEmpresanombrecomercial() ?></option>
                                <?php endforeach; ?>

                            </select>
                        </div>
                    </div>
                </div>
            <div class="row">
                <div class="col-md-12">
                    <p>(*)Campos obligatorios</p>
                </div>
            </div>
        </div>
        <div class="form-actions right">
            <button class="btn blue" type="submit">
                <i class="fa fa-check"></i>
                Guardar
            </button>
        </div>
    </div>
</div>
<?php  echo $this->form()->closeTag(); ?>

<?php
    $form->setAttribute('action', '/catalogo/usuario/changepassword/'.$form->get('idusuario')->getValue());
    echo $this->form()->openTag($form);
?>
<div class="portlet box green" style="border-left-width: 0px; border-bottom-width: 0px; border-right-width: 0px;">
    <div class="portlet-body form">
        <div class="form-body">
            <h3 class="form-section">Cambiar contraseña</h3>
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <?php echo $this->formLabel($form->get('usuario_password')) ?>  
                        <?php echo $this->formPassword($form->get('usuario_password')) ?>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <p>(*)Campos obligatorios</p>
                </div>
            </div>
        </div>
        <div class="form-actions right">
            <button class="btn blue" type="submit">
                <i class="fa fa-check"></i>
                Guardar
            </button>
        </div>
    </div>
</div>
<?php  echo $this->form()->closeTag(); ?>
<script src="/application/custom/js/multiple-select.js"></script>
<script>
    
    $('#empresas').multipleSelect();
    
    var idrol = <?php echo $idrol ?>;
    if(idrol == 2){
        $('#usuario_empresa_container').show();
    }

    $("#empresas").multipleSelect("setSelects", <?php echo $usuario_empresa?>);
    
    $('select[name=idrol]').on('change',function(){
        var val = $('select[name=idrol] option:selected').val();
        if(val == 2){
            $('#usuario_empresa_container').show();
        }else{
            $("#empresas").multipleSelect("uncheckAll");
            $('#usuario_empresa_container').hide();
        }
    });

</script>
    