<link href="/application/global/plugins/datatables/datatables.min.css" rel="stylesheet" type="text/css" />
<link href="/application/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.css" rel="stylesheet" type="text/css" />
<div id="my_container">
    <h3 class="page-title">Reporte Anual</h3>
    <div class="page-bar">
        <ul class="page-breadcrumb">
            <li>
                <a href="/flujoefectivo/reportes/anual">Reporte Anual</a>
            </li>
        </ul>
    </div>
    <div class="portlet box " style="border-left-width: 0px; border-bottom-width: 0px; border-right-width: 0px;">
        <div class="portlet-body form">
            <div class="form-body">
                <div class="btn-set pull-right">
                    <a href="/flujoefectivo/cuentabancaria/nuevo"><button class="btn default" type="button" style="margin-bottom: 15px;">Nueva cuenta bancaria</button></a>
                </div>
                <table class="table table-striped table-bordered table-hover order-column" id="datatable"  style="border-bottom-width: 0px;">
                    <thead>
                        <tr>
                            <th class="text"> Banco </th>
                        </tr>
                    </thead>
                    <tbody class="text">
                        <tr id="<?php echo $entity->getIdcuentabancaria()?>">
                            <td><?php echo $entity->getCuentabancariaBanco() ?></td>
                            </tr>
                    </tbody>
                </table>
            </div>
        </div>
        
    </div>
</div>

<script src="/application/global/scripts/datatable.js" type="text/javascript"></script>
<script src="/application/global/plugins/datatables/datatables.min.js" type="text/javascript"></script>
<script src="/application/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.js" type="text/javascript"></script>
<script src="/application/custom/js/flujoefectivo/reportes.js" type="text/javascript"></script>	


<script>
    var $plugin = $('#my_container').reportes();
    $plugin.anual();
</script>