<link href="/application/global/plugins/datatables/datatables.min.css" rel="stylesheet" type="text/css" />
<link href="/application/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.css" rel="stylesheet" type="text/css" />
<div id="my_container">
    <h3 class="page-title">Reporte anual</h3>
    <div class="page-bar">
        <ul class="page-breadcrumb">
            <li>
                <a href="/flujoefectivo/reportes/anual">Reporte anual</a>
            </li>
        </ul>
    </div>
    <?php
    echo $this->form()->openTag($form);
    ?>
    <div class="portlet box green" style="border-left-width: 0px; border-bottom-width: 0px; border-right-width: 0px;">
        <div class="portlet-body form">
            <div class="form-body">
                <div class="row">
                    <div class="col-md-6">
                        <?php echo $this->formLabel($form->get('ano')) ?>  
                        <?php echo $this->formSelect($form->get('ano')) ?> 
                    </div>
                </div>
                <br>
                <div class="row">
                    <div class="col-md-12">
                        <p>(*)Campos obligatorios</p>
                    </div>
                </div>

            </div>
            <div class="form-actions right">
                <button disabled class="btn blue" id="anual_generar" type="button">
                    <i class="fa fa-check"></i>
                    Generar
                </button>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <table class="table" id="reporte_table">
                        <thead>
                        <th>Concepto</th>
                        <th>Total</th>
                        <th>Total</th>
                        </thead>
                        <tbody id="tbody">
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="/application/global/scripts/datatable.js" type="text/javascript"></script>
<script src="/application/global/plugins/datatables/datatables.min.js" type="text/javascript"></script>
<script src="/application/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.js" type="text/javascript"></script>
<script src="/application/custom/js/flujoefectivo/reportes.js" type="text/javascript"></script>	
<script>
    var $plugin = $('#my_container').reportes();
    $plugin.anual();
</script>