<style>
    input[type=file]{
        padding-top: 0px;
        padding-left: 0px;
    }
    #productos_table .fa-trash{
        color:red;
    }
    #productos_table input{
        width: 80px;
    }
</style>
<link rel="stylesheet" type="text/css" href="/application/custom/css/validaciones.css">
<div class="page-bar">
        <ul class="page-breadcrumb">
            <li>
                <a href="javascript:;">Flujo de efectivo</a>
                 <i class="fa fa-angle-right"></i>
            </li>
            <li>
                <a href="/flujoefectivo/cuentasporpagar/">Cuentas por pagar</a>
                 <i class="fa fa-angle-right"></i>
            </li>
            <li>
                <a href="javascript:;"><?php echo '#'.$form->get('idcompra')->getValue()?></a>
            </li>
        </ul>
</div>
<div id="form_container">
    <form class="form-horizontal" action="/procesos/compra/editar/<?php echo $form->get('idcompra')->getValue()?>" method="post" enctype="multipart/form-data">
        <div class="portlet box green" style="border-left-width: 0px; border-bottom-width: 0px; border-right-width: 0px;">
            <div class="portlet-body form">
                <div class="form-body">
                    <div class="form-body">
                        <h3 class="page-title">Información general</h3>
                        <h5>Total: <?php echo money_format('%(#10n',$total) ?>, Restan: <?php echo money_format('%(#10n',$restan) ?></h5>
                        <div class="form-group">
                            <div class="col-md-6">
                                <?php echo $this->formHidden($form->get('idcompra')) ?> 
                                <?php echo $this->formHidden($form->get('idproveedor')) ?>
                                <?php echo $this->formLabel($form->get('flujoefectivo_fecha')) ?>  
                                <?php echo $this->formText($form->get('flujoefectivo_fecha')) ?> 
                            </div>
                            <div class="col-md-6">
                                <?php echo $this->formLabel($form->get('flujoefectivo_pago')) ?>  
                                <?php echo $this->formSelect($form->get('flujoefectivo_pago')) ?> 
                            </div>
                            
                        </div>
                        <div class="form-group">
                            <div class="col-md-6">
                                <?php echo $this->formLabel($form->get('idcuentabancaria')) ?>  
                                <?php echo $this->formSelect($form->get('idcuentabancaria')) ?> 
                            </div>
                            <div class="col-md-6">
                                <?php echo $this->formLabel($form->get('flujoefectivo_cantidad')) ?>  
                                <?php echo $this->formText($form->get('flujoefectivo_cantidad')) ?> 
                            </div>
                            
                        </div>
                        <div class="form-group">
                            <div class="col-md-6">
                                <?php echo $this->formLabel($form->get('flujoefectivo_mediodepago')) ?>  
                                <?php echo $this->formSelect($form->get('flujoefectivo_mediodepago')) ?> 
                            </div>
                            <div class="col-md-6">
                                <?php echo $this->formLabel($form->get('flujoefectivo_referencia')) ?>  
                                <?php echo $this->formText($form->get('flujoefectivo_referencia')) ?> 
                            </div>
                            
                        </div>
                        <div class="form-group">
                            <div class="col-md-6">
                                <?php echo $this->formLabel($form->get('flujoefectivo_chequecirculacion')) ?>  
                                <?php echo $this->formSelect($form->get('flujoefectivo_chequecirculacion')) ?> 
                            </div>
                            <div class="col-md-6">
                                <?php echo $this->formLabel($form->get('flujoefectivo_fechacobrocheque')) ?>  
                                <?php echo $this->formText($form->get('flujoefectivo_fechacobrocheque')) ?> 
                            </div>
                            
                        </div>
                        <div class="form-group">
                            <div class="col-md-6">
                                <?php echo $this->formLabel($form->get('flujoefectivo_comprobante')) ?>  
                                <?php echo $this->formFile($form->get('flujoefectivo_comprobante')) ?> 
                            </div>
                            <div class="col-md-6">
                               
                                
                            </div>
                            
                        </div>
                        
                    </div>
                </div>
                <div class="form-actions right">
                    <button class="btn blue" type="submit">
                        <i class="fa fa-check"></i>
                        Guardar
                    </button>
                </div>
            </div>
        </div>
        <div class="portlet box green" style="border-left-width: 0px; border-bottom-width: 0px; border-right-width: 0px;">
            <div class="portlet-body form">
                <div class="form-body">
                    <div class="row">
                        <h3 class="page-title">Movimientos</h3>
                        <div class="table-responsive">
                            <table class="table" id="productos_table">
                                <thead>
                                    <th>Fecha</th>
                                    <th>Pago</th>
                                    <th>Cuenta</th>
                                    <th>Cantidad</th>
                                    <th>Medio</th>
                                    <th>Referencia</th>
                                    <th>Comprobante</th>
                                    <th>Opciones</th>
                                </thead>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>    
    </form>
</div>
<script type="text/javascript" src="/application/custom/js/flujoefectivo/cuentasporpagar.js"></script>
<script>
    var $form = $('#form_container').cuentasporpagar();
    $form.edit();
</script>
