
<link href="/application/global/plugins/datatables/datatables.min.css" rel="stylesheet" type="text/css" />
<link href="/application/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.css" rel="stylesheet" type="text/css" />
<div id="my_container">
    <h3 class="page-title">Cuentas por pagar</h3>
    <div class="page-bar">
        <ul class="page-breadcrumb">
            <li>
                <a href="/flujoefectivo/cuentasporpagar">Cuentas por pagar</a>
            </li>
        </ul>
    </div>
    <?php foreach ($messages->getSuccessMessages() as $message):?>
        <div class="alert alert-success alert-dismissable">
            <button class="close" aria-hidden="true" data-dismiss="alert" type="button"></button>
            <strong>Éxito!</strong>
            <?php echo $message?>
        </div>
    <?php endforeach;?>
    <div class="portlet box " style="border-left-width: 0px; border-bottom-width: 0px; border-right-width: 0px;">
        <div class="portlet-body form">
            <div class="form-body">
                <table class="table table-striped table-bordered table-hover order-column" id="datatable"  style="border-bottom-width: 0px;">
                    <thead>
                        <tr>
                            <th class="text"> Proveedor </th>
                            <th class="text"> Folio </th>
                            <th class="text"> Fecha </th>
                            <th class="text"> Total </th>
                            <th class="text"> Pagada </th>
                            <th class="text"> Por pagar </th>
                            <th class="text"> Opciones </th>
                            <th class="text"> Fecha </th>
                        </tr>
                    </thead>
                    <tbody class="text">
                        <?php $entity = new Compra();
                        foreach ($collection as $entity) : ?>
                        <tr id="<?php echo $entity->getProveedor()->getProveedorNombrecomercial()?>">
                            <td><?php echo $entity->getCuentabancariaBanco() ?></td>
                            <td><?php echo $entity->getCuentabancariaNocuenta() ?></td>
                            <td><?php echo $entity->getCuentabancariaBalance() ?></td>
                                <td>
                                    <div class="btn-group">
                                        <button class="btn btn-xs green dropdown-toggle" type="button" data-toggle="dropdown" aria-expanded="false"> Acciones
                                            <i class="fa fa-angle-down"></i>
                                        </button>
                                        <ul class="dropdown-menu" role="menu">
                                            <li>
                                                <a href="/flujoefectivo/cuentabancaria/editar/<?php echo $entity->getIdcuentabancaria()?>">
                                                    <i class="fa fa-pencil"></i> Editar </a>
                                            </li>
                                            <li>
                                                <a href="javascript:;" class="delete_modal">
                                                    <i class="fa fa-trash"></i> Eliminar </a>
                                            </li>
                                        </ul>
                                    </div>
                                    
                                </td>
                            </tr>                            
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
        
    </div>
</div>

<script src="/application/global/scripts/datatable.js" type="text/javascript"></script>
<script src="/application/global/plugins/datatables/datatables.min.js" type="text/javascript"></script>
<script src="/application/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.js" type="text/javascript"></script>
<script src="/application/custom/js/flujoefectivo/cuentabancaria.js" type="text/javascript"></script>	


<script>
    var $plugin = $('#my_container').cuentabancaria();
    $plugin.list();
</script>