<style>
    .page-content{
        background-color: #FFF !important;
    }
</style>
<div class="row">
    <div class="col-md-4 col-md-offset-4">
        <img src="/website/img/CFCI AERSA.png"> 
    </div>
    
</div>
<div>
    <h1><?php echo sprintf($this->translate('Bienvenido a AERSA CFCI'), '<span class="zf-green">', '</span>') ?></h1>
    <p>Con AERSA CFCI se controla dentro de una sola plataforma los siguientes puntos clave de su empresa:</p>
</div>


<div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Flujo de efectivo') ?></h3>
            </div>
            <div class="panel-body">
                <p>Control de entradas y salidas de flujo de efectivo, cuentas bancarias y cuentas por cobrar y pagar.</p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Costos') ?></h3>
            </div>
            <div class="panel-body">
                <p>
                    Control de costos diarios, recetas técnicas y consumos. 
                </p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Inventarios') ?></h3>
            </div>
            <div class="panel-body">
                <p> Valuación y control de inventarios, así como detección de fugas por negligencia o dolo. </p>
            </div>
        </div>
    </div>
</div>
