<link href="/application/global/plugins/datatables/datatables.min.css" rel="stylesheet" type="text/css" />
<link href="/application/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.css" rel="stylesheet" type="text/css" />
<div id="my_container">
    <h3 class="page-title">Inventario cierre de semana</h3>
    <div class="page-bar">
        <ul class="page-breadcrumb">
            <li>
                <a href="/auditoria/cierresemana">Inventario cierre de semana</a>
            </li>
        </ul>
    </div>
    <?php
    $form->setAttribute('action', '/auditoria/cierresemana/editar/'.$inventariomes->getIdinventariomes());
    echo $this->form()->openTag($form);
    ?>
    <div class="portlet box green" style="border-left-width: 0px; border-bottom-width: 0px; border-right-width: 0px;">
        <div class="portlet-body form">
            <div class="form-body">
                <br>
                <div class="row">
                    <div class="col-md-4">
                        <?php echo $this->formLabel($form->get('idalmacen')) ?>  
                        <?php echo $this->formHidden($form->get('idinventariomes')) ?> 
                        <?php echo $this->formSelect($form->get('idalmacen')) ?> 
                    </div>
                    <div class="col-md-4"></div>
                    <div class="col-md-4">
                        <?php echo $this->formLabel($form->get('inventariomes_fecha')) ?>  
                        <?php echo $this->formDate($form->get('inventariomes_fecha')) ?> 
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4">
                        <?php echo $this->formLabel($form->get('idauditor')) ?>  
                        <?php echo $this->formSelect($form->get('idauditor')) ?> 
                    </div>
                    <div class="col-md-4"></div>
                    <div class="col-md-4">
                        <br>
                        <div class="btn-set pull-right">
                            <input type="file" name="batch_inventario" style="display: none" accept=".xls,.xlsx">
                            <a id="subir_inventario" href="#"><button class="btn default" type="button" style="margin-bottom: 15px; margin-right: 10px">Subir inventario</button></a>
                        </div>
                    </div>
                </div>
                <div id="revisada" class="row" >
                    <div class="col-md-4">
                        <?php echo $this->formLabel($form->get('inventariomes_revisada')) ?>  
                        <?php echo $this->formSelect($form->get('inventariomes_revisada')) ?> 
                    </div>
                </div>
                
                <br>
                <div class="form-actions right">
                    <div class="left col-md-2">
                        <button class="btn blue" id="generar_pdf" name="generar_pdf" type="submit">
                            <i class="fa fa-file-pdf-o"></i>
                            PDF
                        </button>
                    </div>
                    <div class="left col-md-2">
                        <button class="btn blue" id="generar_excel" name="generar_excel" type="submit">
                            <i class="fa fa-file-excel-o"></i>
                            Excel
                        </button>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <p>(*)Campos obligatorios</p>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12" style="overflow: scroll; white-space: nowrap;">
                        <table class="table" id="reporte_table">
                            <thead>
                            <th>ID</th>
                            <th>Nomb</th>
                            <th>ExistIni</th>
                            <th>Cmpr</th>
                            <th>ReqIng</th>
                            <th>OrdTabIng</th>
                            <th>Vnt</th>
                            <th>ReqEg</th>
                            <th>OrdTabEg</th>
                            <th>Dev</th>
                            <th>Ajst</th>
                            <th>StT</th>
                            <th>Unid</th>
                            <th>StF</th>
                            <th>Explo</th>
                            <th>FisTot</th>
                            <th>ImpFis</th>
                            <th>Dif</th>
                            <th>CostProm</th>
                            <th>DifImp</th>
                            <th>SubCat</th>
                            <th>Revisado</th>
                            </thead>
                            <tbody id="tbody">
                                <?php $detalle = new Inventariomesdetalle()?>
                                <?php foreach ($reporte as $line) :?>
                                <?php echo $line;?>

                                <?php endforeach?>
                                <tr><td>Responsable</td><td><?php echo $encargado?></td><td></td><td><td></td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>Final alimentos</td><td class='inventariomes_finalalimentos'><input type='hidden'  name='inventariomes_finalalimentos' value='<?php echo $inventariomes->getInventariomesFinalalimentos()?>'><span><?php echo $inventariomes->getInventariomesFinalalimentos()?></span></td></tr>
                                <tr><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>Final bebidas</td><td class='inventariomes_finalbebidas'><input type='hidden'  name='inventariomes_finalbebidas' value='<?php echo $inventariomes->getInventariomesFinalbebidas()?>'><span><?php echo $inventariomes->getInventariomesFinalbebidas()?></span></td></tr>
                                <tr><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>Sobrante</td><td class='inventariomes_sobrantes'><input type='hidden'  name='inventariomes_sobrantes' value='<?php echo $inventariomes->getInventariomesSobrantes()?>'><span><?php echo $inventariomes->getInventariomesSobrantes()?></span></td></tr>
                                <tr><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>Faltante</td><td class='inventariomes_faltantes'><input type='hidden'  name='inventariomes_faltantes' value='<?php echo $inventariomes->getInventariomesFaltantes()?>'><span><?php echo $inventariomes->getInventariomesFaltantes()?></span></td></tr>
                                <tr><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>Total</td><td class='inventariomes_total'><input type='hidden'  name='inventariomes_total' value='<?php echo $inventariomes->getInventariomesTotal()?>'><span><?php echo $inventariomes->getInventariomesTotal()?></span></td></tr>
                                <tr><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>Importe Fisico</td><td class='inventariomes_totalimportefisico'><input type='hidden'  name='inventariomes_totalimportefisico' value='<?php echo $inventariomes->getInventariomesTotalimportefisico()?>'><span><?php echo $inventariomes->getInventariomesTotalimportefisico()?></span></td></tr>
                            </tbody>
                        </table>
                    </div>
                </div>
                <div id="boton_g" name="boton_g" class="form-actions right">
                    <button class="btn blue" id="plantilla_save" type="submit">
                        <i class="fa fa-check"></i>
                        Guardar
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>
<div id="alert_container"></div>
<div id="comentarios_container" class="portlet box green" style="border-left-width: 0px; border-bottom-width: 0px; border-right-width: 0px;">
    <div class="portlet-body form">
        <div class="portlet-body form">
            <div class="form-body">
                <div class="btn-set pull-right">
                    <a id="nota_nuevo" href="javascript:;" class="btn default">Nuevo comentario</a>
                </div>
                 <h3 class="page-title">Comentarios</h3>
                 <div class="mt-comments">

                 </div>
            </div>
        </div>
    </div>
</div>
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.0/themes/base/jquery-ui.css">
<!--<link rel="stylesheet" href="/resources/demos/style.css">-->
<script type="text/javascript" src="/application/custom/js/procesos/comentarios.js"></script>

<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.8.0/xlsx.full.min.js"></script>
<!--<script src="https://code.jquery.com/jquery-1.12.4.js"></script>-->
<script src="https://code.jquery.com/ui/1.12.0/jquery-ui.js"></script>
<script src="/application/global/scripts/datatable.js" type="text/javascript"></script>
<script src="/application/global/plugins/datatables/datatables.min.js" type="text/javascript"></script>
<script src="/application/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.js" type="text/javascript"></script>
<script src="/application/custom/js/auditoria/cierresinventarios.js" type="text/javascript"></script>
<script>
    var $plugin = $('#my_container').cierresinventarios();
    $plugin.edit(<?php echo "'$fecha'";?>);
</script>