<link href="/application/global/plugins/datatables/datatables.min.css" rel="stylesheet" type="text/css" />
<link href="/application/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.css" rel="stylesheet" type="text/css" />
<div id="my_container">
    <h3 class="page-title">Inventario cierre de semana</h3>
    <div class="page-bar">
        <ul class="page-breadcrumb">
            <li>
                <a href="/auditoria/cierresemana">Inventario cierre de semana</a>
            </li>
        </ul>
    </div>
    <?php
    $form->setAttribute('action', '/auditoria/cierresemana/nuevo');
    echo $this->form()->openTag($form);
    ?>
    <div class="portlet box green" style="border-left-width: 0px; border-bottom-width: 0px; border-right-width: 0px;">
        <div class="portlet-body form">
            <div class="form-body">
                <br>
                <div class="row">
                    <div class="col-md-4">
                        <?php echo $this->formLabel($form->get('idalmacen')) ?>  
                        <?php echo $this->formSelect($form->get('idalmacen')) ?> 
                    </div>
                    <div class="col-md-4"></div>
                    <div class="col-md-4">
                        <?php echo $this->formLabel($form->get('inventariomes_fecha')) ?>  
                        <?php echo $this->formDate($form->get('inventariomes_fecha')) ?> 
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4">
                        <?php echo $this->formLabel($form->get('idauditor')) ?>  
                        <?php echo $this->formSelect($form->get('idauditor')) ?> 
                    </div>
                    <div class="col-md-4"></div>
                    <div class="col-md-4">
                        <br>
                        <div class="btn-set pull-right">
                            <input type="file" name="batch_inventario" style="display: none" accept=".xls,.xlsx">
                            <a id="subir_inventario" href="#"><button name="batch_inventario_b" id="batch_inventario_b" class="btn default" type="button" style="margin-bottom: 15px; margin-right: 10px">Subir inventario</button></a>
                        </div>
                    </div>                        
                </div>
                <div id="revisada" class="row" style="display: none">
                    <div class="col-md-4">
                        <?php echo $this->formLabel($form->get('inventariomes_revisada')) ?>  
                        <?php echo $this->formSelect($form->get('inventariomes_revisada')) ?> 
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <p>(*)Campos obligatorios</p>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12" style="overflow: scroll; white-space: nowrap;">
                        <table class="table" id="reporte_table">
                            <thead>
                            <th>ID</th>
                            <th>Nomb</th>
                            <th>ExistIni</th>
                            <th>Cmpr</th>
                            <th>ReqIng</th>
                            <th>OrdTabIng</th>
                            <th>Vnt</th>
                            <th>ReqEg</th>
                            <th>OrdTabEg</th>
                            <th>Dev</th>
                            <th>Ajst</th>
                            <th>StT</th>
                            <th>Unid</th>
                            <th>StF</th>
                            <th>Explo</th>
                            <th>FisTot</th>
                            <th>ImpFis</th>
                            <th>Dif</th>
                            <th>CostProm</th>
                            <th>DifImp</th>
                            <th>Revisado</th>
                            </thead>
                            <tbody id="tbody">
                            </tbody>
                        </table>
                    </div>
                </div>
                <div id="boton_g" name="boton_g" class="form-actions right" style="display: none">
                    <button class="btn blue" id="plantilla_save" type="submit">
                        <i class="fa fa-check"></i>
                        Guardar
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.0/themes/base/jquery-ui.css">
<!--<link rel="stylesheet" href="/resources/demos/style.css">-->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.8.0/xlsx.full.min.js"></script>
<!--<script src="https://code.jquery.com/jquery-1.12.4.js"></script>-->
<script src="https://code.jquery.com/ui/1.12.0/jquery-ui.js"></script>
<script src="/application/global/scripts/datatable.js" type="text/javascript"></script>
<script src="/application/global/plugins/datatables/datatables.min.js" type="text/javascript"></script>
<script src="/application/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.js" type="text/javascript"></script>
<script src="/application/custom/js/auditoria/cierresinventarios.js" type="text/javascript"></script>
<script>
    var $plugin = $('#my_container').cierresinventarios();
    $plugin.new(<?php echo "'$fecha'";?>);
</script>