<style>
    input[type=file]{
        padding-top: 0px;
        padding-left: 0px;
    }
    #productos_table .fa-trash{
        color:red;
    }
    #productos_table input{
        width: 80px;
    }
</style>
<link rel="stylesheet" type="text/css" href="/application/custom/css/validaciones.css">
<div class="page-bar">
        <ul class="page-breadcrumb">
            <li>
                <a href="javascript:;">Procesos</a>
                 <i class="fa fa-angle-right"></i>
            </li>
            <li>
                <a href="/procesos/consignacion">Consignaciones</a>
                 <i class="fa fa-angle-right"></i>
            </li>
            <li>
                <a href="javascript:;"><?php echo '#'.$form->get('idcompra')->getValue()?></a>
            </li>
        </ul>
</div>
<div id="form_container">
    <form class="form-horizontal" action="/procesos/consignacion/editar/<?php echo $form->get('idcompra')->getValue()?>" method="post" enctype="multipart/form-data">
    <div class="portlet box green" style="border-left-width: 0px; border-bottom-width: 0px; border-right-width: 0px;">
        <div class="portlet-body form">
            <div class="form-body">
                <h3 class="page-title">Consignación - <?php echo '#'.$form->get('idcompra')->getValue()?></h3>
                <div class="row">
                    <div class="form-group">
                        <div class="col-md-6">
                            <?php echo $this->formLabel($form->get('compra_fechacompra')) ?>  
                            <?php echo $this->formText($form->get('compra_fechacompra')) ?> 
                            <?php echo $this->formHidden($form->get('compra_fechacreacion')) ?> 
                            <?php echo $this->formHidden($form->get('idcompra')) ?>
                        </div>
                        <div class="col-md-6">
                            <?php echo $this->formLabel($form->get('compra_tipo')) ?>  
                            <?php echo $this->formSelect($form->get('compra_tipo')) ?> 
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-6">
                            <?php echo $this->formHidden($form->get('idproveedor')); ?>  
                            <?php echo $this->formLabel($form->get('idproveedor_autocomplete')); ?>  
                            <div class="input-group">
                                <span class="input-group-addon">
                                    <i class="fa fa-search"></i>
                                </span>
                                 <?php echo $this->formText($form->get('idproveedor_autocomplete')); ?>  

                            </div>

                        </div>
                        <div class="col-md-6">
                            <?php echo $this->formLabel($form->get('compra_folio')) ?>  
                            <?php echo $this->formText($form->get('compra_folio')) ?> 
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-6">

                            <?php echo $this->formLabel($form->get('compra_fechaentrega')) ?>  
                            <?php echo $this->formText($form->get('compra_fechaentrega')) ?> 
                        </div>
                        <div class="col-md-6">
                            <?php echo $this->formLabel($form->get('compra_factura')) ?>  
                            <?php echo $this->formFile($form->get('compra_factura')) ?> 
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-6">

                            <?php echo $this->formLabel($form->get('idalmacen')) ?>  
                            <?php echo $this->formSelect($form->get('idalmacen')) ?> 
                        </div>
                        <div class="col-md-6">
                            <?php echo $this->formLabel($form->get('compra_revisada')) ?>  
                            <?php echo $this->formSelect($form->get('compra_revisada')) ?> 
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="form-group">
                        <div class="col-md-6">
                            <label>Creado por</label>
                            <input class="form-control" type="text" value="<?php echo $entity->getUsuarioRelatedByIdusuario()->getUsuarioNombre();?>" readonly="readonly"> 
                        </div>
                        <div class="col-md-6">
                            <label>Auditor</label>
                            <?php  
                                if($entity->getCompraRevisada()){
                                    $auditor = $entity->getUsuarioRelatedByIdauditor()->getUsuarioNombre();
                                }else{
                                    $auditor = 'N/D';
                                } 
                            ?>
                            <input class="form-control" type="text" value="<?php echo $auditor;?>" readonly="readonly"> 
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="portlet box green" style="border-left-width: 0px; border-bottom-width: 0px; border-right-width: 0px;">
        <div class="portlet-body form">
            <div class="portlet-body form">
                <div class="form-body">
                    <h3 class="page-title">Productos</h3>
                    <div class="row">
                        <div class="form-group">
                            <div class="col-md-4 col-md-offset-6">
                                <div class="input-group">
                                    <span class="input-group-addon">
                                        <i class="fa fa-search"></i>
                                    </span>
                                    <input id="idproducto" type="hidden">
                                    <input id="producto_iva" type="hidden">
                                    <input id="unidadmedida_nombre" type="hidden">
                                    <input id="producto_autocomplete" class="form-control" type="text">
                                </div>
                            </div>
                            <div class="col-md-1">
                                <button disabled id="producto_add" class="btn grey-mint" type="button">Agregar</button>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                         <div class="table-responsive">
                            <table class="table" id="productos_table">
                            <thead>
                                <th>Producto</th>
                                <th>Unidad</th>
                                <th>Cantidad</th>
                                <th>Precio</th>
                                <th>C.U. Neto</th>
                                <th>Desc. (%)</th>
                                <th>IEPS (%)</th>
                                <th>Subtotal</th>
                                <th>Revisada</th>
                                <th>Almacen</th>
                                <th>Opciones</th>
                            </thead>
                            <tbody>
                                <?php $detalle = new Compradetalle()?>
                                <?php foreach ($compra_detalle as $detalle) :?>
                                <tr id="<?php echo $detalle->getIdcompradetalle()?>">
                                    <td>
                                        <input type="hidden" name="productos[<?php echo $detalle->getIdcompradetalle()?>][subtotal]" value="<?php echo $detalle->getCompradetalleSubtotal()?>">
                                        <input type="hidden" name="productos[<?php echo $detalle->getIdcompradetalle()?>][costo_unitario]" value="<?php echo $detalle->getCompradetalleCostounitario()?>">
                                        <input type="hidden" name="productos[<?php echo $detalle->getIdcompradetalle()?>][producto_iva]" value="<?php echo $detalle->getProducto()->getProductoIva()?>">
                                        <input type="hidden" name="productos[<?php echo $detalle->getIdcompradetalle()?>][idproducto]" value="<?php echo $detalle->getIdproducto()?>">
                                        <?php echo $detalle->getProducto()->getProductoNombre()?>
                                    </td>
                                    <td>
                                        <?php echo $detalle->getProducto()->getUnidadmedida()->getUnidadmedidaNombre()?>
                                    </td>
                                    <td>
                                        <input type="text" name="productos[<?php echo $detalle->getIdcompradetalle()?>][cantidad]" value="<?php echo $detalle->getCompradetalleCantidad()?>"> 
                                    </td>
                                    <td>
                                        <input type="text" name="productos[<?php echo $detalle->getIdcompradetalle()?>][precio]" value="<?php echo $detalle->getCompradetallePrecio()?>"> 
                                    </td>
                                    <td>
                                        <?php echo money_format('%+#1.6n',$detalle->getCompradetalleCostounitario())?>
                                    </td>
                                    <td>
                                        <input type="text" name="productos[<?php echo $detalle->getIdcompradetalle()?>][descuento]" value="<?php echo $detalle->getCompradetalleDescuento()?>"> 
                                    </td>
                                    <td>
                                        <input type="text" name="productos[<?php echo $detalle->getIdcompradetalle()?>][ieps]" value="<?php echo $detalle->getCompradetalleIeps()?>"> 
                                    </td>
                                    <td class="subtotal">
                                        <?php echo money_format('%+#1.6n',$detalle->getCompradetalleSubtotal())?>
                                    </td>
                                    <td>
                                        <?php if($detalle->getCompradetalleRevisada()) :?>
                                            <input checked type="checkbox" name=productos[<?php echo $detalle->getIdcompradetalle()?>][revisada]>
                                        <?php else :?>
                                            <input type="checkbox" name=productos[<?php echo $detalle->getIdcompradetalle()?>][revisada]>
                                        <?php endif?>
                                    </td>
                                    <td>
   
                                        <select class="form-control" name="productos[<?php echo $detalle->getIdcompradetalle()?>][almacen]">
                                            <?php foreach ($almacenes as $key => $value) :?>
                                                <?php if($key == $detalle->getIdalmacen()) :?>
                                                    <option selected value="<?php echo $key?>"><?php echo $value?></option>
                                                <?php else :?>
                                                     <option value="<?php echo $key?>"><?php echo $value?></option>
                                                <?php endif;?>
                                            <?php endforeach; ?>
                                        </select> 
                                    </td>
                                    <td><a href="javascript:;"><i class="fa fa-trash"></i></a></td>
                                </tr>
                                <?php endforeach?>
<!--                                <tr>
                                    <td>Producto 1</td>
                                    <td><input type="text"></td>
                                    <td><input type="text"></td>
                                    <td>$ 100.00</td>
                                    <td><input type="text"></td>
                                    <td><input type="text"></td>
                                    <td>$ 100.00</td>
                                    <td><input type="checkbox"></td>
                                    <td>
                                        <select class="form-control">
                                            <option>almacen 1</option>
                                            <option>almacen 2</option>
                                            <option>almacen 3</option>
                                        </select>
                                    </td>
                                    <td><i class="fa fa-trash"></i></td>
                                </tr>-->
                            </tbody>
                            <tfoot>
                                <tr>
                                    <td colspan="8"></td>
                                    <td>SUBTOTAL</td>
                                    <?php echo $this->formHidden($form->get('compra_subtotal')) ?> 
                                    <td id="subtotal"><?php echo money_format('%+#1.6n',$entity->getCompraSubtotal())?></td>
                                </tr>
                                <tr>
                                    <td colspan="8"></td>
                                    <td>IEPS</td>
                                    <?php echo $this->formHidden($form->get('compra_ieps')) ?> 
                                    <td id="ieps"><?php echo money_format('%+#1.6n',$entity->getCompraIeps())?></td>
                                </tr>
                                <tr>
                                    <td colspan="8"></td>
                                    <td>IVA</td>
                                    <?php echo $this->formHidden($form->get('compra_iva')) ?> 
                                    <td id="iva"><?php echo money_format('%+#1.6n',$entity->getCompraIva())?></td>
                                </tr>
                                <tr>
                                    <td colspan="8"></td>
                                    <td>TOTAL</td>
                                    <?php echo $this->formHidden($form->get('compra_total')) ?> 
                                    <td id="total"><?php echo money_format('%+#1.6n',$entity->getCompraTotal())?></td>
                                </tr>
                            </tfoot>
                        </table>
                         </div>
                    </div>
                </div>
                <div class="form-actions right">
                    <button class="btn blue" type="submit">
                        <i class="fa fa-check"></i>
                        Guardar
                    </button>
                </div>
            </div>
        </div>
    </div>
    <div id="comentarios_container" class="portlet box green" style="border-left-width: 0px; border-bottom-width: 0px; border-right-width: 0px;">
        <div class="portlet-body form">
            <div class="portlet-body form">
                <div class="form-body">
                    <div class="btn-set pull-right">
                        <a id="nota_nuevo" href="javascript:;" class="btn default">Nuevo comentario</a>
                    </div>
                     <h3 class="page-title">Comentarios</h3>
                     <div class="mt-comments">

                     </div>
                </div>
            </div>
        </div>
    </div>
</form>
</div>
<script type="text/javascript" src="/application/custom/js/procesos/consignacion.js"></script>
<script type="text/javascript" src="/application/custom/js/procesos/comentarios.js"></script>
<script>
    var $form = $('#form_container').consignacion({'iva':<?php echo $iva?>});
    $form.edit(<?php echo $anio_activo?>,<?php echo $mes_activo?>,<?php echo json_encode($almacenes)?>,<?php echo $count?>,<?php echo json_encode($entity->getCompraTipo())?>);
</script>
