<link href="/application/global/plugins/datatables/datatables.min.css" rel="stylesheet" type="text/css" />
<link href="/application/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.css" rel="stylesheet" type="text/css" />
<div id="my_container">
    <h3 class="page-title">Consignación</h3>
    <div class="page-bar">
        <ul class="page-breadcrumb">
            <li>
                <a href="javascript:;">Procesos</a>
                 <i class="fa fa-angle-right"></i>
            </li>
            <li>
                <a href="/procesos/consignacion">Consignación</a>
            </li>
        </ul>
    </div>
    <?php foreach ($messages->getSuccessMessages() as $message):?>
        <div class="alert alert-success alert-dismissable">
            <button class="close" aria-hidden="true" data-dismiss="alert" type="button"></button>
            <strong>Éxito!</strong>
            <?php echo $message?>
        </div>
    <?php endforeach;?>
    <div class="portlet box green" style="border-left-width: 0px; border-bottom-width: 0px; border-right-width: 0px;">
        <div class="portlet-body form">
            <div class="form-body">
                <div class="btn-set pull-right">
                    <a href="/procesos/consignacion/nuevoregistro"><button class="btn default" type="button" style="margin-bottom: 15px;">Nuevo registro</button></a>
                </div>
                <table class="table table-striped table-bordered table-hover order-column" id="datatable" style="border-bottom-width: 0px;">
                    <thead>
                        <tr>
                            <th> Fecha </th>
                            <th> Proveedor </th>
                            <th> Total </th>
                            <th> Comprobante </th>
                            <th> Revisada </th>
                            <th> Acciones </th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php $entity = new Compra(); ?>
                        <?php foreach ($collection as $entity) : ?>
                            <?php
                            if($entity->getCompraRevisada()) {
                                $class = 'info';
                                $revisada = 'Revisada';
                            } else {
                                $class = 'danger';
                                $revisada = 'No revisada';
                            }
                            if($entity->getCompraTipo() == 'compra') {
                                $class_compra = 'info';
                                $compra = 'Compra';
                            } else {
                                $class_compra = 'info';
                                $compra = 'Orde de compra';
                            }
                            if(!is_null($entity->getCompraFactura())) {
                                $comprobante = '<a target="_blank" href="'.$entity->getCompraFactura().'"><i class="fa fa-file"></i></a>';
                            } else {
                                $comprobante = 'N/D';
                            }
                            ?>
                            <tr date="<?php echo $entity->getCompraFechacompra('Y/m/d') ?>" id="<?php echo $entity->getIdcompra() ?>">
                                <td><?php echo $entity->getCompraFechacompra('d/m/Y') ?></td>
                                <td><?php echo $entity->getProveedor()->getProveedorNombrecomercial() ?></td>
                                <td><?php echo money_format('%+#1.6n',$entity->getCompraTotal()) ?></td>
                                <td><?php echo $comprobante?></td>
                                <td><span class="label label-sm label-<?php echo $class?>"> <?php echo $revisada ?> </span></td>
                                <td>                                    
                                    <div class="btn-group">
                                        <button class="btn btn-xs green dropdown-toggle" type="button" data-toggle="dropdown" aria-expanded="false"> Acciones
                                            <i class="fa fa-angle-down"></i>
                                        </button>
                                        <ul class="dropdown-menu" role="menu">
                                            <li>
                                                <a href="/procesos/consignacion/editar/<?php echo $entity->getIdcompra()?>">
                                                    <i class="fa fa-pencil"></i> Editar </a>
                                            </li>
                                            <li>
                                                <a href="javascript:;" class="delete_modal">
                                                    <i class="fa fa-trash"></i> Eliminar </a>
                                            </li>
                                        </ul>
                                    </div>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<script src="/application/global/scripts/datatable.js" type="text/javascript"></script>
<script src="/application/global/plugins/datatables/datatables.min.js" type="text/javascript"></script>
<script src="/application/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.js" type="text/javascript"></script>
<script src="/application/custom/js/procesos/consignacion.js" type="text/javascript"></script>	
<script>
    
    var plugin = $('#my_container').consignacion();
    plugin.list(<?php echo $anio_activo?>,<?php echo $mes_activo?>);
</script>