<!DOCTYPE html>
<!-- 
Template Name: Metronic - Responsive Admin Dashboard Template build with Twitter Bootstrap 3.3.6
Version: 4.5.5
Author: KeenThemes
Website: http://www.keenthemes.com/
Contact: support@keenthemes.com
Follow: www.twitter.com/keenthemes
Dribbble: www.dribbble.com/keenthemes
Like: www.facebook.com/keenthemes
Purchase: http://themeforest.net/item/metronic-responsive-admin-dashboard-template/4021469?ref=keenthemes
License: You must have a valid license purchased only from themeforest(the above link) in order to legally use the theme for your project.
-->
<!--[if IE 8]> <html lang="en" class="ie8 no-js"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9 no-js"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en">
    <!--<![endif]-->
    <!-- BEGIN HEAD -->

    <head>
        <meta charset="utf-8" />
        <title>CFCI AERSA | Administrador</title>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <meta content="" name="description" />
        <meta content="OneClick" name="author" />
        
        <!-- BEGIN GLOBAL MANDATORY STYLES -->
        <link href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&subset=all" rel="stylesheet" type="text/css" />
        <link href="/application/global/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
        <link href="/application/global/plugins/simple-line-icons/simple-line-icons.min.css" rel="stylesheet" type="text/css" />
        <link href="/application/global/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
        <link href="/application/global/plugins/uniform/css/uniform.default.css" rel="stylesheet" type="text/css" />
        <link href="/application/global/plugins/bootstrap-switch/css/bootstrap-switch.min.css" rel="stylesheet" type="text/css" />
       <link href="/application//global/plugins/bootstrap-datepicker/css/bootstrap-datepicker3.min.css" rel="stylesheet" type="text/css" />
        
        <!-- END GLOBAL MANDATORY STYLES -->
        <!-- BEGIN PAGE LEVEL PLUGINS -->
        <link href="/application/global/plugins/bootstrap-daterangepicker/daterangepicker.min.css" rel="stylesheet" type="text/css" />
        <link href="/application/global/plugins/morris/morris.css" rel="stylesheet" type="text/css" />
        <link href="/application/global/plugins/fullcalendar/fullcalendar.min.css" rel="stylesheet" type="text/css" />
        <link href="/application/global/plugins/jqvmap/jqvmap/jqvmap.css" rel="stylesheet" type="text/css" />
        <!-- END PAGE LEVEL PLUGINS -->
        <!-- BEGIN THEME GLOBAL STYLES -->
        <link href="/application/global/css/components-md.min.css" rel="stylesheet" id="style_components" type="text/css" />
        <link href="/application/global/css/components.css" rel="stylesheet" id="style_components" type="text/css" />
        <link href="/application/global/css/plugins-md.min.css" rel="stylesheet" type="text/css" />
        <!-- END THEME GLOBAL STYLES -->
        <!-- BEGIN THEME LAYOUT STYLES -->
        <link href="/application/layout2/css/layout.min.css" rel="stylesheet" type="text/css" />
        <link href="/application/layout2/css/themes/blue.min.css" rel="stylesheet" type="text/css" id="style_color" />
        <link href="/application/global/plugins/bootstrap-modal/css/bootstrap-modal-bs3patch.css" rel="stylesheet" type="text/css" />
        <link href="/application/global/plugins/bootstrap-modal/css/bootstrap-modal.css" rel="stylesheet" type="text/css" />
        <link href="/application/global/plugins/typeahead/typeahead.css" rel="stylesheet" type="text/css" />
        
        <!-- END THEME LAYOUT STYLES -->
        <link rel="shortcut icon" href="favicon.ico" /> 
        
        
        <script src="/application/global/plugins/jquery.min.js" type="text/javascript"></script>
        <script src="/application/global/plugins/accounting/accounting.js" type="text/javascript"></script>
        <script src="/application/global/plugins/date.format.min.js" type="text/javascript"></script>
        <script src="/application/global/plugins/numeric/numeric.js" type="text/javascript"></script>
        <script src="/application/global/plugins/bootstrap-datepicker/js/bootstrap-datepicker.js" type="text/javascript"></script>
        <script src="/application/global/plugins/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
        <script src="/application/global/plugins/typeahead/typeahead.bundle.min.js" type="text/javascript"></script>
        <script src="/application/global/plugins/js.cookie.min.js" type="text/javascript"></script>
        <script src="/application/global/plugins/bootstrap-hover-dropdown/bootstrap-hover-dropdown.min.js" type="text/javascript"></script>
        <script src="/application/global/plugins/jquery-slimscroll/jquery.slimscroll.min.js" type="text/javascript"></script>
        <script src="/application/global/plugins/jquery.blockui.min.js" type="text/javascript"></script>
        <script src="/application/global/plugins/uniform/jquery.uniform.js" type="text/javascript"></script>
        <script src="/application/global/plugins/bootstrap-switch/js/bootstrap-switch.min.js" type="text/javascript"></script>
        <!-- END CORE PLUGINS -->
        <!-- BEGIN PAGE LEVEL PLUGINS -->
        <script src="/application/global/plugins/moment.min.js" type="text/javascript"></script>
        <script src="/application/global/plugins/bootstrap-daterangepicker/daterangepicker.min.js" type="text/javascript"></script>
        <script src="/application/global/plugins/morris/morris.min.js" type="text/javascript"></script>
        <script src="/application/global/plugins/morris/raphael-min.js" type="text/javascript"></script>
        <script src="/application/global/plugins/counterup/jquery.waypoints.min.js" type="text/javascript"></script>
        <script src="/application/global/plugins/counterup/jquery.counterup.min.js" type="text/javascript"></script>
        <script src="/application/global/plugins/amcharts/amcharts/amcharts.js" type="text/javascript"></script>
        <script src="/application/global/plugins/amcharts/amcharts/serial.js" type="text/javascript"></script>
        <script src="/application/global/plugins/amcharts/amcharts/pie.js" type="text/javascript"></script>
        <script src="/application/global/plugins/amcharts/amcharts/radar.js" type="text/javascript"></script>
        <script src="/application/global/plugins/amcharts/amcharts/themes/light.js" type="text/javascript"></script>
        <script src="/application/global/plugins/amcharts/amcharts/themes/patterns.js" type="text/javascript"></script>
        <script src="/application/global/plugins/amcharts/amcharts/themes/chalk.js" type="text/javascript"></script>
        <script src="/application/global/plugins/amcharts/ammap/ammap.js" type="text/javascript"></script>
        <script src="/application/global/plugins/amcharts/ammap/maps/js/worldLow.js" type="text/javascript"></script>
        <script src="/application/global/plugins/amcharts/amstockcharts/amstock.js" type="text/javascript"></script>
        <script src="/application/global/plugins/fullcalendar/fullcalendar.min.js" type="text/javascript"></script>
        <script src="/application/global/plugins/flot/jquery.flot.min.js" type="text/javascript"></script>
        <script src="/application/global/plugins/flot/jquery.flot.resize.min.js" type="text/javascript"></script>
        <script src="/application/global/plugins/flot/jquery.flot.categories.min.js" type="text/javascript"></script>
        <script src="/application/global/plugins/jquery-easypiechart/jquery.easypiechart.min.js" type="text/javascript"></script>
        <script src="/application/global/plugins/jquery.sparkline.min.js" type="text/javascript"></script>
        <script src="/application/global/plugins/jqvmap/jqvmap/jquery.vmap.js" type="text/javascript"></script>
        <script src="/application/global/plugins/jqvmap/jqvmap/maps/jquery.vmap.russia.js" type="text/javascript"></script>
        <script src="/application/global/plugins/jqvmap/jqvmap/maps/jquery.vmap.world.js" type="text/javascript"></script>
        <script src="/application/global/plugins/jqvmap/jqvmap/maps/jquery.vmap.europe.js" type="text/javascript"></script>
        <script src="/application/global/plugins/jqvmap/jqvmap/maps/jquery.vmap.germany.js" type="text/javascript"></script>
        <script src="/application/global/plugins/jqvmap/jqvmap/maps/jquery.vmap.usa.js" type="text/javascript"></script>
        <script src="/application/global/plugins/jqvmap/jqvmap/data/jquery.vmap.sampledata.js" type="text/javascript"></script>
        
        <!-- END PAGE LEVEL PLUGINS -->
        <!-- BEGIN THEME GLOBAL SCRIPTS -->
        <script src="/application/global/scripts/app.min.js" type="text/javascript"></script>
        <!-- END THEME GLOBAL SCRIPTS -->
        <!-- BEGIN PAGE LEVEL SCRIPTS -->
        <!-- END PAGE LEVEL SCRIPTS -->
        <!-- BEGIN THEME LAYOUT SCRIPTS -->
        <script src="/application/layout2/scripts/layout.min.js" type="text/javascript"></script>
        <script src="/application/layout2/scripts/demo.min.js" type="text/javascript"></script>
        <script src="/application/layout2/scripts/quick-sidebar.min.js" type="text/javascript"></script>
        <script src="/application/global/plugins/bootstrap-modal/js/bootstrap-modalmanager.js" type="text/javascript"></script>
        <script src="/application/global/plugins/bootstrap-modal/js/bootstrap-modal.js" type="text/javascript"></script>
        
        
    </head>
    <!-- END HEAD -->

    <body class="page-header-fixed page-sidebar-closed-hide-logo page-container-bg-solid page-md">
        <?php 
        
            $session = new Shared\Session\AouthSession(); 
            $session = $session->getData();
        ?>
        <!-- BEGIN HEADER -->
        <div class="page-header navbar navbar-fixed-top">
            <!-- BEGIN HEADER INNER -->
            <div class="page-header-inner ">
                <!-- BEGIN LOGO -->
                <div class="page-logo">
                    <a href="index.html">
                        <img class="logo-default" alt="logo" src="/application/layout2/img/aersa_logo.png" style="width: 135px;"> </a>
                    <div class="menu-toggler sidebar-toggler">
                        <!-- DOC: Remove the above "hide" to enable the sidebar toggler button on header -->
                    </div>
                </div>
                <!-- END LOGO -->
                <!-- BEGIN RESPONSIVE MENU TOGGLER -->
                <a href="javascript:;" class="menu-toggler responsive-toggler" data-toggle="collapse" data-target=".navbar-collapse"> </a>
                <!-- END RESPONSIVE MENU TOGGLER -->
                <!-- BEGIN PAGE ACTIONS -->
                <!-- DOC: Remove "hide" class to enable the page header actions -->
              
                <!-- END PAGE ACTIONS -->
                <!-- BEGIN PAGE TOP -->
                <div class="page-top">
                    <!-- BEGIN HEADER SEARCH BOX -->
                    <!-- DOC: Apply "search-form-expanded" right after the "search-form" class to have half expanded search box -->
                    <form class="search-form search-form-expanded" action="https://www.google.com.mx/search" target="_blank" method="GET">
                        <div class="input-group">
                            <input type="text" class="form-control" placeholder="Buscar en Google..." name="q">
                            <span class="input-group-btn">
                                <a href="javascript:;" class="btn submit">
                                    <i class="icon-magnifier"></i>
                                </a>
                            </span>
                        </div>
                    </form>
                    <!-- END HEADER SEARCH BOX -->
                    <!-- BEGIN TOP NAVIGATION MENU -->
                    <div class="top-menu">
                          <ul class="nav navbar-nav pull-right">
                            <!-- BEGIN NOTIFICATION DROPDOWN -->
                            <!-- DOC: Apply "dropdown-dark" class after below "dropdown-extended" to change the dropdown styte -->
                            <li class="dropdown dropdown-extended dropdown-notification" id="header_notification_bar">
                                <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
                                    <i class="icon-bell"></i>
                                    <span class="badge badge-default"> <?php echo count($session['notifications'])?> </span>
                                </a>
                                <ul class="dropdown-menu">
                                    <li class="external">
                                        <h3>
                                            <span class="bold"><?php echo count($session['notifications']) ?> Notificaciones </span> pendientes
                                        </h3>
                                       
                                    </li>
                                    <li>
                                        <ul class="dropdown-menu-list scroller" style="height: 250px;" data-handle-color="#637283">
                                            <?php foreach ($session['notifications'] as $notification):?>
                                               <?php 
                                                    $proceso_label = ucfirst($notification['notificacion_proceso']);
                                                    
                                                    $url ="/procesos/".$notification['notificacion_proceso']."/editar/".$notification['idproceso'];
                                                    
                                                    if($notification['notificacion_proceso'] == 'credito'){
                                                        $proceso_label = 'Nota de credito';
                                                    }elseif($notification['notificacion_proceso'] == 'ajustesinventarios'){
                                                        $proceso_label = 'Ajustes inventarios';
                                                    }elseif($notification['notificacion_proceso'] == 'cierresemana'){
                                                        $url ="/auditoria/".$notification['notificacion_proceso']."/editar/".$notification['idproceso'];
                                                    }
                                               ?>

                                                <li>
                                                    <a href="<?php echo $url?>">
                                                        <!--<span class="time">10 mins</span>-->
                                                        <span class="details">
                                                        <span class="label label-sm label-icon label-warning">
                                                            <i class="fa fa-bell-o"></i>
                                                        </span>Se ha creado una nueva nota en el proceso de <b><?php echo $proceso_label?></b>  con ID <b><?php echo $notification['idproceso']?></b></span>
                                                    </a>
                                                </li>
                                            <?php endforeach;?>
                                
                                        </ul>
                                    </li>
                                </ul>
                            </li>
                            <!-- END NOTIFICATION DROPDOWN -->
                            <!-- BEGIN INBOX DROPDOWN -->
                            <!-- DOC: Apply "dropdown-dark" class after below "dropdown-extended" to change the dropdown styte -->
                       
                            <!-- END INBOX DROPDOWN -->
                            <!-- BEGIN TODO DROPDOWN -->
                            <!-- DOC: Apply "dropdown-dark" class after below "dropdown-extended" to change the dropdown styte -->
                      
                            <!-- END TODO DROPDOWN -->
                            <!-- BEGIN USER LOGIN DROPDOWN -->
                            <!-- DOC: Apply "dropdown-dark" class after below "dropdown-extended" to change the dropdown styte -->
                            <li class="dropdown dropdown-user">
                                <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
                                    <!-- Empresa -Sucursal -->
                                    <?php 
                                        $txt = '';
                                        if(!is_null($session['idempresa'])){
                                            $empresa = EmpresaQuery::create()->findPk($session['idempresa']);
                                            $txt.=' ('.$empresa->getEmpresaNombrecomercial();
                                        }
                                        if(!is_null($session['idsucursal'])){
                                            $sucursal = SucursalQuery::create()->findPk($session['idsucursal']);
                                            $txt.=' - '.$sucursal->getSucursalNombre();
                                        }
                                        $txt.=')';
                                    ?>
                                    <span class="username username-hide-on-mobile"> <?php echo $session['usuario_nombre'].$txt?> </span>
                                
                                </a>
                            
                            </li>
                            <!-- END USER LOGIN DROPDOWN -->
                            <!-- BEGIN QUICK SIDEBAR TOGGLER -->
                            <!-- DOC: Apply "dropdown-dark" class after below "dropdown-extended" to change the dropdown styte -->
                            <li class="dropdown dropdown-extended quick-sidebar-toggler">
                                <span class="sr-only">Toggle Quick Sidebar</span>
                                <a href="/login/out" style="padding: 0px; color: #C0CDDC; font-size: 18px"><i class="icon-logout"></i></a>
                            </li>
                            <!-- END QUICK SIDEBAR TOGGLER -->
                        </ul>
                    </div>
                    <!-- END TOP NAVIGATION MENU -->
                </div>
                <!-- END PAGE TOP -->
            </div>
            <!-- END HEADER INNER -->
        </div>
        <div class="clearfix"> </div>
        <!-- BEGIN CONTAINER -->
        <div class="page-container">
            <!-- BEGIN SIDEBAR -->
            <div class="page-sidebar-wrapper">
                <!-- DOC: Change data-auto-speed="200" to adjust the sub menu slide up/down speed -->
                <div class="page-sidebar navbar-collapse collapse">
                     <ul class="page-sidebar-menu  page-header-fixed page-sidebar-menu-hover-submenu " data-keep-expanded="false" data-auto-scroll="true" data-slide-speed="200">
                        <li class="nav-item start active open">
                            <a href="/" class="nav-link nav-toggle">
                                <i class="icon-home"></i>
                                <span class="title">Escritorio</span>
                                <span class="selected"></span>
                                <span class="arrow open"></span>
                            </a>
                        </li>
                        <li class="nav-item  ">
                            <a href="javascript:;" class="nav-link nav-toggle">
                                <i class="fa fa-folder-open-o"></i>
                                <span class="title">Catálogos</span>
                                <span class="arrow"></span>
                            </a>
                            <ul class="sub-menu">
                                <li class="nav-item  ">
                                    <a href="/catalogo/almacen" class="nav-link ">
                                        <span class="title">Almacenes</span>
                                    </a>
                                </li>
                                <li class="nav-item  ">
                                    <a href="/catalogo/trabajador_promedio" class="nav-link ">
                                        <span class="title">Trabajadores promedio</span>
                                    </a>
                                </li>
                                <li class="nav-item  ">
                                    <a href="/catalogo/asociacionproductos" class="nav-link ">
                                        <span class="title">Asociación de productos</span>
                                    </a>
                                </li>
                            </ul>
                        </li>
                        <li class="nav-item  ">
                            <a href="javascript:;" class="nav-link nav-toggle">
                                <i class="fa fa-cogs"></i>
                                <span class="title">Procesos</span>
                                <span class="arrow"></span>
                            </a>
                            <ul class="sub-menu">
                                <li class="nav-item  ">
                                    <a href="/procesos/ajustesinventarios" class="nav-link ">
                                        <span class="title">Ajustes inventarios</span>
                                    </a>
                                </li>
                                <li class="nav-item  ">
                                    <a href="/procesos/compra" class="nav-link ">
                                        <span class="title">Compra</span>
                                    </a>
                                </li>
                                <li class="nav-item  ">
                                    <a href="/procesos/requisicion" class="nav-link ">
                                        <span class="title">Requisición</span>
                                    </a>
                                </li>
                                <li class="nav-item  ">
                                    <a href="/procesos/tablajeria" class="nav-link ">
                                        <span class="title">Orden de tablajería</span>
                                    </a>
                                </li>
                                <li class="nav-item  ">
                                    <a href="/procesos/credito" class="nav-link ">
                                        <span class="title">Nota de crédito</span>
                                    </a>
                                </li>
                                <li class="nav-item  ">
                                    <a href="/procesos/devolucion" class="nav-link ">
                                        <span class="title">Devolución de mercancía a proveedores</span>
                                    </a>
                                </li>
                                <li class="nav-item  ">
                                    <a href="/procesos/ingresos" class="nav-link ">
                                        <span class="title">Ingresos</span>
                                    </a>
                                </li>
                                <li class="nav-item  ">
                                    <a href="/procesos/consignacion" class="nav-link ">
                                        <span class="title">Consignación</span>
                                    </a>
                                </li>
                                <li class="nav-item  ">
                                    <a href="/procesos/venta" class="nav-link ">
                                        <span class="title">Ventas</span>
                                    </a>
                                </li>
                            </ul>
                        </li>
                        <li class="nav-item">
                            <a href="javascript:;" class="nav-link nav-toggle">
                                <i class="fa fa-money"></i>
                                <span class="title">Flujo de efectivo</span>
                                <span class="arrow"></span>
                            </a>
                            <ul class="sub-menu">
                                <li class="nav-item  ">
                                    <a href="/flujoefectivo/cuentasporpagar" class="nav-link ">
                                        <span class="title">Cuentas por pagar</span>
                                    </a>
                                </li>
                            </ul>
                        </li>
                        <li class="nav-item  ">
                            <a href="javascript:;" class="nav-link nav-toggle">
                                <i class="fa fa-pie-chart"></i>
                                <span class="title">Reportes</span>
                                <span class="arrow"></span>
                            </a>
                            <ul class="sub-menu">
                                <li class="nav-item  ">
                                    <a href="/reportes/kardex" class="nav-link ">
                                        <span class="title">Kardex de almacén</span>
                                    </a>
                                </li>
                                <li class="nav-item  ">
                                    <a href="/reportes/formatoinventario" class="nav-link ">
                                        <span class="title">Formato de inventario</span>
                                    </a>
                                </li>
                                <li class="nav-item  ">
                                    <a href="/reportes/recetas" class="nav-link ">
                                        <span class="title">Recetas técnicas</span>
                                    </a>
                                </li>
                                <li class="nav-item  ">
                                    <a href="/reportes/variacioncostos" class="nav-link ">
                                        <span class="title">Variación de los costos</span>
                                    </a>
                                </li>
                                <li class="nav-item  ">
                                    <a href="/reportes/informeacumulados" class="nav-link ">
                                        <span class="title">Informe acumulado</span>
                                    </a>
                                </li>
                                <li class="nav-item  ">
                                    <a href="/reportes/entradasporcompras" class="nav-link ">
                                        <span class="title">Relación de entradas por compras</span>
                                    </a>
                                </li>
                            </ul>
                            
                        </li>
                        <li class="nav-item  ">
                            <a href="javascript:;" class="nav-link nav-toggle">
                                    <i class="fa fa-gavel"></i>
                                <span class="title">Auditoría</span>
                                <span class="arrow"></span>
                            </a>
                            <ul class="sub-menu">
                                <li class="nav-item  ">
                                    <a href="/auditoria/cierresemana" class="nav-link ">
                                        <span class="title">Inventario de cierre semana</span>
                                    </a>
                                </li>
                                <li class="nav-item  ">
                                    <a href="/auditoria/inventariociclico" class="nav-link ">
                                        <span class="title">⁠⁠⁠Inventario  cíclico</span>
                                    </a>
                                </li>
                            </ul>
                        </li>
                         <li class="nav-item  ">
                            <a href="javascript:;" class="nav-link nav-toggle">
                                <i class="fa fa-black-tie"></i>
                                <span class="title">Administración</span>
                                <span class="arrow"></span>
                            </a>
                            <ul class="sub-menu">
                                <li class="nav-item  ">
                                    <a href="/administracion/configuracion" class="nav-link ">
                                        <span class="title">Configuración</span>
                                    </a>
                                </li>
                                <li class="nav-item  ">
                                    <a href="/administracion/actualizacion" class="nav-link ">
                                        <span class="title">Actualización de productos masiva</span>
                                    </a>
                                </li>
                                <li class="nav-item  ">
                                    <a href="/administracion/revision" class="nav-link ">
                                        <span class="title">Revisión</span>
                                    </a>
                                    <ul class="sub-menu">
                                        <li class="nav-item  ">
                                            <a href="/administracion/revision/compras" class="nav-link ">
                                                <span class="title">Compras</span>
                                            </a>
                                        </li>
                                        <li class="nav-item  ">
                                            <a href="/administracion/revision/requisicion" class="nav-link ">
                                                <span class="title">Requisiciones</span>
                                            </a>
                                        </li>
                                        <li class="nav-item  ">
                                            <a href="/administracion/revision/tablajeria" class="nav-link ">
                                                <span class="title">Órdenes de tablajería</span>
                                            </a>
                                        </li>
                                        <li class="nav-item  ">
                                            <a href="/administracion/revision/credito" class="nav-link ">
                                                <span class="title">Notas de crédito</span>
                                            </a>
                                        </li>
                                        <li class="nav-item  ">
                                            <a href="/administracion/revision/devolucion" class="nav-link ">
                                                <span class="title">Devoluciones</span>
                                            </a>
                                        </li>
                                        <li class="nav-item  ">
                                            <a href="/administracion/revision/ventas" class="nav-link ">
                                                <span class="title">Ventas</span>
                                            </a>
                                        </li>
                                        <li class="nav-item  ">
                                            <a href="/administracion/revision/inventario" class="nav-link ">
                                                <span class="title">Inventario físico afectable</span>
                                            </a>
                                        </li>
                                        <li class="nav-item  ">
                                            <a href="/administracion/revision/ingresos" class="nav-link ">
                                                <span class="title">Ingresos</span>
                                            </a>
                                        </li>
                                    </ul>
                                </li>
                                <li class="nav-item  ">
                                    <a href="/administracion/reportes" class="nav-link ">
                                        <span class="title">Reportes</span>
                                    </a>
                                    <ul class="sub-menu">
                                        <li class="nav-item  ">
                                            <a href="/administracion/reportes/monitoreotablajeria" class="nav-link ">
                                                <span class="title">Monitoreo de tablajería</span>
                                            </a>
                                        </li>
                                        <li class="nav-item  ">
                                            <a href="/administracion/reportes/estadisticosanuales" class="nav-link ">
                                                <span class="title">Comparativo estadístico anual</span>
                                            </a>
                                        </li>
                                        <li class="nav-item  ">
                                            <a href="/administracion/reportes/estadisticosmensuales" class="nav-link ">
                                                <span class="title">Comparativo estadístico mensual</span>
                                            </a>
                                        </li>
                                        <li class="nav-item  ">
                                            <a href="/administracion/reportes/cierresinventarios" class="nav-link ">
                                                <span class="title">Cierre de mes</span>
                                            </a>
                                        </li>
                                        <li class="nav-item  ">
                                            <a href="/administracion/reportes/stock" class="nav-link ">
                                                <span class="title">Stock</span>
                                            </a>
                                        </li>
                                        <li class="nav-item  ">
                                            <a href="/administracion/reportes/analisis" class="nav-link ">
                                                <span class="title">Análisis histórico de gastos variables</span>
                                            </a>
                                        </li>
                                    </ul>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="page-content-wrapper">
                <div class="page-content">
                    <?php echo $this->content?>
                </div>
            </div>
        </div>
    </body>
</html>