<!DOCTYPE html>
<!-- 
Template Name: Metronic - Responsive Admin Dashboard Template build with Twitter Bootstrap 3.3.6
Version: 4.5.5
Author: KeenThemes
Website: http://www.keenthemes.com/
Contact: support@keenthemes.com
Follow: www.twitter.com/keenthemes
Dribbble: www.dribbble.com/keenthemes
Like: www.facebook.com/keenthemes
Purchase: http://themeforest.net/item/metronic-responsive-admin-dashboard-template/4021469?ref=keenthemes
License: You must have a valid license purchased only from themeforest(the above link) in order to legally use the theme for your project.
-->
<!--[if IE 8]> <html lang="en" class="ie8 no-js"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9 no-js"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en">
    <!--<![endif]-->
    <!-- BEGIN HEAD -->

    <head>
        <meta charset="utf-8" />
        <title>CFCI AERSA | Administrador</title>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <meta content="" name="description" />
        <meta content="OneClick" name="author" />
        
        <!-- BEGIN GLOBAL MANDATORY STYLES -->
        <link href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&subset=all" rel="stylesheet" type="text/css" />
        <link href="/application/global/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
        <link href="/application/global/plugins/simple-line-icons/simple-line-icons.min.css" rel="stylesheet" type="text/css" />
        <link href="/application/global/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
        <link href="/application/global/plugins/uniform/css/uniform.default.css" rel="stylesheet" type="text/css" />
        <link href="/application/global/plugins/bootstrap-switch/css/bootstrap-switch.min.css" rel="stylesheet" type="text/css" />
        
        <!-- END GLOBAL MANDATORY STYLES -->
        <!-- BEGIN PAGE LEVEL PLUGINS -->
        <link href="/application/global/plugins/bootstrap-daterangepicker/daterangepicker.min.css" rel="stylesheet" type="text/css" />
        <link href="/application/global/plugins/morris/morris.css" rel="stylesheet" type="text/css" />
        <link href="/application/global/plugins/fullcalendar/fullcalendar.min.css" rel="stylesheet" type="text/css" />
        <link href="/application/global/plugins/jqvmap/jqvmap/jqvmap.css" rel="stylesheet" type="text/css" />
        <!-- END PAGE LEVEL PLUGINS -->
        <!-- BEGIN THEME GLOBAL STYLES -->
        <link href="/application/global/css/components-md.min.css" rel="stylesheet" id="style_components" type="text/css" />
        <link href="/application/global/css/plugins-md.min.css" rel="stylesheet" type="text/css" />
        <!-- END THEME GLOBAL STYLES -->
        <!-- BEGIN THEME LAYOUT STYLES -->
        <link href="/application/layout2/css/layout.min.css" rel="stylesheet" type="text/css" />
        <link href="/application/layout2/css/themes/blue.min.css" rel="stylesheet" type="text/css" id="style_color" />
        <link href="/application/global/plugins/bootstrap-modal/css/bootstrap-modal-bs3patch.css" rel="stylesheet" type="text/css" />
        <link href="/application/global/plugins/bootstrap-modal/css/bootstrap-modal.css" rel="stylesheet" type="text/css" />
        
        
        <!-- END THEME LAYOUT STYLES -->
        <link rel="shortcut icon" href="favicon.ico" /> 
        
        
        <script src="/application/global/plugins/jquery.min.js" type="text/javascript"></script>
        <script src="/application/global/plugins/accounting/accounting.js" type="text/javascript"></script>
        <script src="/application/global/plugins/date.format.min.js" type="text/javascript"></script>
        <script src="/application/global/plugins/numeric/numeric.js" type="text/javascript"></script>
        <script src="/application/global/plugins/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
        <script src="/application/global/plugins/js.cookie.min.js" type="text/javascript"></script>
        <script src="/application/global/plugins/bootstrap-hover-dropdown/bootstrap-hover-dropdown.min.js" type="text/javascript"></script>
        <script src="/application/global/plugins/jquery-slimscroll/jquery.slimscroll.min.js" type="text/javascript"></script>
        <script src="/application/global/plugins/jquery.blockui.min.js" type="text/javascript"></script>
        <script src="/application/global/plugins/uniform/jquery.uniform.min.js" type="text/javascript"></script>
        <script src="/application/global/plugins/bootstrap-switch/js/bootstrap-switch.min.js" type="text/javascript"></script>
        <!-- END CORE PLUGINS -->
        <!-- BEGIN PAGE LEVEL PLUGINS -->
        <script src="/application/global/plugins/moment.min.js" type="text/javascript"></script>
        <script src="/application/global/plugins/bootstrap-daterangepicker/daterangepicker.min.js" type="text/javascript"></script>
        <script src="/application/global/plugins/morris/morris.min.js" type="text/javascript"></script>
        <script src="/application/global/plugins/morris/raphael-min.js" type="text/javascript"></script>
        <script src="/application/global/plugins/counterup/jquery.waypoints.min.js" type="text/javascript"></script>
        <script src="/application/global/plugins/counterup/jquery.counterup.min.js" type="text/javascript"></script>
        <script src="/application/global/plugins/amcharts/amcharts/amcharts.js" type="text/javascript"></script>
        <script src="/application/global/plugins/amcharts/amcharts/serial.js" type="text/javascript"></script>
        <script src="/application/global/plugins/amcharts/amcharts/pie.js" type="text/javascript"></script>
        <script src="/application/global/plugins/amcharts/amcharts/radar.js" type="text/javascript"></script>
        <script src="/application/global/plugins/amcharts/amcharts/themes/light.js" type="text/javascript"></script>
        <script src="/application/global/plugins/amcharts/amcharts/themes/patterns.js" type="text/javascript"></script>
        <script src="/application/global/plugins/amcharts/amcharts/themes/chalk.js" type="text/javascript"></script>
        <script src="/application/global/plugins/amcharts/ammap/ammap.js" type="text/javascript"></script>
        <script src="/application/global/plugins/amcharts/ammap/maps/js/worldLow.js" type="text/javascript"></script>
        <script src="/application/global/plugins/amcharts/amstockcharts/amstock.js" type="text/javascript"></script>
        <script src="/application/global/plugins/fullcalendar/fullcalendar.min.js" type="text/javascript"></script>
        <script src="/application/global/plugins/flot/jquery.flot.min.js" type="text/javascript"></script>
        <script src="/application/global/plugins/flot/jquery.flot.resize.min.js" type="text/javascript"></script>
        <script src="/application/global/plugins/flot/jquery.flot.categories.min.js" type="text/javascript"></script>
        <script src="/application/global/plugins/jquery-easypiechart/jquery.easypiechart.min.js" type="text/javascript"></script>
        <script src="/application/global/plugins/jquery.sparkline.min.js" type="text/javascript"></script>
        <script src="/application/global/plugins/jqvmap/jqvmap/jquery.vmap.js" type="text/javascript"></script>
        <script src="/application/global/plugins/jqvmap/jqvmap/maps/jquery.vmap.russia.js" type="text/javascript"></script>
        <script src="/application/global/plugins/jqvmap/jqvmap/maps/jquery.vmap.world.js" type="text/javascript"></script>
        <script src="/application/global/plugins/jqvmap/jqvmap/maps/jquery.vmap.europe.js" type="text/javascript"></script>
        <script src="/application/global/plugins/jqvmap/jqvmap/maps/jquery.vmap.germany.js" type="text/javascript"></script>
        <script src="/application/global/plugins/jqvmap/jqvmap/maps/jquery.vmap.usa.js" type="text/javascript"></script>
        <script src="/application/global/plugins/jqvmap/jqvmap/data/jquery.vmap.sampledata.js" type="text/javascript"></script>
        
        <!-- END PAGE LEVEL PLUGINS -->
        <!-- BEGIN THEME GLOBAL SCRIPTS -->
        <script src="/application/global/scripts/app.min.js" type="text/javascript"></script>
        <!-- END THEME GLOBAL SCRIPTS -->
        <!-- BEGIN PAGE LEVEL SCRIPTS -->
        <!-- END PAGE LEVEL SCRIPTS -->
        <!-- BEGIN THEME LAYOUT SCRIPTS -->
        <script src="/application/layout2/scripts/layout.min.js" type="text/javascript"></script>
        <script src="/application/layout2/scripts/demo.min.js" type="text/javascript"></script>
        <script src="/application/layout2/scripts/quick-sidebar.min.js" type="text/javascript"></script>
        <script src="/application/global/plugins/bootstrap-modal/js/bootstrap-modalmanager.js" type="text/javascript"></script>
        <script src="/application/global/plugins/bootstrap-modal/js/bootstrap-modal.js" type="text/javascript"></script>
        
        
    </head>
    <!-- END HEAD -->

    <body class="page-header-fixed page-sidebar-closed-hide-logo page-container-bg-solid page-md">
        <?php 
        
            $session = new Shared\Session\AouthSession(); 
            $session = $session->getData();
        ?>
        <!-- BEGIN HEADER -->
        <div class="page-header navbar navbar-fixed-top">
            <!-- BEGIN HEADER INNER -->
            <div class="page-header-inner ">
                <!-- BEGIN LOGO -->
                <div class="page-logo">
                    <a href="index.html">
                        <img class="logo-default" alt="logo" src="/application/layout2/img/aersa_logo.png" style="width: 135px;"> </a>
                    <div class="menu-toggler sidebar-toggler">
                        <!-- DOC: Remove the above "hide" to enable the sidebar toggler button on header -->
                    </div>
                </div>
                <!-- END LOGO -->
                <!-- BEGIN RESPONSIVE MENU TOGGLER -->
                <a href="javascript:;" class="menu-toggler responsive-toggler" data-toggle="collapse" data-target=".navbar-collapse"> </a>
                <!-- END RESPONSIVE MENU TOGGLER -->
                <!-- BEGIN PAGE ACTIONS -->
                <!-- DOC: Remove "hide" class to enable the page header actions -->
  
                <!-- END PAGE ACTIONS -->
                <!-- BEGIN PAGE TOP -->
                <div class="page-top">
                    <!-- BEGIN HEADER SEARCH BOX -->
                    <!-- DOC: Apply "search-form-expanded" right after the "search-form" class to have half expanded search box -->
                    <form class="search-form search-form-expanded" action="https://www.google.com.mx/search" target="_blank" method="GET">
                        <div class="input-group">
                            <input type="text" class="form-control" placeholder="Buscar en Google..." name="q">
                            <span class="input-group-btn">
                                <a href="javascript:;" class="btn submit">
                                    <i class="icon-magnifier"></i>
                                </a>
                            </span>
                        </div>
                    </form>
                    <!-- END HEADER SEARCH BOX -->
                    <!-- BEGIN TOP NAVIGATION MENU -->
                    <div class="top-menu">
                        <ul class="nav navbar-nav pull-right">
                            <!-- BEGIN NOTIFICATION DROPDOWN -->
                            <!-- DOC: Apply "dropdown-dark" class after below "dropdown-extended" to change the dropdown styte -->
                 
                            <!-- END NOTIFICATION DROPDOWN -->
                            <!-- BEGIN INBOX DROPDOWN -->
                            <!-- DOC: Apply "dropdown-dark" class after below "dropdown-extended" to change the dropdown styte -->
                            <!-- END INBOX DROPDOWN -->
                            <!-- BEGIN TODO DROPDOWN -->
                            <!-- DOC: Apply "dropdown-dark" class after below "dropdown-extended" to change the dropdown styte -->
                          
                            <!-- END TODO DROPDOWN -->
                            <!-- BEGIN USER LOGIN DROPDOWN -->
                            <!-- DOC: Apply "dropdown-dark" class after below "dropdown-extended" to change the dropdown styte -->
                            <li class="dropdown dropdown-user">
                                <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
                                    <!-- Empresa -Sucursal -->
                                    <?php 
                                        $txt = '';
                                        if(!is_null($session['idempresa'])){
                                            $empresa = EmpresaQuery::create()->findPk($session['idempresa']);
                                            $txt.=' ('.$empresa->getEmpresaNombrecomercial();
                                        }
                                        if(!is_null($session['idsucursal'])){
                                            $sucursal = SucursalQuery::create()->findPk($session['idsucursal']);
                                           $txt.=' - '.$sucursal->getSucursalNombre();
                                        }
                                        $txt.=')';
                                    ?>
                                    <span class="username username-hide-on-mobile"> <?php echo $session['usuario_nombre'].$txt?> </span>
                                    <i class="fa fa-angle-down"></i>
                                </a>
                                <ul class="dropdown-menu dropdown-menu-default">
                                    <li>
                                        <a href="page_user_profile_1.html">
                                            <i class="icon-user"></i> My Profile </a>
                                    </li>
                                    <li>
                                        <a href="app_calendar.html">
                                            <i class="icon-calendar"></i> My Calendar </a>
                                    </li>
                                    <li>
                                        <a href="app_inbox.html">
                                            <i class="icon-envelope-open"></i> My Inbox
                                            <span class="badge badge-danger"> 3 </span>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="app_todo_2.html">
                                            <i class="icon-rocket"></i> My Tasks
                                            <span class="badge badge-success"> 7 </span>
                                        </a>
                                    </li>
                                    <li class="divider"> </li>
                                    <li>
                                        <a href="page_user_lock_1.html">
                                            <i class="icon-lock"></i> Lock Screen </a>
                                    </li>
                                    <li>
                                        <a href="page_user_login_1.html">
                                            <i class="icon-key"></i> Log Out </a>
                                    </li>
                                </ul>
                            </li>
                            <!-- END USER LOGIN DROPDOWN -->
                            <!-- BEGIN QUICK SIDEBAR TOGGLER -->
                            <!-- DOC: Apply "dropdown-dark" class after below "dropdown-extended" to change the dropdown styte -->
                            <li class="dropdown dropdown-extended quick-sidebar-toggler">
                                <span class="sr-only">Toggle Quick Sidebar</span>
                                <a href="/login/out" style="padding: 0px; color: #C0CDDC; font-size: 18px"><i class="icon-logout"></i></a>
                            </li>
                            <!-- END QUICK SIDEBAR TOGGLER -->
                        </ul>
                    </div>
                    <!-- END TOP NAVIGATION MENU -->
                </div>
                <!-- END PAGE TOP -->
            </div>
            <!-- END HEADER INNER -->
        </div>
        <div class="clearfix"> </div>
        <!-- BEGIN CONTAINER -->
        <div class="page-container">
            <!-- BEGIN SIDEBAR -->
            <div class="page-sidebar-wrapper">
                <!-- DOC: Change data-auto-speed="200" to adjust the sub menu slide up/down speed -->
                <div class="page-sidebar navbar-collapse collapse">
                     <ul class="page-sidebar-menu  page-header-fixed page-sidebar-menu-hover-submenu " data-keep-expanded="false" data-auto-scroll="true" data-slide-speed="200">
                        <li class="nav-item start active open">
                            <a href="/" class="nav-link nav-toggle">
                                <i class="icon-home"></i>
                                <span class="title">Escritorio</span>
                                <span class="selected"></span>
                                <span class="arrow open"></span>
                            </a>
                        </li>
                        <li class="nav-item  ">
                            <a href="javascript:;" class="nav-link nav-toggle">
                                <i class="fa fa-folder-open-o"></i>
                                <span class="title">Catálogos</span>
                                <span class="arrow"></span>
                            </a>
                            <ul class="sub-menu">
                                <li class="nav-item  ">
                                    <a href="/catalogo/usuario" class="nav-link ">
                                        <span class="title">Usuarios</span>
                                    </a>
                                </li>
                                <li class="nav-item  ">
                                    <a href="/catalogo/empresa" class="nav-link ">
                                        <span class="title">Empresas</span>
                                    </a>
                                </li>
                                <li class="nav-item  ">
                                    <a href="/catalogo/categoria" class="nav-link ">
                                        <span class="title">Categorías de productos</span>
                                    </a>
                                </li>
                                <li class="nav-item  ">
                                    <a href="/catalogo/iva" class="nav-link ">
                                        <span class="title">Tasa de IVA </span>
                                    </a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="page-content-wrapper">
                <div class="page-content">
                    <?php echo $this->content?>
                </div>
            </div>
        </div>
    </body>
</html>