<style>
    input[type=file]{
        padding-top: 0px;
        padding-left: 0px;
    }
    #productos_table .fa-trash{
        color:red;
    }
</style>
<link rel="stylesheet" type="text/css" href="/application/custom/css/validaciones.css">
<div class="page-bar">
        <ul class="page-breadcrumb">
            <li>
                <a href="javascript:;">Procesos</a>
                 <i class="fa fa-angle-right"></i>
            </li>
            <li>
                <a href="/procesos/ingresos">Ingresos</a>
                 <i class="fa fa-angle-right"></i>
            </li>
            <li>
                <a href="/procesos/ingresos/nuevo">Registro</a>
            </li>
        </ul>
</div>
<div id="form_container">
    <form class="form-horizontal" action="/procesos/ingresos/editar/<?php echo $entity->getIdingreso()?>" method="post" enctype="multipart/form-data">
    <div class="portlet box green" style="border-left-width: 0px; border-bottom-width: 0px; border-right-width: 0px;">
        <div class="portlet-body form">
            <div class="form-body">
                <h3 class="page-title">Ingresos - Registro</h3><br><br>
                <div class="row">
                    <div class="form-group">
                        <div class="col-md-6">
                            <?php echo $this->formLabel($form->get('ingreso_fecha')) ?>  
                            <?php echo $this->formText($form->get('ingreso_fecha')) ?>
                            <?php echo $this->formHidden($form->get('ingreso_fechacreacion')) ?>
                        </div>

                    </div>
                </div>
                <div class="row">
                    <div class="form-group">
                        <div class="col-md-6">
                            <?php echo $this->formLabel($form->get('ingreso_folio')) ?>  
                            <?php echo $this->formText($form->get('ingreso_folio')) ?> 
                        </div>
                        <div class="col-md-6">
                            <?php echo $this->formLabel($form->get('ingreso_revisada')) ?>  
                            <?php echo $this->formSelect($form->get('ingreso_revisada')) ?> 
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <?php $rubro = new Rubroingreso() ?>
    <?php foreach ($rubros as $rubro) :?>
    <div class="portlet box green" style="border-left-width: 0px; border-bottom-width: 0px; border-right-width: 0px;">
        <div class="portlet-body form">
            <div class="form-body">
                <h3 class="page-title"><?php echo $rubro->getRubroingresoNombre()?></h3><br><br>
                <table class="table" id="<?php echo strtolower($rubro->getRubroingresoNombre())?>">
                    <thead>
                        <th>Conceptos</th>
                        <th>Subtotal</th>
                        <th>IVA</th>
                        <th>Total</th>
                        <th>Revisada</th>
                    </thead>
                    <tbody>
                        <?php $concepto = new Conceptoingreso();?>
                        <?php foreach ($concepto_ingresos as $concepto) :?>
                        <tr>
                            <input type="hidden" name="ingresodetalle[<?php echo $rubro->getIdrubroingreso()?>][<?php echo $concepto->getIdconceptoingreso()?>][subtotal]" value="<?php echo $detalles[$rubro->getIdrubroingreso()][$concepto->getIdconceptoingreso()]['IngresodetalleSub']?>">
                            <input type="hidden" name="ingresodetalle[<?php echo $rubro->getIdrubroingreso()?>][<?php echo $concepto->getIdconceptoingreso()?>][iva]" value="<?php echo $detalles[$rubro->getIdrubroingreso()][$concepto->getIdconceptoingreso()]['IngresodetalleIva']?>">
                            <td><?php echo $concepto->getConceptoingresoNombre()?></td>
                            <td><?php echo money_format('%(#10n',$detalles[$rubro->getIdrubroingreso()][$concepto->getIdconceptoingreso()]['IngresodetalleSub']) ?></td>
                             <td><?php echo money_format('%(#10n',$detalles[$rubro->getIdrubroingreso()][$concepto->getIdconceptoingreso()]['IngresodetalleIva']) ?></td>
                            <td><input name="ingresodetalle[<?php echo $rubro->getIdrubroingreso()?>][<?php echo $concepto->getIdconceptoingreso()?>][total]" type="text" class="form-control" value="<?php echo $detalles[$rubro->getIdrubroingreso()][$concepto->getIdconceptoingreso()]['IngresodetalleTotal']?>"></td>
                            <?php if($detalles[$rubro->getIdrubroingreso()][$concepto->getIdconceptoingreso()]['IngresodetalleRevisada']) :?>
                                <td><input name="ingresodetalle[<?php echo $rubro->getIdrubroingreso()?>][<?php echo $concepto->getIdconceptoingreso()?>][revisada]" type="checkbox" checked></td>
                            <?php else :?>
                                <td><input name="ingresodetalle[<?php echo $rubro->getIdrubroingreso()?>][<?php echo $concepto->getIdconceptoingreso()?>][revisada]" type="checkbox"></td>
                            <?php endif;?>
                        </tr>
                        <?php endforeach;?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <?php endforeach;?>
        
    <div class="portlet box green" style="border-left-width: 0px; border-bottom-width: 0px; border-right-width: 0px;">
        <div class="portlet-body form">
            <div class="form-body">
                <div class="row">
                    <div class="col-md-4">
                        <div class="form-group">
                            <label class="control-label col-md-5">Total bebidas: </label>
                            <div class="col-md-7">
                                <input type="hidden" name="ingreso_totalbebida" value="<?php echo $entity->getIngresoTotalbebida() ?>">
                                <p id="total_bebidas" class="form-control-static"><?php echo money_format('%(#10n',$entity->getIngresoTotalbebida()) ?></p>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group">
                            <label class="control-label col-md-5">Total alimentos: </label>
                            <div class="col-md-7">
                                <input type="hidden" name="ingreso_totalalimento" value="<?php echo $entity->getIngresoTotalalimento() ?>">
                                <p id="total_alimentos" class="form-control-static"><?php echo money_format('%(#10n',$entity->getIngresoTotalalimento()) ?></p>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group">
                            <label class="control-label col-md-5">Total miscelanea: </label>
                            <div class="col-md-7">
                                 <input type="hidden" name="ingreso_totalmiscelanea" value="<?php echo $entity->getIngresoTotalmiscelanea() ?>">
                                 <p id="total_miscelanea" class="form-control-static"><?php echo money_format('%(#10n',$entity->getIngresoTotalmiscelanea()) ?></p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="form-actions right">
                    <button class="btn blue" type="submit">
                        <i class="fa fa-check"></i>
                        Guardar
                    </button>
                </div>
        </div>
        
    </div>
</form>
</div>
<script type="text/javascript" src="/application/custom/js/procesos/ingresos.js"></script>
<script>
    var $form = $('#form_container').ingresos({'iva':<?php echo $iva?>});
    $form.edit(<?php echo $anio_activo?>,<?php echo $mes_activo?>);
</script>
