<style>
    input[type=file]{
        padding-top: 0px;
        padding-left: 0px;
    }
    #productos_table .fa-trash{
        color:red;
    }
</style>
<link rel="stylesheet" type="text/css" href="/application/custom/css/validaciones.css">
<h3 class="page-title"><?php echo $form->get('plantillatablajeria_nombre')->getValue() ?></h3>
<div class="page-bar">
    <ul class="page-breadcrumb">
        <li>
            <a href="/catalogo/tablajeria">Tablajerias</a>
            <i class="fa fa-angle-right"></i>
        </li>
        <li>
            <span><span><?php echo $form->get('plantillatablajeria_nombre')->getValue() ?></span></span>
        </li>
    </ul>
</div>
<div id="form_container">
<?php foreach ($messages->getSuccessMessages() as $message): ?>
    <div class="alert alert-success alert-dismissable">
        <button class="close" aria-hidden="true" data-dismiss="alert" type="button"></button>
        <strong>Ã‰xito!</strong>
        <?php echo $message ?>
    </div>
<?php endforeach; ?>

<?php foreach ($messages->getErrorMessages() as $message): ?>
    <div class="alert alert-danger alert-dismissable">
        <button class="close" aria-hidden="true" data-dismiss="alert" type="button"></button>
        <strong>Error!</strong>
        <?php echo $message ?>

    </div>
<?php endforeach; ?>
<form class="form-horizontal" action="/catalogo/tablajeria/editar/<?php echo $form->get('idplantillatablajeria')->getValue()?>" method="post" enctype="multipart/form-data">
<div class="portlet box green" style="border-left-width: 0px; border-bottom-width: 0px; border-right-width: 0px;">
    <div class="portlet-body form">
        <div class="form-body">
            <h3 class="form-section">Información general</h3>
            <div class="row">
                <?php echo $this->formHidden($form->get('idempresa')); ?>
                <div class="col-md-6">
                    <?php echo $this->formLabel($form->get('plantillatablajeria_nombre')); ?>  
                    <?php echo $this->formText($form->get('plantillatablajeria_nombre')); ?>
                </div>
                <div class="col-md-6">
                    <?php echo $this->formHidden($form->get('idproducto')); ?>  
                    <?php echo $this->formLabel($form->get('idproducto_autocomplete')); ?>  
                    <div class="input-group">
                        <span class="input-group-addon">
                            <i class="fa fa-search"></i>
                        </span>
                        <?php echo $this->formText($form->get('idproducto_autocomplete')); ?>  

                    </div>

                </div>
                <div class="col-md-12">
                    <?php echo $this->formLabel($form->get('plantillatablajeria_descripcion')) ?>  
                    <?php echo $this->formTextarea($form->get('plantillatablajeria_descripcion')) ?>
                </div>
            </div>
            <br>
            <div class="row">
                <div class="col-md-12">
                    <p>(*)Campos obligatorios</p>
                </div>
            </div>
            <h3 class="page-title">Productos</h3><br><br>
            <div class="row">
                <div class="form-group">
                    <div class="col-md-5 col-md-offset-5">
                        <div class="input-group">
                            <span class="input-group-addon">
                                <i class="fa fa-search"></i>
                            </span>
                            <input id="idproducto" class="form-control" type="hidden">
                            <input id="producto_autocomplete" class="form-control" type="text">
                        </div>
                    </div>
                    <div class="col-md-1" style="text-align: right">
                        <button disabled id="producto_add" class="btn grey-mint" type="button">Agregar</button>
                    </div>
                </div>
            </div>
            <div class="row">
                <table class="table" id="productos_table">
                    <thead>
                    <th>Nombre</th>
                    <th>Opción</th>
                    </thead>
                    <tbody>
                        <?php $detalle = new Plantillatablajeriadetalle() ?>
                        <?php foreach ($plantillatablajeria_detalle as $detalle) : ?>
                        <tr id="<?php echo $detalle->getIdplantillatablajeriadetalle() ?>">
                                <td>
                                <input type="hidden" name="plantillatablajeria_detalle[<?php echo $detalle->getIdproducto() ?>][idproducto]" value="<?php echo $detalle->getIdproducto() ?>">
                                    <?php echo $detalle->getProducto()->getProductoNombre() ?>
                                </td>
                                <td><a href="javascript:;"><i class="fa fa-trash"></i></a></td>
                            </tr>
                        <?php endforeach ?>
                    </tbody>
                </table>
            </div>
        </div>
        <div class="form-actions right">
            <button class="btn blue" type="submit" id="plantilla_save">
                <i class="fa fa-check" ></i>
                Guardar
            </button>
        </div>
    </div>
</div>
</form>
</div>
<script type="text/javascript" src="/application/custom/js/catalogo/tablajeria.js"></script>
<script>
    var $form = $('#form_container').tablajeria();
    $form.edit(<?php echo $count?>);
</script>