

<div class="row bg-contacto">
  <div class="col-lg-5 col-lg-offset-6 col-md-6 col-md-offset-6 col-sm-8 col-sm-offset-2 white">
    <h1>¿En que podemos ayudarte?</h1>
    <p>
      Dejanos tus datos y alguno de nuestros asesores se comunicara contigo a la brevedad
    </p>
    <form class="" action="index.html" method="post">
      <div class="form-groupb">
        <div class="row">
          <div class="col-lg-6">
            <label for="">Nombre</label>
            <input type="text" name="" class="form-control" value="">
          </div>
          <div class="col-lg-6">
            <label for="">Telefono</label>
            <input type="text" name="" class="form-control" value="">
          </div>
        </div>
      </div>
      <div class="form-group">
        <div class="row">
          <div class="col-lg-12">
            <label for=""><br>Correo electronico</label>
            <input type="text" name="" class="form-control" value="">
          </div>
        </div>
      </div>
      <div class="form-group" style="margin-top: -25px;">
        <div class="row">
          <div class="col-lg-12">
            <label for=""><br>Mensaje</label>
            <textarea name="" class="form-control" rows="4" cols="40"></textarea>
          </div>
        </div>
      </div>
        <button type="button" class="btn btn-success col-xs-12 btn-submit" name="" style="margin-bottom: 8px"> Enviar </button>
 
    </form>
  </div>

  <div class="col-xs-12 no-bot">
    <div class="row" onClick="style.pointerEvents='none'">
    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3733.387447913683!2d-103.41560998453117!3d20.65381038620258!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x8428ac2f263fec91%3A0x6898c0354e220bf2!2sTulum+4234%2C+El+Zapote%2C+45050+Zapopan%2C+Jal.!5e0!3m2!1ses!2smx!4v1468707824068"
    width="100%" height="450" frameborder="0" scrolling="false" style="border:0" allowfullscreen></iframe>
    </div>
  </div>
</div>
