
<?php $indexRespuesta = 0; ?>

<div class="row bot">
		<img src="/website/img/banners/diagnosticov2.jpg" alt="" class="img-responsive img-index" />
</div>

<div class="row">
  <div class="container">
    <form  class="form-horizontal" id="formDiagnostico" method="post" action="">

      <div class="col-lg-12 col-md-12">
          <button style="text-height: 10"class="btn col-xs-12 text-left panel-green btn-panel" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample" >Administración <i class="fa fa-angle-up pull-right"></i></button>
        <div class="collapse in col-xs-12 mini-top" id="collapseExample">


					<div id="administracion">
                                            <div class="form-group">
					<label for="" class="col-xs-12">Nombre</label>
                                        <textarea style="margin-left: 10px;" type="text" required="" name="Nombre: " class="form-control" rows="1"></textarea>
				</div>
                                            <div class="form-group">
					<label for="" class="col-xs-12">Nombre de la empresa</label>
                                        <textarea style="margin-left: 10px;" type="text" required="" name="Nombre de la empresa: " class="form-control" rows="1"></textarea>
				</div>
                                            <div class="form-group">
					<label for="" class="col-xs-12">Medio de contacto</label>
                                        <textarea  style="margin-left: 10px;" type="text" name="Medio de contacto: " class="form-control" rows="1"></textarea>
				</div>
                                            <div class="form-group">
				<label for="" class="col-xs-12">Giro de la empresa</label>
  				<div class="radio col-lg-3">
  					<label>
  						<input required="" name="administracionRadio99" value="<b>¿Giro de la empresa?</b><br>Empresa de servicios" type="radio">
  						Empresa de servicios
  					</label>
  				</div>
  				<div class="radio col-lg-3">
  					<label>
  						<input required="" name="administracionRadio99" value="<b>¿Giro de la empresa?</b><br>Empresa de productos" type="radio">
  						Empresa de productos
  					</label>
  				</div>
				</div>
					<?php
					$data = array(
						'¿Está definida la estructura organizacional de la empresa?',
						'1',
						'¿Se cuenta con la descripción de puestos del personal que labora actualmente?',
						'1',
						'¿Se cuenta con reglamento interior de trabajo, registrado ante la junta local de conciliación y arbitraje?',
						'1',
						'Se le solicita al personal de nuevo ingreso su expediente completo.<br>(no. afiliación IMSS, carta de policía, fotografías recientes, comprobante de domicilio, etc.)',
						'1'
					)?>

					<?php  setData($data,'administracion'); ?>
					</div>


        </div>

      </div>

      <div class="col-xs-12 mini-top">
        <button data-toggle="collapse" data-target="#collapse-almacen" aria-expanded="false" aria-controls="collapse-almacen" class="btn col-xs-12 text-left panel-blue btn-panel">Almacén <i class="fa fa-angle-up pull-right"></i></button>
        <div class="collapse in col-xs-12 mini-top" id="collapse-almacen">

					<div id="almacen">
					<?php
					$data = array(
						'¿Existen informes de entradas y salidas del producto, tanto almacenable como directo?',
						'1',
						'¿Qué pasos se toman para la recepción del producto (conteo, revisión de calidad, pesado con báscula)?',
						'',
						'¿Quiénes son las personas autorizadas para pedir y entregar producto del almacén?',
						'',
						'¿Se manejan documentos de traspaso de mercancía?',
						'1',
						'¿Está definido el horario de entrega y recepción de mercancía?',
						'1',
						'¿Están establecidos los mínimos y máximos, así como la correcta distribución y acomodo del producto en el almacén?',
						'1',
						'¿Cuenta con llave para el almacén y de los departamentos productivos?',
						'1',
						'¿Se cuenta con sello de “recibido” en el almacén y se coteja la mercancía contra la orden de compra?',
						'1',
						'¿Cuál es el costo parámetro? ¿Cuál es el costo potencial?',
						'',
						'¿Hacen traspasos a otras empresas del mismo grupo?',
						'1'
					)?>

					<?php  setData($data,'almacen'); ?>

					</div>
        </div>

      </div>

			<div class="col-xs-12 mini-top">
				<button data-toggle="collapse" data-target="#collapse-sistemas" aria-expanded="false" aria-controls="collapse-sistemas" class="btn col-xs-12 text-left panel-purple btn-panel">Sistemas <i class="fa fa-angle-up pull-right"></i></button>
				<div class="collapse in col-xs-12 mini-top" id="collapse-sistemas">

					<div id="sistemas">
					<?php
					$data = array(
						'¿Existe un sistema para gestionar el punto de venta y/o los almacenes?',
						'1',
						'En caso afirmativo, ¿dicho sistema puede generar los siguientes informes? (todos exportables a Excel):',
						'N',
						'1. Reporte de todos los movimientos realizados en cada uno de los almacenes (compras, traspasos, ventas, rendimientos).',
						'1',
						'2. Listado en de todos los insumos dados de alta con costos promedio (alimentos, bebidas, suministros y gastos).',
						'1',
						'3. Un registro completo de las existencias de cada uno de los almacenes, valuadas a costo promedio o último costo.',
						'1'
					)?>


					<?php  setData($data,'sistemas'); ?>
					</div>
				</div>

			</div>

			<div class="col-xs-12 mini-top">
				<button data-toggle="collapse" data-target="#collapse-finanzas" aria-expanded="false" aria-controls="collapse-finanzas" class="btn col-xs-12 text-left panel-blue btn-panel">Finanzas <i class="fa fa-angle-up pull-right"></i></button>
				<div class="collapse in col-xs-12 mini-top" id="collapse-finanzas">
					<div id="finanzas">
					<?php
					$data = array(
						'¿Se verifican los rendimientos del producto (mermas)?',
						'1',
						'¿Se realizan inventarios de los diferentes almacenes?, ¿con qué frecuencia?, ¿quién los supervisa y costea?',
						'',
						'¿Se verifican las existencias físicas contra kárdex? ¿con qué frecuencia?',
						'',
						'¿Existe un informe analítico diario de costos?',
						'1',
						'¿Se tienen las recetas técnicas costeadas y actualizadas?',
						'1',
						'¿Cómo se manejan las cortesías, promociones e intercambios y quien los autoriza (si aplica)?',
						'',
						'¿Se elaboran estados financieros (flujo de efectivo, costo de venta)?',
						'1',
						'¿A cuánto asciende la venta mensual aproximadamente?',
						'',
						'Número de empleados',
						'',
						'% que representa la nómina con respecto a la venta mensual (fórmula: nómina del mes / ventas del mes).',
						''
					)?>

					<?php  setData($data,'finanzas'); ?>
					</div>
				</div>

			</div>

			<div class="col-xs-12 mini-top">
				<button data-toggle="collapse" data-target="#collapse-compras" aria-expanded="false" aria-controls="collapse-compras" class="btn col-xs-12 text-left panel-pink btn-panel">Compras <i class="fa fa-angle-up pull-right"></i></button>
				<div class="collapse in col-xs-12 mini-top" id="collapse-compras">
					<div id="compras">
					<?php
					$data = array(
						'¿Se maneja el formato de orden de compra?',
						'1',
						'¿Se informa al almacén de la mercancía que va a recibir y las condiciones de la misma?',
						'1',
						'¿Con cuántos proveedores se cotiza el producto?',
						'',
						'¿Cuenta con llave para el almacén y de los departamentos productivos?',
						'',
						'¿Manejan productos en consignación?',
						'1'
					)?>

					<?php  setData($data,'compras'); ?>
					</div>
				</div>

			</div>

			<div class="col-xs-12 mini-top">
				<input type="submit" id="btnSendData" class="btn btn-success col-lg-8 col-lg-offset-2 col-sm-10 col-sm-offset-1 col-xs-offset-2 col-xs-12 col-xs-offset-0 btn-submit" value="Enviar">
			</div>
			<div class="col-xs-12 top">
					<img src="website/img/icons/loading.gif" alt="" id="imgLoading" class="img-center hidden" />
			</div>

		</form>

		<div class="success-mail" style="display: none">
      <div class="alert alert-success">
        <h1 class="text-center">
          <span class="glyphicon glyphicon-ok "></span>
          Información enviada correctamente
        </h1>
      </div>
		</div>

  </div>
</div>

<script type="text/javascript">

</script>
<script src="website/js/diagnostico.js" type="text/javascript">

</script>

<?php

function setData($data,$section)
{
	$aux = 0;
	 for ($i=0; $i < count($data) ; $i++,$aux++)
	 {
             if ($data[$i+1] == 'N'){ ?>
                
             <div class="form-group">
				<label for="" class="col-xs-12"><?php echo $data[$i] ?></label>
  			
				</div>
             <?php }
	     else if($data[$i+1] == '1')
			 { ?>
				<div class="form-group">
				<label for="" class="col-xs-12"><?php echo $data[$i] ?></label>
  				<div class="radio col-lg-1">
  					<label>
  						<input required type="radio" name="<?php echo $section ?>Radio<?php echo $aux ?>" value="<b><?php echo $data[$i] ?> :</b><br> SI">
  						Si
  					</label>
  				</div>
  				<div class="radio col-lg-1">
  					<label>
  						<input required type="radio" name="<?php echo $section ?>Radio<?php echo $aux ?>" value="<b><?php echo $data[$i] ?> :</b><br> NO">
  						No
  					</label>
  				</div>
				</div>

		    <?php
			 }
			 else if($data[$i+1] == '')
			 {?>
				 <div class="form-group" >
					<label for="" class="col-xs-12" ><?php echo $data[$i] ?></label>
					<textarea    style="margin-left: 10px;" required name="<?php echo $data[$i] ?> : " class="form-control" rows="3" ></textarea>
				</div>
				<?php
			 }
			 $i++;
	 }
}
