<div class="row bot">
		<img src="/website/img/banners/Diagnóstico.jpg" alt="" class="img-responsive img-index" />
</div>

<div class="row">
  <div class="container">
    <form  class="form-horizontal"id="formDiagnostico" method="post">

      <div class="col-lg-12">
        <button data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample" class="btn col-lg-12 text-left panel-green btn-panel">Administración <i class="fa fa-angle-up pull-right"></i></button>
        <div class="collapse in col-xs-12 mini-top" id="collapseExample">
          <div class="form-group ">
            <label class="col-md-2" for="">¿Giro de la empresa? </label>
            <div class="col-md-4">
              <select class="form-control" name="">
                <option> Empresa de servicios</option>
              </select>
            </div>

          </div>
          <div class="form-group">
            <label for="" class="col-xs-12">¿Esta definida la estructura de la empresa?</label>
            <div class="radio col-lg-1">
              <label>
                <input type="radio" name="optionsRadios" id="optionsRadios1" value="option1">
                Si
              </label>
            </div>
            <div class="radio col-lg-1">
              <label>
                <input type="radio" name="optionsRadios" id="optionsRadios1" value="option1">
                No
              </label>
            </div>
          </div>
          <div class="form-group">
            <label for="" class="col-xs-12">¿Se cuenta con la descripción de puestos del personal que labora actualmente?</label>
            <div class="radio col-lg-1">
              <label>
                <input type="radio" name="optionsRadios" id="optionsRadios1" value="option1">
                Si
              </label>
            </div>
            <div class="radio col-lg-1">
              <label>
                <input type="radio" name="optionsRadios" id="optionsRadios1" value="option1">
                No
              </label>
            </div>
          </div>
          <div class="form-group">
            <label for="" class="col-xs-12">¿Se cuenta con reglamento interior de trabajo, registrado ante la junta local de conciliación y arbitraje?</label>
            <div class="radio col-lg-1">
              <label>
                <input type="radio" name="optionsRadios" id="optionsRadios1" value="option1">
                Si
              </label>
            </div>
            <div class="radio col-lg-1">
              <label>
                <input type="radio" name="optionsRadios" id="optionsRadios1" value="option1">
                No
              </label>
            </div>
          </div>
          <div class="form-group">
            <label for="" class="col-xs-12">
              Se le solicita al personal de nuevo ingreso su expediente completo.<br>
              (no. afiliación IMSS, carta de policía, fotografías recientes, comprobante de domicilio, etc.)</label>
            <div class="radio col-lg-1">
              <label>
                <input type="radio" name="optionsRadios" id="optionsRadios1" value="option1">
                Si
              </label>
            </div>
            <div class="radio col-lg-1">
              <label>
                <input type="radio" name="optionsRadios" id="optionsRadios1" value="option1">
                No
              </label>
            </div>
          </div>

        </div>

      </div>
      <div class="col-lg-12 mini-top">
        <button data-toggle="collapse" data-target="#collapse-almacen" aria-expanded="false" aria-controls="collapse-almacen" class="btn col-lg-12 text-left panel-blue btn-panel">Almacén <i class="fa fa-angle-up pull-right"></i></button>
        <div class="collapse in col-xs-12 mini-top" id="collapse-almacen">
          <div class="form-group ">
            <label class="col-md-2" for="">¿Giro de la empresa? </label>
            <div class="col-md-4">
              <select class="form-control" name="">
                <option> Empresa de servicios</option>
              </select>
            </div>

          </div>
          <div class="form-group">
            <label for="" class="col-xs-12">¿Esta definida la estructura de la empresa?</label>
            <div class="radio col-lg-1">
              <label>
                <input type="radio" name="optionsRadios" id="optionsRadios1" value="option1">
                Si
              </label>
            </div>
            <div class="radio col-lg-1">
              <label>
                <input type="radio" name="optionsRadios" id="optionsRadios1" value="option1">
                No
              </label>
            </div>
          </div>
          <div class="form-group">
            <label for="" class="col-xs-12">¿Se cuenta con la descripción de puestos del personal que labora actualmente?</label>
            <div class="radio col-lg-1">
              <label>
                <input type="radio" name="optionsRadios" id="optionsRadios1" value="option1">
                Si
              </label>
            </div>
            <div class="radio col-lg-1">
              <label>
                <input type="radio" name="optionsRadios" id="optionsRadios1" value="option1">
                No
              </label>
            </div>
          </div>
          <div class="form-group">
            <label for="" class="col-xs-12">¿Se cuenta con reglamento interior de trabajo, registrado ante la junta local de conciliación y arbitraje?</label>
            <div class="radio col-lg-1">
              <label>
                <input type="radio" name="optionsRadios" id="optionsRadios1" value="option1">
                Si
              </label>
            </div>
            <div class="radio col-lg-1">
              <label>
                <input type="radio" name="optionsRadios" id="optionsRadios1" value="option1">
                No
              </label>
            </div>
          </div>
          <div class="form-group">
            <label for="" class="col-xs-12">
              Se le solicita al personal de nuevo ingreso su expediente completo.<br>
              (no. afiliación IMSS, carta de policía, fotografías recientes, comprobante de domicilio, etc.)</label>
            <div class="radio col-lg-1">
              <label>
                <input type="radio" name="optionsRadios" id="optionsRadios1" value="option1">
                Si
              </label>
            </div>
            <div class="radio col-lg-1">
              <label>
                <input type="radio" name="optionsRadios" id="optionsRadios1" value="option1">
                No
              </label>
            </div>
          </div>

        </div>

      </div>
    </form>
  </div>
</div>

<script type="text/javascript">

</script>
<script src="website/js/diagnostico.js" type="text/javascript">

</script>
