
<div class="row">
		<img src="/website/img/banners/img-indexv2.jpg" alt="" class="img-responsive img-index" />
</div>
<div class="row">
	<div class="col-lg-10 col-lg-offset-1 col-md-12 col-md-offset-0 col-xs-12 col-xs-offset-0">

	<div class="row">
		<div class="col-md-4 col-md-offset-0 col-sm-8 col-sm-offset-2">
			<h2 class="text-center">¿Qué hacemos?</h2>
			<div class="page-header"></div>
                        <p style="text-align: justify; text-justify: inter-word;">
				En AERSA nos especializamos en la implementación de un entorno de control interno real, a través de un análisis detallado de cómo está estructurada su empresa, tenemos áreas especializadas en empresas de servicios (hoteles, restaurantes, bares) y productos (comercializadoras, productoras)
			</p>
		</div>
		<div class="col-md-4 col-md-offset-0 col-sm-8 col-sm-offset-2">
			<h2 class="text-center">¿Cómo lo hacemos?</h2>
			<div class="page-header"></div>
			<p style="text-align: justify; text-justify: inter-word;">
				Al diagnosticar su empresa, diseñamos un plan de trabajo personalizado, utilizando la reingeniería eliminamos o capacitamos personal que no lleva a cabo las mejores prácticas, asimismo, establecemos lineamientos que deben seguirse y sus respectivas herramientas de supervisión.
			</p>
		</div>
		<div class="col-md-4 col-md-offset-0 col-sm-8 col-sm-offset-2">
			<h2 class="text-center">¿Por qué?</h2>
			<div class="page-header"></div>
			<p style="text-align: justify; text-justify: inter-word;">
				Con esto, detectamos y/o prevenimos fraudes, implementamos las herramientas necesarias para controlar flujo, costos e inventarios de manera clara y concentrada, y aumentamos las utilidades.
			</p>
		</div>
	</div>


	</div>

</div>

<div class="row top" >
	<div class="col-xs-12">
		<div class="row" style="background-image: url('website/img/1305.png'); opacity: 1; background-position: 75% 50%; ">
			<div class="col-md-5 col-md-offset-0 col-sm-8 col-sm-offset-2">
				<img src="/website/img/macv2.png" class="img-responsive col-xs-10 col-xs-offset-1 top bot"  alt="" />
			</div>
			<div class="col-md-7 col-md-offset-0 col-sm-10 col-sm-offset-1" style="padding-top: 70px; padding-right: 50px;">
                            <h2 style="color:#729D4A"class="white text-center" >Con nuestra plataforma web AERSA CFCI consolida toda tu información en una sola fuente</h2>
                            <h4 class="white text-center" style="color:#98CC62">Evite cuadres y cruces con otras entidades, tales como contadores internos o externos u otros entes administrativos</h4>
				<button class="btn btn-lg btn-info white col-md-4 col-md-offset-4 col-sm-6 col-sm-offset-3 col-xs-10 col-xs-offset-1 top bot">Comience hoy mismo</button>
			</div>

		</div>
	</div>
</div>

<div class="row top">
	<div class="col-lg-10 col-lg-offset-1 col-md-12 col-md-offset-0 text-center">
		<strong class="top">Con AERSA CFCI se controla dentro de una sola plataforma los siguientes puntos clave de su empresa:</strong>
		<div class="row top">
			<div class="col-md-4 text-left">
				<h2 class="text-center">Flujo de efectivo</h2>
				<div class="page-header"></div>
				<p>
					Control de entradas y salidas de flujo de efectivo, cuentas bancarias y cuentas por cobrar y pagar.
				</p>
			</div>
			<div class="col-md-4 text-left">
				<h2 class="text-center">Costos</h2>
				<div class="page-header"></div>
				<p>
					Control de costos diarios, recetas técnicas y consumos.
				</p>
			</div>
			<div class="col-md-4 text-left">
				<h2 class="text-center">Inventarios</h2>
				<div class="page-header"></div>
				<p>
					Valuación y control de inventarios, así como detección de fugas por negligencia o dolo.
				</p>
			</div>
		</div>
	</div>

</div>
