
<div class="row">
		<img src="/website/img/banners/img-index.png" alt="" class="img-responsive img-index" />
</div>
<div class="row">
	<div class="col-lg-10 col-lg-offset-1">

	<div class="row">
		<div class="col-lg-4">
			<h2 class="text-center">¿Qué hacemos?</h2>
			<div class="page-header"></div>
			<p>
				En AERSA nos especializamos en la implementación de un entorno de control interno real, a través de un análisis detallado de cómo está estructurada su empresa, tenemos áreas especializadas en empresas de servicios (hoteles, restaurantes, bares) y productos (comercializadoras, productoras)
			</p>
		</div>
		<div class="col-lg-4">
			<h2 class="text-center">¿Cómo lo hacemos?</h2>
			<div class="page-header"></div>
			<p>
				Al diagnosticar su empresa, diseñamos un plan de trabajo personalizado, utilizando la reingeniería eliminamos o capacitamos personal que no lleva a cabo las mejores prácticas, asimismo, establecemos lineamientos que deben seguirse y sus respectivas herramientas de supervisión.
			</p>
		</div>
		<div class="col-lg-4">
			<h2 class="text-center">¿Por qué?</h2>
			<div class="page-header"></div>
			<p>
				Con esto, detectamos y/o prevenimos fraudes, implementamos las herramientas necesarias para controlar flujo, costos e inventarios de manera clara y concentrada, y aumentamos las utilidades.
			</p>
		</div>
	</div>


	</div>

</div>

<div class="row bg-green top">
	<div class="col-lg-12">
		<div class="row">
			<div class="col-lg-5">
				<img src="/website/img/IMac_vector.svg.png" class="img-responsive col-xs-10 col-xs-offset-1 top bot"  alt="" />
			</div>
			<div class="col-lg-7">
				<h1 class="white text-center top"><strong>Algún texto anunciando un servicio empresarial</strong></h1>
				<h3 class="white text-center">Algun texto descriptivo acerca de este servicio.</h3>
				<button class="btn btn-default green col-lg-4 col-lg-offset-4 top">Acción</button>
			</div>

		</div>
	</div>
</div>

<div class="row top">
	<div class="col-lg-10 col-lg-offset-1 text-center">
		<strong class="top">Con AERSA CFCI se controla dentro de una sola plataforma los siguientes puntos clave de su empresa:</strong>
		<div class="row top">
			<div class="col-lg-4 text-left">
				<h1>Flujo de efectivo</h1>
				<div class="page-header"></div>
				<p>
					Control de entradas y salidas de flujo de efectivo, cuentas bancarias y cuentas por cobrar y pagar.
				</p>
			</div>
			<div class="col-lg-4 text-left">
				<h1>Costos</h1>
				<div class="page-header"></div>
				<p>
					Control de costos diarios, recetas técnicas y consumos.
				</p>
			</div>
			<div class="col-lg-4 text-left">
				<h1>Inventarios</h1>
				<div class="page-header"></div>
				<p>
					Valuación y control de inventarios, así como detección de fugas por negligencia o dolo.
				</p>
			</div>
		</div>
	</div>

</div>
