
<div class="row">
		<img src="/website/img/banners/img-indexv2.jpg" alt="" class="img-responsive img-index" />
</div>
<div class="row">
	<div class="col-lg-10 col-lg-offset-1 col-md-12 col-md-offset-0 col-xs-12 col-xs-offset-0">

	<div class="row">
		<div class="col-md-4 col-md-offset-0 col-sm-8 col-sm-offset-2">
			<h2 class="text-center">¿Qué hacemos?</h2>
			<div class="page-header"></div>
                        <p style="text-align: justify; text-justify: inter-word;">
				En AERSA nos especializamos en la implementación de un entorno de control interno real, a través de un análisis detallado de cómo está estructurada su empresa, tenemos áreas especializadas en empresas de servicios (hoteles, restaurantes, bares) y productos (comercializadoras, productoras, importadoras). Nuestras tres áreas de enfoque son: <b>flujo de efectivo, costos e inventarios</b>, todo controlado desde una plataforma integral optimizando tiempos y evitando engorrosos cuadres entre las diferentes áreas que controlan estas partidas.
			</p>
		</div>
		<div class="col-md-4 col-md-offset-0 col-sm-8 col-sm-offset-2">
			<h2 class="text-center">¿Cómo lo hacemos?</h2>
			<div class="page-header"></div>
			<p style="text-align: justify; text-justify: inter-word;">
                            Al diagnosticar su empresa, diseñamos un plan de trabajo personalizado, utilizando la reingeniería eliminamos o capacitamos personal que no lleva a cabo las mejores prácticas de control interno para su empresa, asimismo, establecemos lineamientos que deben seguirse y sus respectivas herramientas de supervisión, ya que creemos firmemente que una implementación de control interno sin elementos para su ejecución y control está destinada a fracasar. Asimismo, contamos con programas de capacitación para todo el personal que tiene participación en el control interno de su empresa, logrando con esto que se apeguen al control interno implementado.
                        </p>
		</div>
		<div class="col-md-4 col-md-offset-0 col-sm-8 col-sm-offset-2">
			<h2 class="text-center">¿Por qué?</h2>
			<div class="page-header"></div>
			<p style="text-align: justify; text-justify: inter-word;">
                            Con esto, detectamos y/o prevenimos fraudes, implementamos las herramientas necesarias para controlar flujo, costos e inventarios de manera clara y concentrada, teniendo como resultado mayor tranquilidad para los dueños/socios, un reporteo de cuentas claras en tiempo real, una mayor conciencia en el uso y aprovechamiento de los recursos y lo más importante: un incremento en las utilidades. <b>En AERSA, nuestro objetivo principal es que la inversión en nuestros servicios profesionales sea siempre menor a los beneficios obtenidos por los mismos.</b>
                        </p>
		</div>
	</div>


	</div>

</div>

<div class="row top" >
	<div class="col-xs-12">
		<div class="row" style="background-image: url('website/img/1305.png'); opacity: 1; background-position: 75% 50%; ">
			<div class="col-md-5 col-md-offset-0 col-sm-8 col-sm-offset-2">
				<img src="/website/img/CFCI AERSA.png" class="img-responsive col-xs-10 col-xs-offset-1 top bot"  alt="" />
			</div>
			<div class="col-md-7 col-md-offset-0 col-sm-10 col-sm-offset-1" style="padding-top: 70px; padding-right: 50px;">
                            <h2 style="color:#729D4A"class="white text-center" >Con nuestra plataforma web AERSA CFCI consolida toda tu información en una sola fuente</h2>
                            <h4 class="white text-center" style="color:#98CC62">Evite cuadres y cruces con otras entidades, tales como contadores internos o externos u otros entes administrativos</h4>
                            <a href="/diagnostico" style="white-space:normal; word-wrap:break-word; " class="btn btn-lg btn-info white col-md-4 col-md-offset-4 col-sm-6 col-sm-offset-3 col-xs-10 col-xs-offset-1 top bot">Obtenga una propuesta personalizada para su empresa</a>
			</div>

		</div>
	</div>
</div>

<div class="row top">
	<div class="col-lg-10 col-lg-offset-1 col-md-12 col-md-offset-0 text-center">
		<strong class="top">Con AERSA CFCI se controla dentro de una sola plataforma los siguientes puntos clave de su empresa:</strong>
		<div class="row top">
			<div class="col-md-4 text-left">
				<h2 class="text-center">Flujo de efectivo</h2>
				<div class="page-header"></div>
				<p style="text-align: justify; text-justify: inter-word;">
                                    Control de entradas y salidas de flujo de efectivo, cajas chicas, cuentas bancarias y cuentas por cobrar y pagar, incluyendo cheques en circulación y anticipos a proveedores. Determinación de pérdidas o utilidades antes de impuestos, control de compras, gastos de manera analítica para servir de apoyo en la toma de decisiones y reparto de utilidades.
                                </p>
			</div>
			<div class="col-md-4 text-left">
				<h2 class="text-center">Costos</h2>
				<div class="page-header"></div>
				<p style="text-align: justify; text-justify: inter-word;">
                                    Control de costos a través de cédulas de costos por diferencias de inventarios (incluye valuaciones de las existencias), consumos reales contra estimados (recetas contra consumo real), validación de ejecución de recetas en campo, recomendaciones para determinación de precios de venta. Asimismo, análisis de costos unitarios con alertas personalizadas de aumentos o decrementos para apoyar en las cotizaciones con proveedores.
                                </p>
			</div>
			<div class="col-md-4 text-left">
				<h2 class="text-center">Inventarios</h2>
				<div class="page-header"></div>
				<p style="text-align: justify; text-justify: inter-word;">
                                    Valuación y control de inventarios, así como detección de mal uso de mercancía por negligencia o dolo con un nivel de detalle máximo. Esto incluye manejo de múltiples almacenes de resguardo y operativos, así como control entre traspasos entre almacenes de una misma sucursal o entre sucursales de un mismo grupo incluyendo manejo de comisariatos en caso de grupos grandes, además de controles específicos para mercancía en consignación y productos bonificados.
                                </p>
			</div>
		</div>
	</div>

</div>
