<div class="row bot">
		<img src="/website/img/banners/nosotros.png" alt="" class="img-responsive img-index" />
</div>
<div class="container">
  <div class="row">
    <h1>Nosotros</h1>
    <div class="border-nosotros" style="width: 100%"></div>
  </div>
  <div class="row top">
      <p style="text-align: justify">
      En AERSA somos un equipo de profesionales especializado en el diseño y ejecución de entornos de control interno, con el objetivo de prevenir y detectar fugas y malos manejos en el uso de los recursos de su empresa, contamos con personal experimentado durante más de 10 años en giros de servicios (hoteles, restaurantes, bares) y productos (productoras, comercializadoras, importadoras).
    </p>
    <p style="text-align: justify">
      Entre nuestros principales logros se encuentran las detecciones de fraudes y desviaciones de recursos, así como la baja de personal implicado de manera dolosa o negligente en dichos eventos.
    </p>
    <p style="text-align: justify">
      Con nuestra herramienta AERSA CFCI (Control de flujo, costos e inventarios) ofrecemos una solución integral donde podrá ver reflejados los resultados de la implementación de nuestros controles y reglas de negocio compatible con virtualmente cualquier punto de venta. Ofrecemos dos maneras de trabajar:
    </p>
    <p style="text-align: justify">
      -     AERSA implementa, supervisa y audita el flujo, costo e inventarios de la empresa de manera permanente.<br>
      -     AERSA implementa y capacita a un equipo de auditoría interno de la empresa para la supervisión y control del flujo, costo e inventarios de la empresa, el cual contará con soporte por parte de AERSA.
    </p>
  </div>

</div>
