<link href="/application/global/plugins/datatables/datatables.min.css" rel="stylesheet" type="text/css" />
<link href="/application/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.css" rel="stylesheet" type="text/css" />
<div id="my_container">
    <h3 class="page-title">Asociación productos - Conceptos CFDI</h3>
    <div class="page-bar">
        <ul class="page-breadcrumb">
            <li>
                <a href="/catalogo/asociacionconceptos">Listado de productos</a>
            </li>
        </ul>
    </div>
    <?php foreach ($messages->getSuccessMessages() as $message):?>
        <div class="alert alert-success alert-dismissable">
            <button class="close" aria-hidden="true" data-dismiss="alert" type="button"></button>
            <strong>Éxito!</strong>
            <?php echo $message?>
        </div>
    <?php endforeach;?>
    <div class="portlet box green" style="border-left-width: 0px; border-bottom-width: 0px; border-right-width: 0px;">
        <div class="portlet-body form">
            <div class="form-body">
                
                <table class="table table-striped table-bordered table-hover order-column" id="datatable_product" style="border-bottom-width: 0px;">
                    <thead >
                        <tr>
                            <th> Proveedor </th>
                            <th> Emisor </th>
                            <th> Opciones </th>
                        </tr>
                    </thead>
                    <tbody>

                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<script src="/application/global/scripts/datatable.js" type="text/javascript"></script>
<script src="/application/global/plugins/datatables/datatables.min.js" type="text/javascript"></script>

<script src="/application/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.js" type="text/javascript"></script>
<script type="text/javascript" src="https://cdn.datatables.net/plug-ins/1.10.12/api/fnSetFilteringDelay.js"></script>
<script>
    
        
      function encode_utf8(s) {
        return unescape(encodeURIComponent(s));
      }

      function decode_utf8(s) {
        return decodeURIComponent(escape(s));
      }
          
      //INICIALIZAMOS DATATABLES
        var table = $('#datatable_product');
        $.ajax({
            url:'/application/json/datatable/lang_es.json',
            dataType:'json',
            success:function(data){
               table.dataTable({
                   "language":data,
                   "order":[[0,'asc']],
                   "serverSide": true,
                   processing: true,
                   iDisplayLength:10,
                   searchDelay: 350,
                   "ajax": {
                        "type": "POST"
                    },
                    "columns": [
                        {"data": "producto_nombre", "name": "producto_nombre", "orderable": true},
                        {"data": "productocfdi_nombre", "name": "productocfdi_nombre", "orderable": true},
                        {"data": "options", "name": "options", "orderable": false}
                    ],
                    "columnDefs": [
                        { "orderable": false, "targets": 0 }
                    ],
                    "rowCallback": function( row, data, index ) {
                        $(row).find('.asociar_modal').on('click',function(){
                            var tmpl = [
                                '<div class="modal fade bs-modal-lg in" aria-hidden="true" role="dialog" tabindex="-1" style="display: block;">',
                                    '<form method="post" action="/catalogo/asociacionconceptos/asociar">',
                                        '<div class="modal-header">',
                                            '<h4 class="modal-title">Asociación productos - Conceptos CFDI </h4>',
                                        '</div>',
                                        '<div class="modal-body">',
                                            '<div class="row">',

                                                '<div class="col-md-12">',
                                                    '<div class="form-group">',
                                                        '<label for="producto_nombre">Producto *</label>',
                                                        '<input required class="form-control" type="text" name="proveedor_razonsocial" value="'+decode_utf8(data.producto_nombre)+'" disabled>',
                                                    '</div>',
                                                '</div>',
                                                '<div class="col-md-12">',
                                                    '<div class="form-group">',
                                                        '<label for="producto_nombre">Concepto *</label>',
                                                        '<div class="form-group">',

                                                            '<input type="hidden" name="idproducto" value="'+data.DT_RowId+'">',
                                                            '<input required class="form-control" type="text" name="productocfdi_nombre">',
                                                             '<span style="color:red;display:none">Este campo es requerido</span>',
                                                        '</div>',
                                                    '</div>',
                                                '</div>',
                                            '</div>',
                                        '</div>',
                                        '<div class="modal-footer">',
                                            '<button id="save_product" href="#" class="btn blue">Guardar</button>',
                                            '<button id="cancel_product" href="#" class="btn red">Cancelar</button>',
                                        '</div>',
                                    '</form>',
                                '</div>',  
                            ].join('');
                            var $modal = $(tmpl);
                            $modal.modal();
                            $modal.find('#cancel_product').on('click',function(){
                                $modal.modal('hide');
                            });
                        });
                        $(row).find('.delete_modal').on('click',function(){
                            var tmpl = [
                                // tabindex is required for focus
                                ' <div class="modal fade draggable-modal" id="draggable" tabindex="-1" role="basic" aria-hidden="true">',
                                  '<div class="modal-header">',
                                    '<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>',
                                    '<h4 class="modal-title">ADVERTENCIA</h4>', 
                                  '</div>',
                                  '<form method="post" action="/catalogo/asociacionconceptos/eliminar">',
                                    '<div class="modal-body">',
                                      '<input type="hidden" name="idproducto" value="'+data.DT_RowId+'">',
                                      '<p>¿Estas seguro que deseas eliminar la asociación seleccionada?</p>',
                                    '</div>',
                                    '<div class="modal-footer">',
                                      '<a href="#" data-dismiss="modal" class="btn btn-default">Cancelar</a>',
                                      '<button class="btn btn-danger" type="submit">Eliminar</button>',
                                    '</div>',
                                  '</form>',
                                '</div>'
                            ].join('');
                            var $modal = $(tmpl);
                            $modal.modal();
                            $modal.find('#cancel_product').on('click',function(){
                                $modal.modal('hide');
                            });
                        });
                    }
               }).fnSetFilteringDelay();
            },
        });

</script>