<link href="/application/global/plugins/datatables/datatables.min.css" rel="stylesheet" type="text/css" />
<link href="/application/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.css" rel="stylesheet" type="text/css" />
<div id="my_container">
    <h3 class="page-title">Tasa IVA</h3>
    <div class="page-bar">
        <ul class="page-breadcrumb">
            <li>
                <a href="/catalogo/usuario">Tasa de iva</a>
            </li>
        </ul>
    </div>
    <?php foreach ($messages->getSuccessMessages() as $message):?>
        <div class="alert alert-success alert-dismissable">
            <button class="close" aria-hidden="true" data-dismiss="alert" type="button"></button>
            <strong>Éxito!</strong>
            <?php echo $message?>
        </div>
    <?php endforeach;?>
    <div class="portlet box green" style="border-left-width: 0px; border-bottom-width: 0px; border-right-width: 0px;">
        <div class="portlet-body form">
            <div class="form-body">
                <?php if (count($collection) < 2): ?>
                    <div class="btn-set pull-right">
                        <a href="/catalogo/iva/nuevo"><button class="btn default" type="button" style="margin-bottom: 15px;"><i class="fa fa-plus"></i> Nueva Tasa</button></a>
                    </div>
                <?php endif ?>
                
                <table class="table table-striped table-bordered table-hover order-column text-center" id="datatable" style="border-bottom-width: 0px;">
                    <thead>
                        <tr>
                            <th class="text-center"> Tasa IVA </th>
                            <th class="text-center"> Acciones </th>

                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($collection as $entity) : ?>
                            
                            <tr id="<?php echo $entity->getIdtasaiva() ?>">
                                <td><?php echo $entity->getTasaivaValor() ?></td>
                                

                                
                                <td>
                                    <div class="btn-group">
                                    <a href="/catalogo/iva/editar/<?php echo $entity->getIdtasaiva()?>">
                                        <button class="btn blue btn-xs">
                                                <i class="fa fa-pencil"></i> Editar 
                                        </button>
                                    </a>
                                    <a href="javascript:;" class="delete_modal_iva">
                                        <button class="btn red btn-xs">
                                                <i class="fa fa-trash"></i> Eliminar 
                                        </button>
                                    </a>
                                        
                                    </div>
                                </td><br>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<script src="/application/global/scripts/datatable.js" type="text/javascript"></script>
<script src="/application/global/plugins/datatables/datatables.min.js" type="text/javascript"></script>
<script src="/application/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.js" type="text/javascript"></script>
<script src="/application/custom/js/catalogo/usuario.js" type="text/javascript"></script>	
<script>
    (function( $ ){
    
    // var plugin = $('#my_container').usuario();
    $('.delete_modal_iva').click(function(){
              
      var id = $(this).closest('tr').attr('id');
      var tmpl = [
        // tabindex is required for focus
        ' <div class="modal fade draggable-modal" id="draggable" tabindex="-1" role="basic" aria-hidden="true">',
          '<div class="modal-header">',
            '<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>',
            '<h4 class="modal-title">ADVERTENCIA</h4>', 
          '</div>',
          '<form method="post" action="/catalogo/iva/eliminar/'+id+'">',
            '<div class="modal-body">',
              '<p>¿Estas seguro que deseas eliminar la tasa de iva seleccionada?</p>',
            '</div>',
            '<div class="modal-footer">',
              '<a href="#" data-dismiss="modal" class="btn btn-default">Cancelar</a>',
              '<button class="btn btn-danger" type="submit">Eliminar</button>',
            '</div>',
          '</form>',
        '</div>'
      ].join('');
      $(tmpl).modal();
    });
    

})( jQuery );
</script>