<h3 class="page-title"><?php echo $form->get('almacen_nombre')->getValue()?></h3>
<div class="page-bar">
    <ul class="page-breadcrumb">
        <li>
            <a href="/catalogo/usuario">Usuarios</a>
            <i class="fa fa-angle-right"></i>
        </li>
        <li>
            <span><?php echo $form->get('almacen_nombre')->getValue()?></span>
        </li>
    </ul>
</div>
<?php foreach ($messages->getErrorMessages() as $message):?>
    <div class="alert alert-danger alert-dismissable">
        <button class="close" aria-hidden="true" data-dismiss="alert" type="button"></button>
        <strong>Error!</strong>
        <?php echo $message?>
        
    </div>
<?php endforeach;?>
<?php
    $form->setAttribute('action', '/catalogo/almacen/editar/'.$form->get('idalmacen')->getValue().'/'.$sucursal->getIdSucursal().'/'.$empresa->getIdEmpresa());
    echo $this->form()->openTag($form);
?>
<div class="portlet box green" style="border-left-width: 0px; border-bottom-width: 0px; border-right-width: 0px;">
    <div class="portlet-body form">
        <div class="form-body">
            <h3 class="form-section">Información general</h3>
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <?php echo $this->formLabel($form->get('almacen_nombre')) ?>  
                        <?php echo $this->formText($form->get('almacen_nombre')) ?>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <?php echo $this->formLabel($form->get('almacen_encargado')) ?>  
                        <?php echo $this->formText($form->get('almacen_encargado')) ?>
                    </div>
                </div>
                <div class="col-md-6">
                    <div >
                        <?php echo $this->formLabel($form->get('almacen_estatus')) ?>  
                        <?php echo $this->formSelect($form->get('almacen_estatus')) ?>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <br>
                    <p>(*)Campos obligatorios</p>
                </div>
            </div>
        </div>
        <div class="form-actions right">
            <button class="btn blue" type="submit">
                <i class="fa fa-check"></i>
                Guardar
            </button>
        </div>
    </div>
</div>
<?php  echo $this->form()->closeTag(); ?>
