<!--<div class="row bg-purple newcl">
	<div class="col-lg-2">
		<div class="row">
			<img src="/website/img/img-cotizar.png" alt="">
		</div>
	</div>
	<div class="col-lg-10 ">
		<div class="test">
			<h1 >Cotización para el cliente</h1>
			<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptas repellendus porro neque exercitationem quo maiores, consectetur corporis dolores ad officia veniam assumenda! Ipsa numquam, sunt eum? Vitae qui, modi maxime.</p>
			<button class="btn btn-default">Cotizar</button>
		</div>
	</div>
</div>-->

<div class="row">
		<img src="/website/img/img-index.png" alt="" class="img-responsive img-index" />
</div>
<div class="row">
	<div class="col-lg-10 col-lg-offset-1">

	<div class="row">
		<div class="col-lg-4">
			<h1 class="text-center">¿Qué hacemos?</h1>
			<div class="page-header"></div>
			<p>
				En AERSA nos especializamos en la implementación de un entorno de control interno real, a través de un análisis detallado de cómo está estructurada su empresa, tenemos áreas especializadas en empresas de servicios (hoteles, restaurantes, bares) y productos (comercializadoras, productoras)
			</p>
		</div>
		<div class="col-lg-4">
			<h1 class="text-center">¿Cómo lo hacemos?</h1>
			<div class="page-header"></div>
			<p>
				Al diagnosticar su empresa, diseñamos un plan de trabajo personalizado, utilizando la reingeniería eliminamos o capacitamos personal que no lleva a cabo las mejores prácticas, asimismo, establecemos lineamientos que deben seguirse y sus respectivas herramientas de supervisión.
			</p>
		</div>
		<div class="col-lg-4">
			<h1 class="text-center">¿Por qué?</h1>
			<div class="page-header"></div>
			<p>
				Con esto, detectamos y/o prevenimos fraudes, implementamos las herramientas necesarias para controlar flujo, costos e inventarios de manera clara y concentrada, y aumentamos las utilidades.
			</p>
		</div>
	</div>


	</div>

</div>
<!--
<div class="row" style="margin-top: 150px;">
    <div class="col-md-8 col-md-offset-2" >
        <img class="img-responsive" src="/website/img/website-under-construction.png"></img>
    </div>
</div>

-->
