

<div class="row bg-purple newcl">
	<div class="col-lg-2">
		<div class="row">
			<img src="/website/img/img-cotizar.png" alt="">
		</div>
	</div>
	<div class="col-lg-10 ">
		<div class="test">
			<h1 >Cotización para el cliente</h1>
			<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptas repellendus porro neque exercitationem quo maiores, consectetur corporis dolores ad officia veniam assumenda! Ipsa numquam, sunt eum? Vitae qui, modi maxime.</p>
			<button class="btn btn-default">Cotizar</button>
		</div>
	</div>

</div>