<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Aersa')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/website/css/style.css')
                        ->prependStylesheet($this->basePath() . '/website/css/bootstrap.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/website/js/bootstrap.js')
            ->prependFile($this->basePath() . '/website/js/jquery.min.js')
        ; ?>

    </head>
    <body>
        <div class="container">

            <nav class="navbar navbar-default">

                    <!-- Brand and toggle get grouped for better mobile display -->
                    <div class="navbar-header">
                      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                      </button>
                      
                    </div>

                    <!-- Collect the nav links, forms, and other content for toggling -->

                        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-2">
                            <div class="col-lg-2">
                                <ul class="nav navbar-nav ">
                                    <li><a class="color-green" href="#"><img src="/website/img/aersa.png" class="img-responsive"alt=""></a></li>
                                </ul>
                            </div>

                            <div class="col-lg-10">
                                <div class="col-lg-12">
                                    <ul class="nav navbar-nav navbar-right  row">
                                        <li><a class="color-green" href="#">Iniciar sesión <img src="/website/img/login.png" alt=""></a></li>
                                    </ul>
                                </div>
                                <div class="col-lg-12">
                                    <ul class="nav navbar-nav navbar-right  row top">
                                        <li><a class="color-green" href="#">Servicios</a></li>
                                        <li><a class="color-green" href="#">Nosotros</a></li>
                                        <li><a class="color-green" href="#">Cotización</a></li>
                                        <li><a class="color-green" href="#">Contacto</a></li>
                                    </ul>
                                </div>
                            </div>
                        </div><!-- /.navbar-collapse -->
            </nav>

            <?php echo $this->content; ?>

        
            <hr>
            <footer>
                
            </footer>
        
        </div> 
        <?php echo $this->inlineScript() ?>
    </body>
</html>
