<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('AERSA')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/website/css/style.css')
                        ->prependStylesheet($this->basePath() . '/website/css/magic.min.css')
                        ->prependStylesheet($this->basePath() . '/website/css/font-awesome.min.css')
                        ->prependStylesheet($this->basePath() . '/website/css/index.css')
                        ->prependStylesheet($this->basePath() . '/website/css/diagnostico.css')
                        ->prependStylesheet($this->basePath() . '/website/css/contacto.css')
                        ->prependStylesheet($this->basePath() . '/website/css/jasny-bootstrap.css')
                        ->prependStylesheet($this->basePath() . '/website/css/bootstrap.css')
                         ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/website/js/bootstrap.js')
            ->prependFile($this->basePath() . '/website/js/jasny-bootstrap.min.js')
            ->prependFile($this->basePath() . '/website/js/jquery.min.js')
        ; ?>

    </head>
    <body>
        <div class="container-fluid">


            <!-- Navbar versión móvil -->
            <nav id="navMovil" class="navmenu navmenu-default navmenu-fixed-left offcanvas" role="navigation">
              <ul class="nav navmenu-nav">
                <li><a class="text-center color-green" href="#">Servicios</a></li>
                <li><a class="text-center color-green" href="/nosotros">Nosotros</a></li>
                <li><a class="text-center color-green" href="/diagnostico">Diagnóstico</a></li>
                <li><a class="text-center color-green" href="/contacto">Contacto</a></li>
              </ul>
            </nav>

            <nav class="navbar navbar-default">

                    <!-- Brand and toggle get grouped for better mobile display -->
                    <div class="navbar-header">
                      <button type="button" class="navbar-toggle collapsed" data-toggle="offcanvas" data-canvas="body" data-target="#navMovil" aria-expanded="false">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                      </button>
                      <img src="/website/img/logo_aersa.png" class="img-responsive hidden visible-xs"alt="">
                    </div>


                    <!-- Collect the nav links, forms, and other content for toggling -->

                        <div class="collapse navbar-collapse hidden-xd" id="">
                            <div class="col-lg-2 col-md-2 hidden-xs">
                                <ul class="nav navbar-nav ">
                                    <li><a class="color-green" href="/"><img src="/website/img/logo_aersa.png" class="img-responsive"alt=""></a></li>
                                </ul>
                            </div>

                            <div class="col-lg-10 col-md-10">
<!--                                <div class="col-lg-12 col-md-12">
                                    <ul class="nav navbar-nav navbar-right  row">
                                        <li><a class="color-green" href="">Iniciar sesión <img src="/website/img/login.png" alt=""></a></li>
                                    </ul>
                                </div>-->
                                <div class="col-lg-12 col-md-12" style="padding-top: 75px;">
                                    <ul class="nav navbar-nav navbar-right  row top">
                                        <li><a class="color-green" href="/">Inicio</a></li>
                                        <li><a class="color-green" href="/servicios">Servicios</a></li>
                                        <li><a class="color-green" href="/nosotros">Nosotros</a></li>
                                        <li><a class="color-green" href="/diagnostico">Diagnóstico</a></li>
                                        <li><a class="color-green" href="/contacto">Contacto</a></li>
                                        <li><a class="color-green" href="http://admin.aersamx.com">Iniciar sesión</a></li>
                                    </ul>
                                </div>
                            </div>
                        </div><!-- /.navbar-collapse -->
            </nav>

            <?php echo $this->content; ?>



            <footer class="top">
              <div class="row footer-container">
                <div class="container">
                  <div class="col-md-4 col-md-offset-4 col-sm-6 col-sm-offset-3 col-xs-12 col-xs-offset-0 top">
                    <div class="col-md-3 col-sm-3 col-xs-3 col-xs-offset-3 col-lg-offset-3 col-md-offset-3 col-sm-offset-3">


                    <a href="#"><img src="/website/img/icons/facebook-logo-button.png"class=" img-center icon-footer" alt="" /></a></div>
                    <div class="col-md-3 col-sm-3 col-xs-3 ">


                    <a href="#"><img src="/website/img/icons/instagram-logo.png"class=" img-center icon-footer" alt="" /></a></div>
                  </div>
                  <div class="col-xs-12 bot top">
                    <div class="row footer-menu">
                      <div class="col-md-1 col-sm-1"></div>
                      <div class="col-md-2  col-sm-2 col-xs-12 text-center top-xs">
                        <a href="/"><strong class="white">Inicio<div class="pull-right fa fa-circle hidden-sm hidden-xs"></div></strong></a>
                      </div>
                      <div class="col-md-2  col-sm-2 col-xs-12 text-center top-xs">
                        <a href="#"><strong class="white">Servicios<div class="pull-right fa fa-circle hidden-sm hidden-xs"></div></strong></a>
                      </div>
                      <div class="col-md-2  col-sm-2 col-xs-12 text-center top-xs">
                        <a href="/nosotros"><strong class="white">Nosotros<div class="pull-right fa fa-circle hidden-sm hidden-xs"></div></strong></a>
                      </div>
                      <div class="col-md-2  col-sm-2 col-xs-12 text-center top-xs">
                        <a href="/diagnostico"><strong class="white">Diagnóstico<div class="pull-right fa fa-circle hidden-sm hidden-xs"></div></strong></a>
                      </div>
                      <div class="col-md-2  col-sm-2 col-xs-12 text-center top-xs">
                        <a href="/contacto"><strong class="white">Contacto</strong></a>
                      </div>
                    </div>

                  </div>
                </div>
              </div>
              <div class="row copyright-container text-center">
                <h5 class="mini-top mini-bot">AERSA 2016  |  TODOS LOS DERECHOS RESERVADOS</h5>
              </div>
            </footer>

        </div>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
