<style>
    input[type=file]{
        padding-top: 0px;
        padding-left: 0px;
    }
    #productos_table .fa-trash{
        color:red;
    }
</style>
<link rel="stylesheet" type="text/css" href="/application/custom/css/validaciones.css">
<div id="form_container">
    <div class="page-bar">
        <ul class="page-breadcrumb">
            <li>
                <a href="javascript:;">Procesos</a>
                 <i class="fa fa-angle-right"></i>
            </li>
            <li>
                <a href="/procesos/requisicion">Requisicion</a>
                 <i class="fa fa-angle-right"></i>
            </li>
            <li>
                <a href="javascript:;"><?php echo '#'.$form->get('idrequisicion')->getValue()?></a>
            </li>
        </ul>
    </div>
    <h3 class="page-title">Requisición - <?php echo '#'.$form->get('idrequisicion')->getValue()?></h3>
    <?php
    $form->setAttribute('action', '/procesos/requisicion/editar/'.$form->get('idrequisicion')->getValue());
    echo $this->form()->openTag($form);
    ?>
    <div class="portlet box green" style="border-left-width: 0px; border-bottom-width: 0px; border-right-width: 0px;">
        <div class="portlet-body form">
            <div class="form-body">
                <h3 class="form-section">Información general</h3>
                <div class="row">
                    <?php echo $this->formHidden($form->get('idempresa')); ?>
                    <div class="col-md-6">
                        <?php echo $this->formLabel($form->get('requisicion_fecha')) ?>  
                        <?php echo $this->formText($form->get('requisicion_fecha')) ?> 
                        <?php echo $this->formHidden($form->get('requisicion_fechacreacion')) ?> 
                        <?php echo $this->formHidden($form->get('idrequisicion')) ?>
                    </div>
                    <div class="col-md-6">
                        <?php echo $this->formLabel($form->get('requisicion_folio')) ?>  
                        <?php echo $this->formText($form->get('requisicion_folio')) ?> 
                    </div>
                    <?php echo $this->formHidden($form->get('idsucursalorigen')); ?>
                    <div class="col-md-6">
                        <?php echo $this->formLabel($form->get('sucursal_nombre')) ?>  
                        <?php echo $this->formText($form->get('sucursal_nombre')) ?> 
                    </div>
                    <div class="col-md-6">
                        <?php echo $this->formLabel($form->get('idalmacenorigen')) ?>  
                        <?php echo $this->formSelect($form->get('idalmacenorigen')) ?> 
                    </div>
                    <div class="col-md-6">
                        <?php echo $this->formLabel($form->get('idsucursaldestino')) ?>  
                        <?php echo $this->formSelect($form->get('idsucursaldestino')) ?> 
                    </div>
                    <div class="col-md-6">
                        <?php echo $this->formLabel($form->get('idalmacendestino')) ?>  
                        <?php echo $this->formSelect($form->get('idalmacendestino')) ?> 
                    </div>
                    <div class="col-md-6">
                        <?php echo $this->formLabel($form->get('idconceptosalida')) ?>  
                        <?php echo $this->formSelect($form->get('idconceptosalida')) ?> 
                    </div>
                    <div class="col-md-6">
                        <?php echo $this->formLabel($form->get('requisicion_revisada')) ?>  
                        <?php echo $this->formSelect($form->get('requisicion_revisada')) ?> 
                    </div>
                </div>
                                <div class="row">
                    <div class="form-group">
                        <div class="col-md-6">
                            <label>Creado por</label>
                            <input class="form-control" type="text" value="<?php echo $entity->getUsuarioRelatedByIdusuario()->getUsuarioNombre();?>" readonly="readonly"> 
                        </div>
                        <div class="col-md-6">
                            <label>Auditor</label>
                            <?php  
                                if($entity->getRequisicionRevisada()){
                                    $auditor = $entity->getUsuarioRelatedByIdauditor()->getUsuarioNombre();
                                }else{
                                    $auditor = 'N/D';
                                } 
                            ?>
                            <input class="form-control" type="text" value="<?php echo $auditor;?>" readonly="readonly"> 
                        </div>
                    </div>
                </div>
                
                
                <h3 class="form-section">Productos *</h3><br><br>
                <div class="row">
                    <div class="form-group">
                        <div class="col-md-4 col-md-offset-6">
                            <div class="input-group">
                                <span class="input-group-addon">
                                    <i class="fa fa-search"></i>
                                </span>
                                <input id="idproducto" type="hidden">
                                <input id="unidadmedida_nombre" type="hidden">
                                <input id="producto_autocomplete" class="form-control" type="text">
                            </div>
                        </div>
                        <div class="col-md-1">
                            <button disabled id="producto_add" class="btn grey-mint" type="button">Agregar</button>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <table class="table" id="productos_table">
                            <thead>
                            <th>Tipo</th>
                            <th>Producto</th>
                            <th>Unidad</th>
                            <th>Cantidad</th>
                            <th>Precio unitario</th>
                            <th>subtotal</th>
                            <th>Revisada</th>
                            <th>Opcion</th>
                            </thead>
                            <tbody id="productos_table_tbody">
                                <?php $detalle = new Requisiciondetalle()?>
                                <?php foreach ($requisiciondetalle as $detalle) :?>
                                <tr id="<?php echo $detalle->getIdrequisiciondetalle()?>" idpro="<?php echo $detalle->getIdproducto()?>">
                                    <td>
                                        <?php echo $detalle->getProducto()->getProductoTipo();?>
                                    </td>
                                    <td>
                                        <input type="hidden" name="productos[<?php echo $detalle->getIdrequisiciondetalle()?>][requisiciondetalle_subtotal]" value="<?php echo $detalle->getRequisiciondetalleSubtotal()?>">
                                        <input type="hidden" name="productos[<?php echo $detalle->getIdrequisiciondetalle()?>][preciounitario]" value="<?php echo $detalle->getRequisiciondetallePreciounitario()?>">
                                        <input type="hidden" name="productos[<?php echo $detalle->getIdrequisiciondetalle()?>][idproducto]" value="<?php echo $detalle->getIdproducto()?>">
                                        <?php echo $detalle->getProducto()->getProductoNombre()?>
                                    </td>
                                    <td>
                                        <?php echo $detalle->getProducto()->getUnidadmedida()->getUnidadmedidaNombre()?>
                                    </td>
                                    <td class="pro_cantidad">
                                        <input type="text" name="productos[<?php echo $detalle->getIdrequisiciondetalle()?>][requisiciondetalle_cantidad]" value="<?php echo $detalle->getRequisiciondetalleCantidad()?>"> 
                                    </td>
                                    <td>
                                        <input type="text" name="productos[<?php echo $detalle->getIdrequisiciondetalle()?>][requisiciondetalle_preciounitario]" value="<?php echo $detalle->getRequisiciondetallePreciounitario()?>"> 
                                    </td>
                                    <td class="requisiciondetalle_subtotal">
                                        <?php echo money_format('%+#1.6n',$detalle->getRequisiciondetalleSubtotal())?>
                                    </td>
                                    <td>
                                        <?php if($detalle->getRequisiciondetalleRevisada()) :?>
                                            <input checked type="checkbox" name=productos[<?php echo $detalle->getIdrequisiciondetalle()?>][requisiciondetalle_revisada]>
                                        <?php else :?>
                                            <input type="checkbox" name=productos[<?php echo $detalle->getIdrequisiciondetalle()?>][requisiciondetalle_revisada]>
                                        <?php endif?>
                                    </td>
                                    <?php if($detalle->getProducto()->getProductoTipo()!="simple") {?>
                                    <td>
                                        <a href=javascript:;><i class="fa fa-list"></i></a>
                                    </td>
                                    <?php } ?>
                                    <td>
                                        <a href="javascript:;"><i class="fa fa-trash"></i></a>
                                    </td>
                                </tr>
                                <?php endforeach?>
                            </tbody>
                            <tfoot>
                                <tr>
                                    <td colspan="6"></td>
                                    <td>TOTAL</td>
                                    <?php echo $this->formHidden($form->get('requisicion_total')) ?> 
                                    <td id="total"><?php echo '$'.money_format('%+#1.6n',$entity->getRequisicionTotal())?></td>
                                </tr>
                            </tfoot>
                        </table>
                    </div>
                </div>
                <br>
                <div class="row">
                    <div class="col-md-12">
                        <p>(*)Campos obligatorios</p>
                    </div>
                </div>
            </div>
            <div class="form-actions right">
                <button class="btn blue" id="requisicion_save" type="submit">
                    <i class="fa fa-check"></i>
                    Guardar
                </button>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript" src="/application/custom/js/procesos/requisicion.js"></script>
<script>
    var $form = $('#form_container').requisicion({'idrol':<?php echo $idrol?>});
    $form.edit(<?php echo $anio_activo?>,<?php echo $mes_activo?>);
</script>