<link href="/application/global/plugins/datatables/datatables.min.css" rel="stylesheet" type="text/css" />
<link href="/application/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.css" rel="stylesheet" type="text/css" />
<div id="my_container">
    <h3 class="page-title">Requisición</h3>
    <div class="page-bar">
        <ul class="page-breadcrumb">
            <li>
                <a href="/procesos/requisicion">Requisición</a>
            </li>
        </ul>
    </div>
    <?php foreach ($messages->getSuccessMessages() as $message):?>
        <div class="alert alert-success alert-dismissable">
            <button class="close" aria-hidden="true" data-dismiss="alert" type="button"></button>
            <strong>Exito!</strong>
            <?php echo $message?>
        </div>
    <?php endforeach;?>
    <div class="portlet box " style="border-left-width: 0px; border-bottom-width: 0px; border-right-width: 0px;">
        <div class="portlet-body form">
            <div class="form-body">
                <div class="btn-set pull-right">
                    <a href="/procesos/requisicion/nuevo"><button class="btn default" type="button" style="margin-bottom: 15px;">Nueva requisición</button></a>
                </div>
                <h2>Requisiciones</h2><br>
                
                <table class="table table-striped table-bordered table-hover order-column" id="datatable"  style="border-bottom-width: 0px;">
                    <thead>
                        <tr>
                            <th class="text"> Fecha </th>
                            <th class="text"> Folio </th>
                            <th class="text"> Origen </th>
                            <th class="text"> Destino </th>
                            <th> Revisada </th>
                            <th class="text"> Opciones </th>
                        </tr>
                    </thead>
                    <tbody class="text">
                        <?php $entity= new Requisicion();?>
                        <?php foreach ($collection as $entity) : ?>
                        <?php 
                            if($entity->getRequisicionRevisada()) {
                                $class = 'info';
                                $revisada = 'Revisada';
                            } else {
                                $class = 'danger';
                                $revisada = 'No revisada';
                            }
                        ?>
                        <tr date="<?php echo $entity->getRequisicionFecha('Y/m/d') ?>"  id="<?php echo $entity->getIdrequisicion() ?>">
                                <td><?php echo $entity->getRequisicionFecha('d/m/Y') ?></td>
                                <td><?php echo $entity->getRequisicionFolio() ?></td>
                                <td><?php echo $entity->getSucursalRelatedByIdsucursalorigen()->getSucursalNombre()." - ".$entity->getAlmacenRelatedByIdalmacenorigen()->getAlmacenNombre() ?></td>
                                <td><?php echo $entity->getSucursalRelatedByIdsucursaldestino()->getSucursalNombre()." - ".$entity->getAlmacenRelatedByIdalmacendestino()->getAlmacenNombre() ?></td>
                                <td><span class="label label-sm label-<?php echo $class?>"> <?php echo $revisada ?> </span></td>
                                <td>
                                    <div class="btn-group">
                                        <button class="btn btn-xs green dropdown-toggle" type="button" data-toggle="dropdown" aria-expanded="false"> Acciones
                                            <i class="fa fa-angle-down"></i>
                                        </button>   
                                        <ul class="dropdown-menu" role="menu">
                                            <?php $mostrar=true;
                                            if(UsuarioQuery::create()->filterByIdusuario($idusuario)->findOne()->getIdrol()=="5") {
                                                $detalles= $entity->getRequisiciondetalles();
                                                foreach ($detalles as $detalle) {
                                                    if((bool)$detalle->getRequisiciondetalleRevisada())
                                                        $mostrar=false;
                                                }
                                            } if($mostrar) {?>
                                            <li>
                                                <a href="/procesos/requisicion/editar/<?php echo $entity->getIdrequisicion()?>">
                                                    <i class="fa fa-pencil"></i> Editar </a>
                                            </li>
                                            <?php } ?>
                                            <?php if($idsucursal==$entity->getIdsucursalorigen() && \Application\Dashboard\Controller\IndexController::validateprocessbyinventariomesfordelete($entity->getRequisicionRevisada(),$entity->getRequisicionFecha(), array($entity->getIdalmacenorigen(),$entity->getIdalmacendestino()))):?>
                                            <li>
                                                <a href="javascript:;" class="delete_modal">
                                                    <i class="fa fa-trash"></i> Eliminar </a>
                                            </li>
                                            <?php endif;?>
                                        </ul>
                                    </div>
                                    
                                </td>
                            </tr>                            
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<script src="/application/global/scripts/datatable.js" type="text/javascript"></script>
<script src="/application/global/plugins/datatables/datatables.min.js" type="text/javascript"></script>
<script src="/application/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.js" type="text/javascript"></script>
<script src="/application/custom/js/procesos/requisicion.js" type="text/javascript"></script>	
<!--
<script src="/application/custom/js/catalogo/tablajeria.js" type="text/javascript"></script>
-->
<script>
    var $plugin = $('#my_container').requisicion({'idrol':<?php echo $idrol?>});
    $plugin.list(<?php echo $anio_activo?>,<?php echo $mes_activo?>);
</script>