<style>
    input[type=file]{
        padding-top: 0px;
        padding-left: 0px;
    }
    #productos_table .fa-trash{
        color:red;
    }
</style>
<link rel="stylesheet" type="text/css" href="/application/custom/css/validaciones.css">
<div id="form_container">
    <div class="page-bar">
        <ul class="page-breadcrumb">
            <li>
                <a href="javascript:;">Procesos</a>
                 <i class="fa fa-angle-right"></i>
            </li>
            <li>
                <a href="/procesos/requisicion">Requisicion</a>
                 <i class="fa fa-angle-right"></i>
            </li>
            <li>
                <a href="/procesos/requisicion/nuevo">Registro</a>
            </li>
        </ul>
    </div>
    
    <?php foreach ($messages->getSuccessMessages() as $message): ?>
        <div class="alert alert-success alert-dismissable">
            <button class="close" aria-hidden="true" data-dismiss="alert" type="button"></button>
            <strong>Exito!</strong>
            <?php echo $message ?>
        </div>
    <?php endforeach; ?>

    <?php foreach ($messages->getErrorMessages() as $message): ?>
        <div class="alert alert-danger alert-dismissable">
            <button class="close" aria-hidden="true" data-dismiss="alert" type="button"></button>
            <strong>Error!</strong>
            <?php echo $message ?>
        </div>
    <?php endforeach; ?>
    <?php
    $form->setAttribute('action', '/procesos/requisicion/nuevo');
    echo $this->form()->openTag($form);
    ?>
    <div class="portlet box green" style="border-left-width: 0px; border-bottom-width: 0px; border-right-width: 0px;">
        <div class="portlet-body form">
            <div class="form-body">
                <h3 class="page-title">Requisición - Registro</h3>
                <h3 class="form-section">Información general</h3>
                <div class="row">
                    <?php echo $this->formHidden($form->get('idempresa')); ?>
                    <div class="col-md-6">
                        <?php echo $this->formLabel($form->get('requisicion_fecha')) ?>  
                        <?php echo $this->formText($form->get('requisicion_fecha')) ?> 
                    </div>
                    <div class="col-md-6">
                        <?php echo $this->formLabel($form->get('requisicion_folio')) ?>  
                        <?php echo $this->formText($form->get('requisicion_folio')) ?> 
                    </div>
                    <?php echo $this->formHidden($form->get('idsucursalorigen')); ?>
                    <div class="col-md-6">
                        <?php echo $this->formLabel($form->get('sucursal_nombre')) ?>  
                        <?php echo $this->formText($form->get('sucursal_nombre')) ?> 
                    </div>
                    <div class="col-md-6">
                        <?php echo $this->formLabel($form->get('idalmacenorigen')) ?>  
                        <?php echo $this->formSelect($form->get('idalmacenorigen')) ?> 
                    </div>
                    <div class="col-md-6">
                        <?php echo $this->formLabel($form->get('idsucursaldestino')) ?>  
                        <?php echo $this->formSelect($form->get('idsucursaldestino')) ?> 
                    </div>
                    <div class="col-md-6">
                        <?php echo $this->formLabel($form->get('idalmacendestino')) ?>  
                        <?php echo $this->formSelect($form->get('idalmacendestino')) ?> 
                    </div>
                    <div class="col-md-6">
                        <?php echo $this->formLabel($form->get('idconceptosalida')) ?>  
                        <?php echo $this->formSelect($form->get('idconceptosalida')) ?> 
                    </div>
                    <div class="col-md-6">
                        <?php echo $this->formLabel($form->get('requisicion_revisada')) ?>  
                        <?php echo $this->formSelect($form->get('requisicion_revisada')) ?> 
                    </div>
                </div>
                <h3 class="form-section">Productos *</h3><br><br>
                <div class="row">
                    <div class="form-group">
                        <div class="col-md-4 col-md-offset-6">
                            <div class="input-group">
                                <span class="input-group-addon">
                                    <i class="fa fa-search"></i>
                                </span>
                                <input id="idproducto" type="hidden">
                                <input id="unidadmedida_nombre" type="hidden">
                                <input id="producto_autocomplete" class="form-control" type="text">
                            </div>
                        </div>
                        <div class="col-md-1">
                            <button disabled id="producto_add" class="btn grey-mint" type="button">Agregar</button>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <table class="table" id="productos_table">
                            <thead>
                            <th>Tipo</th>
                            <th>Producto</th>
                            <th>Unidad</th>
                            <th>Cantidad</th>
                            <th>Precio unitario</th>
                            <th>subtotal</th>
                            <th>Revisada</th>
                            <th>Opcion</th>
                            </thead>
                            <tbody id="productos_table_tbody">
                            </tbody>
                            <tfoot>
                                <tr>
                                    <td colspan="6"></td>
                                    <td>TOTAL</td>
                                    <input type="hidden" name="requisicion_total">
                                    <td id="total">$0.00</td>
                                </tr>
                            </tfoot>
                        </table>
                    </div>
                </div>
                <br>
                <div class="row">
                    <div class="col-md-12">
                        <p>(*)Campos obligatorios</p>
                    </div>
                </div>
            </div>
            <div class="form-actions right">
                <button disabled class="btn blue" id="requisicion_save" type="submit">
                    <i class="fa fa-check"></i>
                    Guardar
                </button>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript" src="/application/custom/js/procesos/requisicion.js"></script>
<script>
    var $form = $('#form_container').requisicion();
    $form.new(<?php echo $anio_activo?>,<?php echo $mes_activo?>);
</script>