<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'Application\Module'                               => __DIR__ . '/Module.php',
  'Application\Dashboard\Controller\IndexController' => __DIR__ . '/src/Application/Dashboard/Controller/IndexController.php',
  'Website\Controller\IndexController'               => __DIR__ . '/src/Website/Controller/IndexController.php',
);
