<link href="/application/global/plugins/datatables/datatables.min.css" rel="stylesheet" type="text/css" />
<link href="/application/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.css" rel="stylesheet" type="text/css" />
<div id="my_container">
    <h3 class="page-title">Trabajadores promedio</h3>
    <div class="page-bar">
        <ul class="page-breadcrumb">
            <li>
                <a href="/catalogo/trabajador_promedio">Trabajadores promedio</a>
            </li>
        </ul>
    </div>
    <?php foreach ($messages->getSuccessMessages() as $message):?>
        <div class="alert alert-success alert-dismissable">
            <button class="close" aria-hidden="true" data-dismiss="alert" type="button"></button>
            <strong>Éxito!</strong>
            <?php echo $message?>
        </div>
    <?php endforeach;?>
    <div class="portlet box green" style="border-left-width: 0px; border-bottom-width: 0px; border-right-width: 0px;">
        <div class="portlet-body form">
            <div class="form-body">
                <div class="btn-set pull-right">
                    <a href="/catalogo/trabajador_promedio/nuevo"><button class="btn default" type="button" style="margin-bottom: 15px;">Nuevo registro</button></a>
                </div>
                <table class="table table-striped table-bordered table-hover order-column" id="datatable" style="border-bottom-width: 0px;">
                    <thead>
                        <tr>
                            <th> Año </th>
                            <th> Mes </th>
                            <th> Trabajadores </th>
                            <th> Acciones </th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($collection as $entity) : ?>
                            
                        <?php
                            $mes = $entity->getTrabajadorespromediomes();
                            if($mes == 1)
                                $mes = "Enero";
                            elseif($mes == 2)
                                $mes = "Febrero";
                            elseif($mes == 3)
                                $mes = "Marzo";
                            elseif($mes == 4)
                                $mes = "Abril";
                            elseif($mes == 5)
                                $mes = "Mayo";
                            elseif($mes == 6)
                                $mes = "Junio";
                            elseif($mes == 7)
                                $mes = "Julio";
                            elseif($mes == 8)
                                $mes = "Agosto";
                            elseif($mes == 9)
                                $mes = "Septiembre";
                            elseif($mes == 10)
                                $mes = "Octubre";
                            elseif($mes == 11)
                                $mes = "Noviembre";
                            elseif($mes == 12)
                                $mes = "Diciembre";
                            
                        ?>
                            <tr id="<?php echo $entity->getIdTrabajadorespromedio() ?>">
                                <td><?php echo $entity->getTrabajadorespromedioanio() ?></td>
                                <td><?php echo $mes ?></td>

                                <td><?php echo $entity->getTrabajadorespromediocantidad() ?></td>
                                <td>                                    
                                    <div class="btn-group">
                                        <button class="btn btn-xs green dropdown-toggle" type="button" data-toggle="dropdown" aria-expanded="false"> Acciones
                                            <i class="fa fa-angle-down"></i>
                                        </button>
                                        <ul class="dropdown-menu" role="menu">
                                            <li>
                                                <a href="/catalogo/trabajador_promedio/editar/<?php echo $entity->getIdtrabajadorespromedio()?>">
                                                    <i class="fa fa-pencil"></i> Editar </a>
                                            </li>
                                            
                                            <li>
                                                <a href="javascript:;" class="delete_trabajadorespromedio">
                                                    <i class="fa fa-trash"></i> Eliminar </a>
                                            </li>
                                            
                                        </ul>
                                    </div>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<script src="/application/global/scripts/datatable.js" type="text/javascript"></script>
<script src="/application/global/plugins/datatables/datatables.min.js" type="text/javascript"></script>
<script src="/application/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.js" type="text/javascript"></script>
<script src="/application/custom/js/catalogo/usuario.js" type="text/javascript"></script>	
<script>
    
    var plugin = $('#my_container').usuario();
    $('.delete_trabajadorespromedio').click(function(){
              
        var id = $(this).closest('tr').attr('id');
        var tmpl = [
          // tabindex is required for focus
          ' <div class="modal fade draggable-modal" id="draggable" tabindex="-1" role="basic" aria-hidden="true">',
            '<div class="modal-header">',
              '<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>',
              '<h4 class="modal-title">ADVERTENCIA</h4>', 
            '</div>',
            '<form method="post" action="/catalogo/trabajador_promedio/eliminar/'+id+'">',
              '<div class="modal-body">',
                '<p>¿Estas seguro que deseas eliminar el registro seleccionado?</p>',
              '</div>',
              '<div class="modal-footer">',
                '<a href="#" data-dismiss="modal" class="btn btn-default">Cancelar</a>',
                '<button class="btn btn-danger" type="submit">Eliminar</button>',
              '</div>',
            '</form>',
          '</div>'
        ].join('');
        $(tmpl).modal();
      });
</script>