<h3 class="page-title"><?php echo $form->get('plantillatablajeria_nombre')->getValue()?></h3>
<div class="page-bar">
    <ul class="page-breadcrumb">
        <li>
            <a href="/catalogo/tablajeria">Tablajerias</a>
            <i class="fa fa-angle-right"></i>
        </li>
        <li>
            <span><span><?php echo $form->get('plantillatablajeria_nombre')->getValue()?></span></span>
        </li>
    </ul>
</div>
<?php foreach ($messages->getSuccessMessages() as $message):?>
    <div class="alert alert-success alert-dismissable">
        <button class="close" aria-hidden="true" data-dismiss="alert" type="button"></button>
        <strong>Éxito!</strong>
        <?php echo $message?>
    </div>
<?php endforeach;?>

<?php foreach ($messages->getErrorMessages() as $message):?>
    <div class="alert alert-danger alert-dismissable">
        <button class="close" aria-hidden="true" data-dismiss="alert" type="button"></button>
        <strong>Error!</strong>
        <?php echo $message?>
        
    </div>
<?php endforeach;?>
<?php
    $form->setAttribute('action', '/catalogo/tablajeria/editar/'.$form->get('idplantillatablajeria')->getValue());
    echo $this->form()->openTag($form);
?>
<div class="portlet box green" style="border-left-width: 0px; border-bottom-width: 0px; border-right-width: 0px;">
    <div class="portlet-body form">
        <div class="form-body">
            <h3 class="form-section">Información general</h3>
            <div class="row">
                    <?php echo  $this->formHidden($form->get('idempresa'));?>
                <div class="col-md-6">
                    <?php echo $this->formLabel($form->get('plantillatablajeria_nombre')); ?>  
                    <?php echo  $this->formText($form->get('plantillatablajeria_nombre'));?>
                </div>
                <div class="col-md-6">
                    <?php echo $this->formLabel($form->get('idproducto')) ?>  
                    <?php echo  $this->formSelect($form->get('idproducto'))?>
                </div>
                <div class="col-md-12">
                    <?php echo $this->formLabel($form->get('plantillatablajeria_descripcion')) ?>  
                    <?php echo  $this->formTextarea($form->get('plantillatablajeria_descripcion'))?>
                </div>
            </div>
            <br>
            <div class="row">
                <div class="col-md-12">
                    <p>(*)Campos obligatorios</p>
                </div>
            </div>
        </div>
        <div class="form-actions right">
            <button class="btn blue" type="submit">
                <i class="fa fa-check"></i>
                Guardar
            </button>
        </div>
    </div>
</div>
<?php  echo $this->form()->closeTag(); ?>