<link href="/application/global/plugins/datatables/datatables.min.css" rel="stylesheet" type="text/css" />
<link href="/application/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.css" rel="stylesheet" type="text/css" />
<div id="my_container">
    <h3 class="page-title">Orden de tablajeria</h3>
    <div class="page-bar">
        <ul class="page-breadcrumb">
            <li>
                <a href="javascript:;">Procesos</a>
                 <i class="fa fa-angle-right"></i>
            </li>
            <li>
                <a href="/procesos/tablajeria">Orden de tablajeria</a>
            </li>
        </ul>
    </div>
    <?php foreach ($messages->getSuccessMessages() as $message):?>
        <div class="alert alert-success alert-dismissable">
            <button class="close" aria-hidden="true" data-dismiss="alert" type="button"></button>
            <strong>Éxito!</strong>
            <?php echo $message?>
        </div>
    <?php endforeach;?>
    <div class="portlet box " style="border-left-width: 0px; border-bottom-width: 0px; border-right-width: 0px;">
        <div class="portlet-body form">
            <div class="form-body">
                <div class="btn-set pull-right">
                    <a href="/procesos/tablajeria/nuevo"><button class="btn default" type="button" style="margin-bottom: 15px;">NUEVO REGISTRO</button></a>
                </div>                
                <table class="table table-striped table-bordered table-hover order-column" id="datatable"  style="border-bottom-width: 0px;">
                    <thead>
                        <tr>
                            <th> Fecha </th>
                            <th> Folio </th>
                            <th> Producto </th>
                            <th> Revisada </th>
                            <th> Opciones </th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php $entity = new Ordentablajeria()?>
                        <?php foreach ($collection as $entity) : ?>
                            <?php
                            if($entity->getOrdentablajeriaRevisada()) {
                                $class = 'info';
                                $revisada = 'Revisada';
                            } else {
                                $class = 'danger';
                                $revisada = 'No revisada';
                            }?>
                            <tr date="<?php echo $entity->getOrdentablajeriaFecha('Y/m/d') ?>" id="<?php echo $entity->getIdordentablajeria()?>">
                                <td><?php echo $entity->getOrdentablajeriaFecha('d/m/Y') ?></td>
                                <td><?php echo $entity->getOrdentablajeriaFolio() ?></td>
                                <td><?php echo $entity->getProducto()->getProductoNombre() ?></td>
                                <td><span class="label label-sm label-<?php echo $class?>"> <?php echo $revisada ?> </span></td>
                                <td>
                                    <div class="btn-group">
                                        <button class="btn btn-xs green dropdown-toggle" type="button" data-toggle="dropdown" aria-expanded="false"> Acciones
                                            <i class="fa fa-angle-down"></i>
                                        </button>
                                        <ul class="dropdown-menu" role="menu">
                                            <li>
                                                <a href="/procesos/tablajeria/editar/<?php echo $entity->getIdordentablajeria()?>">
                                                    <i class="fa fa-pencil"></i> Editar </a>
                                            </li>
                                            <?php if(\Application\Dashboard\Controller\IndexController::validateprocessbyinventariomesfordelete($entity->getOrdentablajeriaRevisada(),$entity->getOrdentablajeriaFecha(), array($entity->getIdalmacenorigen(),$entity->getIdalmacendestino()))):?>
                                            <li>
                                                <a href="javascript:;" class="delete_modal">
                                                    <i class="fa fa-trash"></i> Eliminar </a>
                                            </li>
                                            <?php endif;?>
                                        </ul>
                                    </div>
                                    
                                </td>
                            </tr>                            
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
        
    </div>
</div>

<script src="/application/global/scripts/datatable.js" type="text/javascript"></script>
<script src="/application/global/plugins/datatables/datatables.min.js" type="text/javascript"></script>
<script src="/application/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.js" type="text/javascript"></script>
<script src="http://cdn.datatables.net/plug-ins/1.10.13/sorting/date-eu.js" type="text/javascript"></script>
<script src="/application/custom/js/procesos/ordentablajeria.js" type="text/javascript"></script>
<script>    
    var plugin = $('#my_container').ordentablajeria({'idrol':<?php echo $idrol?>});
    plugin.list(<?php echo $anio_activo?>,<?php echo $mes_activo?>);
</script>


