<link rel="stylesheet" type="text/css" href="/application/custom/css/validaciones.css">
<style>
    #productos_table .fa-trash{
        color:red;
    }
    #productos_table input[readonly]{
        background: #EEF1F5;
        
    }
    #productos_table input{
        width: 80px;
    }
</style>
<div id="form_container">
<h3 class="page-title">Registro orden de tablajeria</h3>
<div class="page-bar">
    <ul class="page-breadcrumb">
        <li>
            <a href="javascript:;">Procesos</a>
             <i class="fa fa-angle-right"></i>
        </li>
        <li>
            <a href="/procesos/tablajeria">Orden de tablajeria</a>
            <i class="fa fa-angle-right"></i>
        </li>
        <li>
            <a href="/procesos/tablajeria/nuevo">Registro</a>
        </li>
    </ul>
</div>
<?php foreach ($messages->getSuccessMessages() as $message):?>
    <div class="alert alert-success alert-dismissable">
        <button class="close" aria-hidden="true" data-dismiss="alert" type="button"></button>
        <strong>Éxito!</strong>
        <?php echo $message?>
    </div>
<?php endforeach;?>
<?php
    $form->setAttribute('action', '/procesos/tablajeria/nuevo');
    echo $this->form()->openTag($form);
?>
    <div class="portlet box green" style="border-left-width: 0px; border-bottom-width: 0px; border-right-width: 0px;">
        <div class="portlet-body form">
            <div class="form-body">
                <h3 class="form-section">Información general</h3>
                <div class="row">
                    <div class="form-group">
                        <div class="col-md-6">
                            <?php echo $this->formLabel($form->get('ordentablajeria_fecha')) ?>  
                            <?php echo $this->formText($form->get('ordentablajeria_fecha')) ?> 
                        </div>
                        <div class="col-md-6">
                            <?php echo $this->formLabel($form->get('ordentablajeria_folio')) ?>  
                            <?php echo $this->formText($form->get('ordentablajeria_folio')) ?> 
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-6">
                            <?php echo $this->formHidden($form->get('idproducto')); ?> 
                            <?php echo $this->formHidden($form->get('producto_unidadmedida')); ?>  
                            <?php echo $this->formLabel($form->get('idproducto_autocomplete')) ?>  
                            <?php echo $this->formText($form->get('idproducto_autocomplete')) ?> 
                        </div>
                        <div class="col-md-3">
                            <?php echo $this->formLabel($form->get('ordentablajeria_pesobruto')) ?>  
                            <?php echo $this->formText($form->get('ordentablajeria_pesobruto')) ?> 
                        </div>
                        <div class="col-md-3">
                            <input type="hidden" name="pesoporcion">
                            <?php echo $this->formLabel($form->get('ordentablajeria_numeroporciones')) ?>  
                            <?php echo $this->formText($form->get('ordentablajeria_numeroporciones')) ?> 
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-6">
                            <?php echo $this->formLabel($form->get('ordentablajeria_preciokilo')) ?>  
                            <?php echo $this->formText($form->get('ordentablajeria_preciokilo')) ?> 
                        </div>
                        <div class="col-md-6">
                            <?php echo $this->formLabel($form->get('ordentablajeria_totalbruto')) ?>  
                            <?php echo $this->formText($form->get('ordentablajeria_totalbruto')) ?> 
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-6">
                            <?php echo $this->formLabel($form->get('ordentablajeria_inyeccion')) ?>  
                            <?php echo $this->formText($form->get('ordentablajeria_inyeccion')) ?> 
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="form-group">
                        <div class="col-md-6">
                            <?php echo $this->formLabel($form->get('idalmacenorigen')) ?>  
                            <?php echo $this->formSelect($form->get('idalmacenorigen')) ?> 
                        </div>
                        <div class="col-md-6">
                            <?php echo $this->formLabel($form->get('idalmacendestino')) ?>  
                            <?php echo $this->formSelect($form->get('idalmacendestino')) ?> 
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="portlet box green" style="border-left-width: 0px; border-bottom-width: 0px; border-right-width: 0px;">
        <div class="portlet-body form">
            <div class="form-body">
                <h3 class="form-section">Tablajeado</h3>
                <div class="row">
                    <div class="form-group">
                        <div class="col-md-6">
                            <?php echo $this->formLabel($form->get('ordentablajeria_pesoneto')) ?>  
                            <?php echo $this->formText($form->get('ordentablajeria_pesoneto')) ?> 
                        </div>
                        <div class="col-md-6">
                            <?php echo $this->formLabel($form->get('ordentablajeria_precioneto')) ?>  
                            <?php echo $this->formText($form->get('ordentablajeria_precioneto')) ?> 
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-6">
                            <?php echo $this->formLabel($form->get('ordentablajeria_merma')) ?>  
                            <?php echo $this->formText($form->get('ordentablajeria_merma')) ?> 
                        </div>
                        <div class="col-md-6">
                            <?php echo $this->formLabel($form->get('ordentablajeria_porcentajemerma')) ?>  
                            <?php echo $this->formText($form->get('ordentablajeria_porcentajemerma')) ?> 
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-6">
                            <?php echo $this->formLabel($form->get('ordentablajeria_aprovechamiento')) ?>  
                            <?php echo $this->formText($form->get('ordentablajeria_aprovechamiento')) ?> 
                        </div>
                        <div class="col-md-6">
                            <?php echo $this->formLabel($form->get('ordentablajeria_revisada')) ?>  
                            <?php echo $this->formSelect($form->get('ordentablajeria_revisada')) ?> 
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="portlet box green" style="border-left-width: 0px; border-bottom-width: 0px; border-right-width: 0px;">
        <div class="portlet-body form">
            <div class="form-body">
                <h3 class="form-section">Productos</h3>
                <div class="row">
                    <div class="form-group">
                        
                        <div class="col-md-4 col-md-offset-6">
                            <div class="input-group">
                                <span class="input-group-addon">
                                    <i class="fa fa-search"></i>
                                </span>
                                <input name="idproductoautocomplete" type="hidden" disabled>
                                <input name="productoautocomplete_unidadmedida" type="hidden" disabled>
                                <input name="producto_autocomplete" class="form-control" type="text" disabled>
                            </div>
                        </div>
                        <div class="col-md-1">
                            <button disabled id="producto_add" class="btn grey-mint" type="button">Agregar</button>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="table-responsive">
                        <table class="table" id="productos_table">
                        <thead>
                            <th>Producto</th>
                            <th>Cantidad</th>
                            <th>Unidad medida</th>
                            <th>Peso porción (Kilos)</th>
                            <th>Peso total</th>
                            <th>Precio porción</th>
                            <th>Importe</th>
                            <th>Revisada</th>
                            <th>Opciones</th>
                        </thead>
                        <tbody>
                            
                        </tbody>
                        <tfoot>
                            <tr>
         
                                <td colspan="4">Total</td>
                                <td style="padding-left: 8px;" colspan="2" id="peso_total">0</td>
                                <td colspan="4" style="padding-left: 8px;" id="importe_total">$0.00</td>
                            </tr> 
                        </tfoot>
                    </table>
                    </div>
                </div>
                
            </div>
            <div class="form-actions right">
                <button type="submit" style="display: none"></button>
                <a class="btn blue submit"
                   <i class="fa fa-check"></i>
                    Guardar
                </a>
            </div>
        </div>
    </div>
<?php  echo $this->form()->closeTag(); ?>
</div>
<script type="text/javascript" src="/application/custom/js/procesos/ordentablajeria.js"></script>
<script>
    var $form = $('#form_container').ordentablajeria({'idrol':<?php echo $idrol?>});
    $form.new(<?php echo $anio_activo?>,<?php echo $mes_activo?>,<?php echo $almacenes?>);
</script>
