<link rel="stylesheet" type="text/css" href="/application/custom/css/validaciones.css">

<h3 class="page-title">Registro orden de tablajeria</h3>
<div class="page-bar">
    <ul class="page-breadcrumb">
        <li>
            <a href="/catalogo/tablajeria">Tablajerias</a>
            <i class="fa fa-angle-right"></i>
        </li>
        <li>
            <span>Registro</span>
        </li>
    </ul>
</div>
<?php foreach ($messages->getSuccessMessages() as $message):?>
    <div class="alert alert-success alert-dismissable">
        <button class="close" aria-hidden="true" data-dismiss="alert" type="button"></button>
        <strong>Éxito!</strong>
        <?php echo $message?>
    </div>
<?php endforeach;?>
<?php
    $form->setAttribute('action', '/catalogo/tablajeria/nuevo');
    echo $this->form()->openTag($form);
?>
    <div class="portlet box green" style="border-left-width: 0px; border-bottom-width: 0px; border-right-width: 0px;">
        <div class="portlet-body form">
            <div class="form-body">
                <h3 class="form-section">Información general</h3>
                <div class="row">
                    <?php echo  $this->formHidden($form->get('idordentablajeria'));?>
                    <div class="form-group col-md-12">
                        <div class="col-md-2">
                            <?php echo $this->formLabel($form->get('ordentablajeria_fecha')); ?>  
                        </div>
                        <div class="col-md-4">
                            <?php echo  $this->formText($form->get('ordentablajeria_fecha'));?>
                        </div>
                        <div class="col-md-2">
                            <?php echo $this->formLabel($form->get('ordentablajeria_folio')) ?>  
                        </div>
                        <div class="col-md-4">
                            <?php echo  $this->formText($form->get('ordentablajeria_folio'))?>
                        </div>
                    </div>
                    <div class="form-group col-md-12">
                        <div class="col-md-2 ">
                            <?php echo $this->formHidden($form->get('idproducto')); ?>  
                            <?php echo $this->formLabel($form->get('idproducto_autocomplete')); ?>  
                        </div>
                        <div class="col-md-4">
                            
                            <div class="input-group">
                                <input type="hidden" id="idproducto">
                                <span class="input-group-addon">
                                    <i class="fa fa-search"></i>
                                </span>
                                 <?php echo $this->formText($form->get('idproducto_autocomplete')); ?>  

                            </div>
                        </div>
                        
                        <div class="col-md-2">
                            <?php echo $this->formLabel($form->get('ordentablajeria_pesobruto')); ?>  
                        </div>
                        <div class="col-md-2">
                            <?php echo  $this->formText($form->get('ordentablajeria_pesobruto'));?>
                        </div>
                        <div class="col-md-2">
                            <?php echo  $this->formText($form->get('ordentablajeria_numeroporciones'));?>
                        </div>
                    </div>
                    <div class="form-group col-md-12">
                        <div class="col-md-2">
                            <?php echo $this->formLabel($form->get('ordentablajeria_preciokilo')); ?>  
                        </div>
                        <div class="col-md-4">
                            <?php echo  $this->formText($form->get('ordentablajeria_preciokilo'));?>
                        </div>
                        <div class="col-md-2">
                            <?php echo $this->formLabel($form->get('ordentablajeria_precioneto')) ?>  
                        </div>
                        <div class="col-md-4">
                            <?php echo  $this->formText($form->get('ordentablajeria_precioneto'))?>
                        </div>
                    </div>
                    <div class="form-group col-md-12">
                        <div class="col-md-2">
                            <?php echo $this->formLabel($form->get('ordentablajeria_inyeccion')); ?>  
                        </div>
                        <div class="col-md-4">
                            <?php echo  $this->formText($form->get('ordentablajeria_inyeccion'));?>
                        </div>
                    </div>
                    <div class="form-group col-md-12">
                        <div class="col-md-2">
                            <?php echo $this->formLabel($form->get('idalmacenorigen')); ?>  
                        </div>
                        <div class="col-md-4">
                            <?php echo  $this->formSelect($form->get('idalmacenorigen'));?>
                        </div>
                        <div class="col-md-2">
                            <?php echo $this->formLabel($form->get('idalmacendestino')) ?>  
                        </div>
                        <div class="col-md-4">
                            <?php echo  $this->formSelect($form->get('idalmacendestino'))?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="portlet box green" style="border-left-width: 0px; border-bottom-width: 0px; border-right-width: 0px;">
        <div class="portlet-body form">
            <div class="form-body">
                <h3 class="form-section">Tablajeando</h3>
                <div class="row">
                        <div class="form-group col-md-12">
                            <div class="col-md-2">
                                <?php echo $this->formLabel($form->get('ordentablajeria_pesoneto')); ?>  
                            </div>
                            <div class="col-md-4">
                                <?php echo  $this->formText($form->get('ordentablajeria_pesoneto'));?>
                            </div>
                            <div class="col-md-2">
                                <?php echo $this->formLabel($form->get('ordentablajeria_precioneto')) ?>  
                            </div>
                            <div class="col-md-4">
                                <?php echo  $this->formText($form->get('ordentablajeria_precioneto'))?>
                            </div>
                        </div>
                        <div class="form-group col-md-12">
                            <div class="col-md-2">
                                <?php echo $this->formLabel($form->get('ordentablajeria_merma')); ?>  
                            </div>
                            <div class="col-md-4">
                                <?php echo  $this->formText($form->get('ordentablajeria_merma'));?>
                            </div>
                            <div class="col-md-2">
                                <?php echo $this->formLabel($form->get('ordentablajeria_porcentajemerma')) ?>  
                            </div>
                            <div class="col-md-4">
                                <?php echo  $this->formText($form->get('ordentablajeria_porcentajemerma'))?>
                            </div>
                        </div>

                        <div class="form-group col-md-12">
                            <div class="col-md-2">
                                <?php echo $this->formLabel($form->get('ordentablajeria_aprovechamiento')); ?>  
                            </div>
                            <div class="col-md-4">
                                <?php echo  $this->formText($form->get('ordentablajeria_aprovechamiento'));?>
                            </div>
                            <div class="col-md-2">
                                <?php echo $this->formLabel($form->get('ordentablajeria_revisada')) ?>  
                            </div>
                            <div class="col-md-4">
                                <?php echo  $this->formSelect($form->get('ordentablajeria_revisada'))?>
                            </div>
                        </div>

                    </div>
            </div>
        </div>
    </div>
    <div class="portlet box green" style="border-left-width: 0px; border-bottom-width: 0px; border-right-width: 0px;">
        <div class="portlet-body form">
            <div class="form-body">
                <h3 class="form-section">Productos</h3>
                <div class="row">
                    <div class="form-group">
                        <div class="col-md-5 col-md-offset-6">
                            <div class="input-group">
                                <span class="input-group-addon">
                                    <i class="fa fa-search"></i>
                                </span>
                                <input id="idproductoTabla" type="hidden">
                                <input name="producto_autocompleteTabla" class="form-control" type="text">
                            </div>
                        </div>
                        <div class="col-md-1">
                            <button disabled id="producto_add" class="btn grey-mint" type="button">Agregar</button>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <table class="table" id="productos_table">
                        <thead>
                            <th>Producto</th>
                            <th>Cantidad</th>
                            <th>Unidad medida</th>
                            <th>Peso porción</th>
                            <th>Peso total</th>
                            <th>Precio porción</th>
                            <th>Importe</th>
                            <th>Revisada</th>
                            <th>Almacen</th>
                            <th>Opciones</th>
                        </thead>
                        <tbody>

                        </tbody>
                        <tfoot>
                            
                        </tfoot>
                    </table>
                </div>
                
            </div>
            <div class="form-actions right">
                <button class="btn blue" id="btnSubmit" type="submit">
                    <i class="fa fa-check"></i>
                    Guardar
                </button>
            </div>
        </div>
    </div>
<?php  echo $this->form()->closeTag(); ?>

<script type="text/javascript" src="/application/custom/js/procesos/ordentablajeria.js"></script>

