<script src="/website/js/servicios.js"></script>
<script src="/website/js/jquery-ui.js"></script>
<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">

<script src="/website/js/responsiveMap.js"></script>

<div class="row bot">
        <img class="img-responsive img-index" src="/website/img/banners/accounting1.jpg" alt="" style="height: 499px;">
</div>

<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <h5>Nuestros servicios de asesoría se adaptan a prácticamente cualquier tipo de empresa, entre nuestros clientes se encuentran: <b>Restaurantes, Bares, Hoteles, Constructoras, Comercializadoras, Productoras, entre otros.</b></h5>
 
        </div>
    </div>
    <div class="row top">
        <div class="hidden-xs">
            <div style="position: relative;">

                <img class="img-responsive img-center img-100" id="imgTransportes" src="/website/img/servicios/servicios_1.jpg"  usemap="#mapTransportes" alt="" />
                <div id="detalleMaritimo">
                    <div class="detalle-content">
                        <span id="maritimoClose" class="glyphicon glyphicon-remove pull-right icon-close" aria-hidden="true"></span>
                        <div class="content">
                            <br>
                            <br>
                            <br>
                            Para conocer la viabilidad del proyecto, así como el retorno de inversión.
                        </div>
                    </div>
                </div>
                <div id="detalleTerrestre">
                    <div class="detalle-content">
                        <span id="terrestreClose"class="glyphicon glyphicon-remove pull-right icon-close" aria-hidden="true"></span>
                        <div class="content">
                            <br>
                            <br>
                            <br>
                            A través de la revisión diaria de documentos de entradas y salidas, cédulas de costos y monitoreo de parámetros.
                        </div>
                    </div>
                    
                </div>
                <div id="detalleAereo">
                    <div class="detalle-content">
                        <span id="aereoClose"class="glyphicon glyphicon-remove pull-right icon-close" aria-hidden="true"></span>
                        <div class="content">
                            <br>
                            <br>
                            <br>
                            A través de la revisión de perfiles del personal actual con el objetivo de determinar salida de personal innecesario o que no aporta a la empresa, así como la asignación de responsabilidades de acuerdo a las mejores prácticas.
                        </div>
                    </div>
                    
                </div>
            </div>
            <map name="mapTransportes">
                <area  id="btnMaritimo"  shape="rect" coords="0,0,321,428"        />
                <area  id="btnAereo"     shape="rect" coords="321,0,640,428"      />
                <area  id="btnTerrestre" shape="rect" coords="640,0,959,428"     />
            </map>
        </div>
        <div class="hidden visible-xs">
            <img class="img-responsive col-xs-10 col-xs-offset-1 " id="imgMaritimoM" src="/website/img/servicios/diseño_planes.jpg" usemap="#maritimoM" alt="" />
            <div class="col-xs-10 col-xs-offset-1">
                <div id="detalleMaritimoM" class="col-xs-12 " >
                    <span id="maritimoMClose" class="glyphicon glyphicon-remove pull-right top " ></span>
                    <div class="col-xs-12 row">
                        <div class="content" style="padding-bottom: 20px; text-align:left">
                            <br>
                            <br>
                            <br>
                            Para conocer la viabilidad del proyecto, así como el retorno de inversión.
                        </div>
                    </div>
                </div>
            </div>
            <map name="maritimoM">
                <area id="btnMaritimoM" alt="" title=""  shape="rect" coords="1,0,501,670"  target="_self"    />
            </map>
            <img class="img-responsive col-xs-10 col-xs-offset-1 top img-rounded " 	id="imgAereoM" src="/website/img/servicios/reingenieria.jpg"  usemap="#aereoM" alt="" />

            <div class="col-xs-10 col-xs-offset-1">
                <div id="detalleAereoM" class="col-xs-12 " >
                    <span id="aereoMClose" class="glyphicon glyphicon-remove pull-right top " ></span>
                    <div class="col-xs-12">
                        <div class="content" style="padding-bottom: 20px; text-align:left">
                       
                            A través de la revisión diaria de documentos de entradas y salidas, cédulas de costos y monitoreo de parámetros.
                        </div>
                    </div>
                </div>
            </div>

            <map name="aereoM">
                <area id="btnAereoM" alt="" title=""  shape="rect" coords="1,0,501,670"  target="_self"    />
            </map>
            <img class="img-responsive col-xs-10 col-xs-offset-1 top img-rounded "  id="imgTerrestreM" src="/website/img/servicios/control_costos.jpg"  usemap="#terrestreM" alt="" />

            <div class="col-xs-10 col-xs-offset-1">
                <div id="detalleTerrestreM" class="col-xs-12 " >
                    <span id="terrestreMClose" class="glyphicon glyphicon-remove pull-right top " ></span>
                    <div class="col-xs-12">
                        <div class="content" style="padding-bottom: 20px; text-align:left">
                           
                            A través de la revisión de perfiles del personal actual con el objetivo de determinar salida de personal innecesario o que no aporta a la empresa, así como la asignación de responsabilidades de acuerdo a las mejores prácticas.
                        </div>
                    </div>
                </div>
            </div>
            <map name="terrestreM">
                <area id="btnTerrestreM" alt="" title=""  shape="rect" coords="1,0,501,670"  target="_self"    />
            </map>
        </div>

    </div>

    <div class="row top">
        <div class="hidden-xs">
            <div style="position: relative;">
                  <img class="img-responsive img-center img-100" id="imgLogistica" src="/website/img/servicios/servicios_2.jpg" usemap="#mapLogistica" alt="" >	
                <div id="detalleAduana">
                    <div class="detalle-content">
                        <span id="aduanaClose"class="glyphicon glyphicon-remove pull-right icon-close" aria-hidden="true"></span>
                        <div class="content">
                            <br>
                            <br>
                            <br>
                           A través de conteos cíclicos y mensuales para determinación de faltantes por negligencia, dolo o mal manejo de la mercancía, todo esto vinculado con las recetas técnicas, las cuales son validadas en campo por nuestro personal especializado en el giro.
                    </div>
                     

                </div>
                <div id="detalleLogistica">
                    <div class="detalle-content">
                        <span id="logisticaClose"class="glyphicon glyphicon-remove pull-right icon-close" aria-hidden="true"></span>
                        <div class="content">
                            <br>
                            <br>
                            <br>
                            A través de la captura de cuentas bancarias, caja chica, desde los ingresos de ventas diarias y aportaciones de socios hasta las compras y gastos de la operación diaria, todo consolidado en un reporte sencillo de interpretar y completamente consistente con los costos e inventarios, así como las cuentas por pagar y cobrar.                        </div>

                        </div>
                    </div>      
                </div>
                <div id="detalleSeguro">
                    <div class="detalle-content">
                        <span id="seguroClose"class="glyphicon glyphicon-remove pull-right icon-close" aria-hidden="true"></span>
                        <div class="content">
                            <br>
                            <br>
                            <br>
                            A través de la captura de cuentas bancarias, caja chica, desde los ingresos de ventas diarias y aportaciones de socios hasta las compras y gastos de la operación diaria, todo consolidado en un reporte sencillo de interpretar y completamente consistente con los costos e inventarios, así como las cuentas por pagar y cobrar.                       
                        </div>
                    </div>
                </div>
            </div>
            <map name="mapLogistica">
                <area id="btnAduana" 	alt="" shape="rect" coords="0,0,321,428"      />
                <area id="btnSeguro"    alt="" shape="rect" coords="321,0,640,428"      />
                <area id="btnLogistica"	alt="" shape="rect" coords="640,0,959,428"     />
            </map>
        </div>
    
        <div class="hidden visible-xs">
                            <img class="img-responsive col-xs-10 col-xs-offset-1 img-rounded " id="imgAduanaM " src="/website/img/servicios/control_inventarios.jpg"  usemap="#aduanaM" alt="" />

            <div class="col-xs-10 col-xs-offset-1">
                <div id="detalleAduanaM" class="col-xs-12 " >
                    <span id="aduanaMClose" class="glyphicon glyphicon-remove pull-right top " ></span>
                    <div class="col-xs-12">
                         <div class="content" style="padding-bottom: 20px; text-align:left">
                   
                            A través de conteos cíclicos y mensuales para determinación de faltantes por negligencia, dolo o mal manejo de la mercancía, todo esto vinculado con las recetas técnicas, las cuales son validadas en campo por nuestro personal especializado en el giro. 
                        </div>
                    </div>
                    
                </div>
            </div>
            <map name="aduanaM">
                <area  id="btnAduanaM" shape="rect" coords="1,0,501,670"  target="_self"    />
            </map>
                            <img class="img-responsive col-xs-10 col-xs-offset-1 img-rounded " id="imgAduanaM " src="/website/img/servicios/control_efectivo.jpg"  usemap="#seguroM" alt="" />

            <div class="col-xs-10 col-xs-offset-1">
                <div id="detalleSeguroM" class="col-xs-12 " >
                    <span id="seguroMClose" class="glyphicon glyphicon-remove pull-right top " ></span>
                    <div class="col-xs-12">
                        <div class="content" style="padding-bottom: 20px; text-align:left">
                            
                            A través de la captura de cuentas bancarias, caja chica, desde los ingresos de ventas diarias y aportaciones de socios hasta las compras y gastos de la operación diaria, todo consolidado en un reporte sencillo de interpretar y completamente consistente con los costos e inventarios, así como las cuentas por pagar y cobrar. 
                        </div>
                    </div>
                    
                </div>
            </div>
            <map name="seguroM">
                <area  id="btnSeguroM" shape="rect" coords="1,0,501,670"  target="_self"    />
            </map>

            <map name="logisticaM">
                <area  id="btnLogisticaM" shape="rect" coords="1,0,501,670"  target="_self"    />
            </map>
        </div>
        <div class="row" >
        <div class="col-xs-10 col-xs-offset-1 col-md-12 col-md-offset-0" style=" margin-top: 20px">
        <h4><b>¿Cómo logramos el control de estos 3 puntos críticos (flujo, costos e inventarios)? </b></h4>
        <p>A través de <b>AERSA CFCI</b> , nuestra plataforma web compatible con cualquier punto de venta, sistema operativo o dispositivo.</p><p>Nuestra manera de trabajar consiste en un periodo de implementación, el cual puede durar de 4 a 6 meses, el cual, una vez concluido puede tener dos caminos:</p>
        <ol style="padding-left: 15px;">
            <li>Formar una auditoría interna, es decir, usted decide el personal que dará seguimiento a los controles y auditoría, el cual será capacitado y contará con soporte de AERSA.</li>
            <li>AERSA se encarga de la auditoría de manera externa.</li>
        </ol>
        <p>¿Cómo saber si mi empresa de servicios necesita los servicios de AERSA y cómo puedo cotizarlos? <a href="/diagnostico" style="color:blue">Llene este breve cuestionario</a></p>   
            
        </div>
        </div>
    </div>
</div>
<script>

    $(document).ready(function (e) {
        $('img[usemap]').rwdImageMaps();
    });


</script>