<div class="portlet light portlet-fit ">
    <div class="portlet-title">
        <div class="caption">
            <h2>Compras</h2>
        </div>
    </div>
    <div class="portlet-body">
        <div class="table-toolbar">
            <div class="row">
            </div>
        </div>
        <div id="sample_editable_1_wrapper" class="dataTables_wrapper no-footer">
            <div class="row">
                <div class="col-md-6 col-sm-6">
                    <div class="dataTables_length" id="sample_editable_1_length">
                        <label> 
                            Mostrar <select name="sample_editable_1_length" aria-controls="sample_editable_1" class="form-control input-sm input-xsmall input-inline">
                                <option value="5">5</option>
                                <option value="15">15</option>
                                <option value="20">20</option>
                                <option value="-1">All</option>
                            </select> registros</label>
                    </div>
                </div>
                <div class="col-md-6 col-sm-6">
                    <div id="sample_editable_1_filter" class="dataTables_filter">
                        <a href="compra/nuevoregistro"><button style="float: right" class="btn default"> Nueva compra</button></a>
                    </div>
                </div>
            </div>
            <div class="table-scrollable">
                <table id="sample_editable_1" class="table table-striped table-hover table-bordered dataTable no-footer" role="grid" aria-describedby="sample_editable_1_info">
                    <thead>
                        <tr role="row">
                            <th class="sorting" tabindex="0" aria-controls="sample_editable_1" rowspan="1" colspan="1" style="width: 122px;" aria-label=" Full Name : activate to sort column ascending"> Fecha</th>
                            <th class="sorting" tabindex="0" aria-controls="sample_editable_1" rowspan="1" colspan="1" style="width: 122px;" aria-label=" Points : activate to sort column ascending"> Proveedor </th>
                            <th class="sorting" tabindex="0" aria-controls="sample_editable_1" rowspan="1" colspan="1" style="width: 122px;" aria-label=" Notes : activate to sort column ascending"> Tipo </th>
                            <th class="sorting" tabindex="0" aria-controls="sample_editable_1" rowspan="1" colspan="1" style="width: 122px;" aria-label=" Notes : activate to sort column ascending"> Total </th>
                            <th class="sorting" tabindex="0" aria-controls="sample_editable_1" rowspan="1" colspan="1" style="width: 122px;" aria-label=" Notes : activate to sort column ascending"> Revisada </th>
                            <th class="sorting" tabindex="0" aria-controls="sample_editable_1" rowspan="1" colspan="1" style="width: 122px;" aria-label=" Edit : activate to sort column ascending"> Opciones </th>
                        </tr>
                    </thead>
<!--                    CUERPO DE LA TABLA-->
                    <?php foreach ($collection as $entity) : ?>

                                <tr id="<?php echo $entity->getIdcompra() ?>">
                                <td><?php echo $entity->getCompraFechacompra() ?></td>
                                <td><?php echo $entity->getProveedor()->getProveedorNombrecomercial()?></td>
                                <td><?php echo $entity->getCompratipo()?></td>
                                <td><?php echo $entity->getCompraTotal()?></td>
                                <td><?php
                                        $revisada = $entity->getCompraRevisada();
                                            if($revisada == 1){
                                                echo "Revisada";
                                            }else{
                                                echo "No revisada";
                                            }?>
                                </td>
                                <td>
                                    <div class="btn-group">
                                        <button class="btn btn-xs green dropdown-toggle" type="button" data-toggle="dropdown" aria-expanded="false"> Acciones
                                            <i class="fa fa-angle-down"></i>
                                        </button>
                                        <ul class="dropdown-menu" role="menu">
                                            <li>
                                                <a href="/proceso/compra/editar/<?php echo $entity->getIdcompra()?>">
                                                    <i class="fa fa-pencil"></i> Editar </a>
                                            </li>
                                            <li>
                                                <a href="javascript:;" class="delete_modal">
                                                    <i class="fa fa-trash"></i> Eliminar </a>
                                            </li>
                                        </ul>
                                    </div>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                </table>
            </div>
            <div class="row">
                <div class="col-md-5 col-sm-5">
                    <div class="dataTables_info" id="sample_editable_1_info" role="status" aria-live="polite">Mostrando registros del 1 a 5 de un total de 8 registros</div>        
                </div>
                <div class="col-md-7 col-sm-7">
                    <div class="dataTables_paginate paging_bootstrap_number" id="sample_editable_1_paginate">
                        <ul class="pagination" style="visibility: visible;">
                            <li class="prev disabled">
                                <a title="Prev" href="#">
                                    <i class="fa fa-angle-left"></i>
                                </a>
                            </li>
                            <li class="active">
                                <a href="#">1</a>
                            </li>
                            <li>
                                <a href="#">2</a>
                            </li>
                            <li class="next">
                                <a title="Next" href="#">
                                    <i class="fa fa-angle-right"></i>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>