<style>
    input[type=file]{
        padding-top: 0px;
        padding-left: 0px;
    }
    #productos_table .fa-trash{
        color:red;
    }
</style>
<div id="form_container">
<form class="form-horizontal" action="#">
    <div class="portlet box green" style="border-left-width: 0px; border-bottom-width: 0px; border-right-width: 0px;">
        <div class="portlet-body form">
            <div class="form-body">
                <h3 class="page-title">Compras - Registro</h3><br><br>
                <div class="row">
                    <div class="form-group">
                        <div class="col-md-6">

                            <?php echo $this->formLabel($form->get('compra_fechacompra')) ?>  
                            <?php echo $this->formText($form->get('compra_fechacompra')) ?> 
                        </div>
                        <div class="col-md-6">
                            <?php echo $this->formLabel($form->get('compra_tipo')) ?>  
                            <?php echo $this->formSelect($form->get('compra_tipo')) ?> 
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-6">
                            <?php echo $this->formHidden($form->get('idproveedor')); ?>  
                            <?php echo $this->formLabel($form->get('idproveedor_autocomplete')); ?>  
                            <div class="input-group">
                                <span class="input-group-addon">
                                    <i class="fa fa-search"></i>
                                </span>
                                 <?php echo $this->formText($form->get('idproveedor_autocomplete')); ?>  

                            </div>

                        </div>
                        <div class="col-md-6">
                            <?php echo $this->formLabel($form->get('compra_folio')) ?>  
                            <?php echo $this->formText($form->get('compra_folio')) ?> 
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-6">

                            <?php echo $this->formLabel($form->get('compra_fechaentrega')) ?>  
                            <?php echo $this->formText($form->get('compra_fechaentrega')) ?> 
                        </div>
                        <div class="col-md-6">
                            <?php echo $this->formLabel($form->get('compra_factura')) ?>  
                            <?php echo $this->formFile($form->get('compra_factura')) ?> 
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-6">

                            <?php echo $this->formLabel($form->get('idalmacen')) ?>  
                            <?php echo $this->formSelect($form->get('idalmacen')) ?> 
                        </div>
                        <div class="col-md-6">
                            <?php echo $this->formLabel($form->get('compra_revision')) ?>  
                            <?php echo $this->formSelect($form->get('compra_revision')) ?> 
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="portlet box green" style="border-left-width: 0px; border-bottom-width: 0px; border-right-width: 0px;">
        <div class="portlet-body form">
            <div class="portlet-body form">
                <div class="form-body">
                    <h3 class="page-title">Productos</h3><br><br>
                    <div class="row">
                        <div class="form-group">
                            <div class="col-md-5 col-md-offset-6">
                                <div class="input-group">
                                    <span class="input-group-addon">
                                        <i class="fa fa-search"></i>
                                    </span>
                                    <input id="idproducto" type="hidden">
                                    <input id="producto_autocomplete" class="form-control" type="text">
                                </div>
                            </div>
                            <div class="col-md-1">
                                <button disabled id="producto_add" class="btn grey-mint" type="button">Agregar</button>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <table class="table" id="productos_table">
                            <thead>
                                <th>Producto</th>
                                <th>Cantidad</th>
                                <th>Precio</th>
                                <th>C.U. Neto</th>
                                <th>Desc.</th>
                                <th>IEPS</th>
                                <th>Subtotal</th>
                                <th>Revisada</th>
                                <th>Almacen</th>
                                <th>Opciones</th>
                            </thead>
                            <tbody>
<!--                                <tr>
                                    <td>Producto 1</td>
                                    <td><input type="text"></td>
                                    <td><input type="text"></td>
                                    <td>$ 100.00</td>
                                    <td><input type="text"></td>
                                    <td><input type="text"></td>
                                    <td>$ 100.00</td>
                                    <td><input type="checkbox"></td>
                                    <td>
                                        <select class="form-control">
                                            <option>almacen 1</option>
                                            <option>almacen 2</option>
                                            <option>almacen 3</option>
                                        </select>
                                    </td>
                                    <td><i class="fa fa-trash"></i></td>
                                </tr>-->
                            </tbody>
                            <tfoot>
                                <tr>
                                    <td colspan="8"></td>
                                    <td>SUBTOTAL</td>
                                    <td>$0.00</td>
                                </tr>
                                <tr>
                                    <td colspan="8"></td>
                                    <td>IEPS</td>
                                    <td>$0.00</td>
                                </tr>
                                <tr>
                                    <td colspan="8"></td>
                                    <td>IVA</td>
                                    <td>$0.00</td>
                                </tr>
                                <tr>
                                    <td colspan="8"></td>
                                    <td>TOTAL</td>
                                    <td>$0.00</td>
                                </tr>
                            </tfoot>
                        </table>
                    </div>
                </div>
                <div class="form-actions right">
                    <button class="btn blue" type="submit">
                        <i class="fa fa-check"></i>
                        Guardar
                    </button>
                </div>
            </div>
        </div>
    </div>
</form>
<!--<div class="portlet light portlet-fit ">
    <div class="portlet-title">
        <div class="caption portlet">
            <h2 >Productos</h2>
        </div>
    </div>
    <div class="portlet-body">
        <div class="table-toolbar">
            <div class="row">
            </div>
        </div>
        <div id="sample_editable_1_wrapper" class="dataTables_wrapper no-footer">
            <div class="row">
                <div class="col-md-6 col-sm-6">
                    <div class="dataTables_length" id="sample_editable_1_length">
                        <label> 
                            Mostrar <select name="sample_editable_1_length" aria-controls="sample_editable_1" class="form-control input-sm input-xsmall input-inline">
                                <option value="5">5</option>
                                <option value="15">15</option>
                                <option value="20">20</option>
                                <option value="-1">All</option>
                            </select> registros</label>
                    </div>
                </div>
                <div class="col-md-6 col-sm-6">
                    <div id="sample_editable_1_filter" class="dataTables_filter">
                        <label style=" margin-left: 220px">Buscar:  
                            <input type="search" class="form-control input-sm input-small input-inline" placeholder="" aria-controls="sample_editable_1">
                        </label>
                        <button style="float: right" class="btn default">Agregar</button>
                    </div>
                </div>
            </div>
            <div class="table-scrollable">
                <table id="sample_editable_1" class="table table-striped table-hover table-bordered dataTable no-footer" role="grid" aria-describedby="sample_editable_1_info">
                    <thead>
                        <tr role="row">
                            <th class="sorting" tabindex="0" aria-controls="sample_editable_1" rowspan="1" colspan="1" style="width: 122px;" aria-label=" Full Name : activate to sort column ascending">Producto</th>
                            <th class="sorting" tabindex="0" aria-controls="sample_editable_1" rowspan="1" colspan="1" style="width: 122px;" aria-label=" Points : activate to sort column ascending">Cantidad</th>
                            <th class="sorting" tabindex="0" aria-controls="sample_editable_1" rowspan="1" colspan="1" style="width: 122px;" aria-label=" Notes : activate to sort column ascending">Precio</th>
                            <th class="sorting" tabindex="0" aria-controls="sample_editable_1" rowspan="1" colspan="1" style="width: 122px;" aria-label=" Notes : activate to sort column ascending">C.U. Neto</th>
                            <th class="sorting" tabindex="0" aria-controls="sample_editable_1" rowspan="1" colspan="1" style="width: 122px;" aria-label=" Notes : activate to sort column ascending">Desc.</th>
                            <th class="sorting" tabindex="0" aria-controls="sample_editable_1" rowspan="1" colspan="1" style="width: 122px;" aria-label=" Edit : activate to sort column ascending">IEPS</th>
                            <th class="sorting" tabindex="0" aria-controls="sample_editable_1" rowspan="1" colspan="1" style="width: 122px;" aria-label=" Edit : activate to sort column ascending">Subtotal</th>
                            <th class="sorting" tabindex="0" aria-controls="sample_editable_1" rowspan="1" colspan="1" style="width: 122px;" aria-label=" Edit : activate to sort column ascending">Revisada</th>
                            <th class="sorting" tabindex="0" aria-controls="sample_editable_1" rowspan="1" colspan="1" style="width: 122px;" aria-label=" Edit : activate to sort column ascending">Almacen</th>
                            <th class="sorting" tabindex="0" aria-controls="sample_editable_1" rowspan="1" colspan="1" style="width: 122px;" aria-label=" Edit : activate to sort column ascending">Opciones</th>
                        </tr>
                    </thead>
                CUERPO  DE LA TABLA
                      
                </table>
            </div>
            <div class="row">
                <div class="col-md-5 col-sm-5">
                    <div class="dataTables_info" id="sample_editable_1_info" role="status" aria-live="polite">Mostrando registros del 1 a 5 de un total de 8 registros</div>
                </div>
                <div class="col-md-7 col-sm-7">
                    <div class="dataTables_paginate paging_bootstrap_number" id="sample_editable_1_paginate">
                        <ul class="pagination" style="visibility: visible;">
                            <li class="prev disabled">
                                <a title="Prev" href="#">
                                    <i class="fa fa-angle-left"></i>
                                </a>
                            </li>
                            <li class="active">
                                <a href="#">1</a>
                            </li>
                            <li>
                                <a href="#">2</a>
                            </li>
                            <li class="next">
                                <a title="Next" href="#">
                                    <i class="fa fa-angle-right"></i>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div style="margin-left: 950px">
        <label>Subtotal: </label><br>
        <label>IEPS: </label><br>
        <label>IVA: </label><br>
        <label>TOTAL: </label><br><br>
    </div>
        <button style="margin-left: 970px" class="btn default">Guardar</button><br><br>
</div>-->

</div>
<script type="text/javascript" src="/application/custom/js/procesos/compra.js"></script>
<script>
    var $form = $('#form_container').compra();
    $form.new(<?php echo $anio_activo?>,<?php echo $mes_activo?>,<?php echo $almacenes?>);
</script>
