<link href="/application/global/plugins/datatables/datatables.min.css" rel="stylesheet" type="text/css" />
<link href="/application/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.css" rel="stylesheet" type="text/css" />
<div id="my_container">
    <h3 class="page-title">Kardex</h3>
    <div class="page-bar">
        <ul class="page-breadcrumb">
            <li>
                <a href="/reportes/kardex">Kardex</a>
            </li>
        </ul>
    </div>
    <?php
    $form->setAttribute('action', '/reportes/kardex');
    echo $this->form()->openTag($form);
    ?>
    <div class="portlet box green" style="border-left-width: 0px; border-bottom-width: 0px; border-right-width: 0px;">
        <div class="portlet-body form">
            <div class="form-body">
                <h3 class="form-section">Almacenes *</h3><br>
                <input type="hidden" name="almacenes" value="">
                <div class="row">
                    <div class="icheck-list">
                        <?php $almacen=new Almacen();foreach ($almacenes as $almacen):?>
                        <div class="col-md-3">
                            <label>
                                <input id="<?php echo $almacen->getIdalmacen();?>" name="gen" value="<?php echo ucfirst($almacen->getAlmacenNombre())?>" type="radio" class="icheck generado"> <?php echo ucfirst($almacen->getAlmacenNombre())?>
                            </label>
                        </div>
                        <?php endforeach;?>
                    </div>
                </div>
                <br>
                <div class="row">
                    <h3 class="form-section"></h3><br>
                    <div class="col-md-6">
                        <?php echo $this->formLabel($form->get('fecha_inicio')) ?>  
                        <?php echo $this->formDate($form->get('fecha_inicio')) ?> 
                    </div>
                    <div class="col-md-6">
                        <?php echo $this->formLabel($form->get('fecha_fin')) ?>  
                        <?php echo $this->formDate($form->get('fecha_fin')) ?> 
                    </div>
                </div>
                <h3 class="form-section">Productos</h3><br>
                <div class="row">
                    <div class="form-group">
                        <div class="col-md-4 col-md-offset-6">
                            <div class="input-group">
                                <span class="input-group-addon">
                                    <i class="fa fa-search"></i>
                                </span>
                                <input id="idproducto" type="hidden">
                                <input id="producto_autocomplete" class="form-control" type="text">
                            </div>
                        </div>
                        <div class="col-md-1">
                            <button disabled id="producto_add" class="btn grey-mint" type="button">Agregar</button>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <table class="table" id="productos_table">
                            <thead>
                            <th>Nombre producto</th>
                            </thead>
                            <tbody id="productos_table_tbody">
                            </tbody>
                        </table>
                    </div>
                </div>
                <br>
                <div class="row">
                    <div class="col-md-12">
                        <p>(*)Campos obligatorios</p>
                    </div>
                </div>
              </div>
                
                <div class="form-actions right">
                    <div class="left col-md-2">
                        <button disabled class="btn blue" id="generar_pdf" name="generar_pdf" type="submit">
                            <i class="fa fa-file-pdf-o"></i>
                            PDF
                        </button>
                    </div>
                    <div class="left col-md-2">
                        <button disabled class="btn blue" id="generar_excel" name="generar_excel" type="submit">
                            <i class="fa fa-file-excel-o"></i>
                            Excel
                        </button>
                    </div>
                    <button disabled class="btn blue" id="generar" type="button">
                        <i class="fa fa-check"></i>
                        Generar
                    </button>
                </div>

                <div class="row">
                    <div class="col-md-12" style="overflow: scroll; white-space: nowrap;">
                        <table class="table" id="reporte_table">
                            <thead>
                            <th>Fecha</th>
                            <th>Folio</th>
                            <th>Proceso</th>
                            <th>Proveedor</th>
                            <th>Entrada</th>
                            <th>Salida</th>
                            <th>Existencia</th>
                            <th>Entrada $</th>
                            <th>Salida $</th>
                            <th>Saldo</th>
                            <th>CP</th>
                            </thead>
                            <tbody id="tbody">

                            </tbody>
                        </table>
                    </div>
                </div>

            </div>
        </div>
    </div>
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.0/themes/base/jquery-ui.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js" type="text/javascript"></script>
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.0/jquery-ui.js"></script>
<script src="/application/global/plugins/typeahead/typeahead.bundle.min.js" type="text/javascript"></script>
<script type="text/javascript" src="/application/custom/js/reportes/cardex.js"></script>
<script>
    var $plugin = $('#my_container').cardex();
    $plugin.list(<?php echo "'$fecha'";?>);
</script>