<link href="/application/global/plugins/datatables/datatables.min.css" rel="stylesheet" type="text/css" />
<link href="/application/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.css" rel="stylesheet" type="text/css" />
<div id="my_container">
    <h3 class="page-title">Empresas</h3>
    <div class="page-bar">
        <ul class="page-breadcrumb">
            <li>
                <a href="/catalogo/empresa">Empresas</a>
            </li>
        </ul>
    </div>
    <?php foreach ($messages->getSuccessMessages() as $message):?>
        <div class="alert alert-success alert-dismissable">
            <button class="close" aria-hidden="true" data-dismiss="alert" type="button"></button>
            <strong>Éxito!</strong>
            <?php echo $message?>
        </div>
    <?php endforeach;?>
    <div class="portlet box green" style="border-left-width: 0px; border-bottom-width: 0px; border-right-width: 0px;">
        <div class="portlet-body form">
            <div class="form-body">
                <div class="btn-set pull-right">
                    <a href="#"><button class="btn default" type="button" style="margin-bottom: 15px;">Subir proveedores</button></a>
                    <a href="/catalogo/proveedor/nuevo"><button class="btn default" type="button" style="margin-bottom: 15px;">Nuevo proveedor</button></a>
                </div>
                <table class="table table-striped table-bordered table-hover order-column" id="datatable" style="border-bottom-width: 0px;">
                    <thead >
                        <tr>
                            <th class="text-center"> Nombre comercial </th>
                            <th class="text-center"> Razón social </th>
                            <th class="text-center"> RFC </th>
                            <th class="text-center"> Teléfono </th>
                            <th class="text-center"> Cuidad </th>
                            <th class="text-center"> Opciones </th>
                        </tr>
                    </thead>
                    
                    <tbody class="text-center">
                        <?php foreach ($collection as $entity) : ?>

                            <tr id="<?php echo $entity->getIdProveedor() ?>">
                                <td><?php echo $entity->getProveedorNombrecomercial() ?></td>
                                <td><?php echo $entity->getProveedorRazonsocial() ?></td>
                                <td><?php echo $entity->getProveedorRfc() ?></td>
                                <td><?php echo $entity->getProveedorTelefono() ?></td>
                                <td><?php echo $entity->getProveedorCiudad() ?></td>
                                
                                <td class="text-left">                                    
                                    <div class="btn-group">
                                        <button class="btn btn-xs green dropdown-toggle" type="button" data-toggle="dropdown" aria-expanded="false"> Acciones
                                            <i class="fa fa-angle-down"></i>
                                        </button>
                                        <ul class="dropdown-menu" role="menu">
                                            <li>
                                                <a href="#">
                                                    <i class="fa fa-pencil"></i> Editar </a>
                                            </li>
                                            <!--
                                            <li>
                                                <a href="javascript:;" class="delete_modal">
                                                    <i class="fa fa-trash"></i> Eliminar </a>
                                            </li>
                                            -->
                                        </ul>
                                    </div>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<script src="/application/global/scripts/datatable.js" type="text/javascript"></script>
<script src="/application/global/plugins/datatables/datatables.min.js" type="text/javascript"></script>
<script src="/application/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.js" type="text/javascript"></script>
<script src="/application/custom/js/catalogo/usuario.js" type="text/javascript"></script>	
<script>
    
    var plugin = $('#my_container').usuario();
    
    

</script>