<link href="/application/global/plugins/datatables/datatables.min.css" rel="stylesheet" type="text/css" />
<link href="/application/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.css" rel="stylesheet" type="text/css" />
<div id="my_container">
    <h3 class="page-title">Proveedores</h3>
    <div class="page-bar">
        <ul class="page-breadcrumb">
            <li>
                <a href="/catalogo/empresa">Proveedores</a>
            </li>
        </ul>
    </div>
    <?php foreach ($messages->getSuccessMessages() as $message):?>
        <div class="alert alert-success alert-dismissable">
            <button class="close" aria-hidden="true" data-dismiss="alert" type="button"></button>
            <strong>Éxito!</strong>
            <?php echo $message?>
        </div>
    <?php endforeach;?>
    <div class="portlet box green" style="border-left-width: 0px; border-bottom-width: 0px; border-right-width: 0px;">
        <div class="portlet-body form">
            <div class="form-body">
                <div class="btn-set pull-right">
                    <form action="/catalogo/proveedor/export" method="post">
                        <button class="btn default" id="generar_excel" name="generar_excel" type="submit" style="margin-bottom: 15px;">
                            <i class="fa fa-file-excel-o"></i>
                            Exportar Excel
                        </button>
                        <button class="btn default" id="generar_pdf" name="generar_pdf" type="submit" style="margin-bottom: 15px;">
                            <i class="fa fa-file-pdf-o"></i>
                            Exportar PDF
                        </button>
                        <input type="file" name="batch_proveedores" style="display: none" accept=".xls,.xlsx">
                        <a id="subir_proveedor" href="#"><button class="btn default" type="button" style="margin-bottom: 15px; margin-right: 10px">Subir proveedores</button></a>
                        <a href="/catalogo/proveedor/nuevo"><button class="btn default" type="button" style="margin-bottom: 15px;">Nuevo proveedor</button></a>
                    </form>
                </div>
                <table class="table table-striped table-bordered table-hover order-column" id="datatable" style="border-bottom-width: 0px;">
                    <thead >
                        <tr>
                            <th> Nombre comercial </th>
                            <th> Razón social </th>
                            <th> RFC </th>
                            <th> Teléfono </th>
                            <th> Ciudad </th>
                            <th> Estatus </th>
                            
                            <th> Opciones </th>
                        </tr>
                    </thead>
                    
                    <tbody>
                        <?php $entity = new Proveedor();?>
                        <?php foreach ($collection as $entity) : ?>
                            <?php 
                                
                            if ($entity->getProveedorEstatus() == 1) 
                            {
                                $estatus = 'Activo';
                                $class = 'info';
                            } 
                            else 
                            {
                                $estatus = 'Inactivo';
                                $class = 'danger';
                            }
                            
                            ?>
                            <tr id="<?php echo $entity->getIdProveedor() ?>">
                                <td><?php echo $entity->getProveedorNombrecomercial() ?></td>
                                <td><?php echo $entity->getProveedorRazonsocial() ?></td>
                                <td><?php echo $entity->getProveedorRfc() ?></td>
                                <td><?php echo $entity->getProveedorTelefono() ?></td>
                                <td><?php echo $entity->getProveedorCiudad() ?></td>
                                <td><span class="label label-sm label-<?php echo $class ?>"> <?php echo $estatus ?> </span></td>
                                <td class="text-left">                                    
                                    <div class="btn-group">
                                        <button class="btn btn-xs green dropdown-toggle" type="button" data-toggle="dropdown" aria-expanded="false"> Acciones
                                            <i class="fa fa-angle-down"></i>
                                        </button>
                                        <ul class="dropdown-menu" role="menu">
                                            <li>
                                                <a href="/catalogo/proveedor/editar/<?php echo $entity->getIdProveedor() ?>">
                                                    <i class="fa fa-pencil"></i> Editar </a>
                                            </li>
                                            <!--
                                            <li>
                                                <a href="javascript:;" class="delete_modal">
                                                    <i class="fa fa-trash"></i> Eliminar </a>
                                            </li>
                                            -->
                                        </ul>
                                    </div>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.8.0/xlsx.full.min.js"></script>
<script src="/application/global/scripts/datatable.js" type="text/javascript"></script>
<script src="/application/global/plugins/datatables/datatables.min.js" type="text/javascript"></script>
<script src="/application/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.js" type="text/javascript"></script>
<script src="/application/custom/js/catalogo/usuario.js" type="text/javascript"></script>	
<script>
    
    var plugin = $('#my_container').usuario();
    
    

</script>